<div class="main_body">
    <div class="left width-100">
        <div id="wall-profile">
        <div id="wall_container">

<div id="updateboxarea">
<h4>What's up?</h4>
<div id="searchbox">
Search Friend:<input type="text" class="uiinput" id="searchinput"  />
<div id="display" ></div>
</div>
<textarea name="update" id="update" maxlength="200" ></textarea>
<br />
<div id="webcam_container" class='border'>
<div id="webcam" >
</div>
<div id="webcam_preview">

</div>

<div id='webcam_status'></div>
<div id='webcam_takesnap'>

<input type="button" value=" Take Snap " onclick="return takeSnap();" class="camclick button"/>
<input type="hidden" id="webcam_count" />
</div>
</div>
<div  id="imageupload" class="border">
<form id="imageform" method="post" enctype="multipart/form-data" action='<?php echo $this->baseUrl("wall/index/imageajax"); ?>'> 
<div id='preview'>
</div>

<span id='addphoto'>Add Photo:</span> <input type="file" name="photoimg" id="photoimg" />
<input type='hidden' id='uploadvalues' />
</form>
</div>
<div style="width:100%;clear:both">
<input type="submit"  value=" Update "  id="update_button"  class="update_button"/> 
<span style="float:right">
<a href="javascript:void(0);" id="camera" title="Upload Image"><img src="<?php echo $this->baseUrl('public/wall/images/icons/cameraa.png');?>" border="0" /></a> 
 <a href="javascript:void(0);" id="webcam_button" title="Webcam Snap"><img src="<?php echo $this->baseUrl('public/wall/images/icons/web-cam.png');?>"  border="0"  style='margin-top:5px'/></a>
</span>
</div>

</div>

<div id='flashmessage'>
<div id="flash" align="left"  ></div>
</div>
<div id="content">

<?php 
// Loading Messages
//include('load_messages.php'); 
echo $this->action('loadmessage', 'index', 'wall', array(86));
?>

</div>
</div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>