<div class="main_body">
					<div class="left width-100">
						<div id="wall-profile">
							<div class="messaging">
								<textarea></textarea>
								<div class="clear">&nbsp;</div>
								<input type="button" value="share" />
								<a href="javascript:void(0)" class="image">image</a>
								<a href="javascript:void(0)" class="video">video</a>
								<div class="clear">&nbsp;</div>
							</div>
							<div class="profile_posts">
								<ul>
									<li class="post">
										<div class="post_image"><a href="javascript:void(0)"><img src="images/profile_image.png" /></a></div>
										<div class="postInformation">
											<div class="left width-100">
												<h5>Hi Friend check in <a href="#">getlinc</a> for new desings cloths</h5>
												<div class="detail"><a href="javascript:void(0)">Comment</a>| 8 Minutes Ago |<a href="javascript:void(0)">Share</a></div>
												<div class="subcomment">
													<div class="post_image"><a href="javascript:void(0)"><img src="images/profile_image.png" /></a></div>
													<div class="postInformation">
														<div class="left width-100">
															<h5>Hi Friend check in <a href="#">getlinc</a> for new desings cloths</h5>
															<div class="detail"><a href="javascript:void(0)">Comment</a>| 8 Minutes Ago |<a href="javascript:void(0)">Share</a></div>
															
															<div class="clear"></div>
														</div>
													</div>
													<div class="clear"></div>
												</div>
												<div class="subcomment">
													<div class="post_image"><a href="javascript:void(0)"><img src="images/profile_image.png" /></a></div>
													<div class="postInformation">
														<div class="left width-100">
															<h5>Hi Friend check in <a href="#">getlinc</a> for new desings cloths</h5>
															<div class="detail"><a href="javascript:void(0)">Comment</a>| 8 Minutes Ago |<a href="javascript:void(0)">Share</a></div>
															
															<div class="clear"></div>
														</div>
													</div>
													<div class="clear"></div>
												</div>
												<div class="clear"></div>
											</div>
										</div>
										<div class="clear"></div>
									</li>
									<li class="post">
										<div class="post_image"><a href="javascript:void(0)"><img src="images/profile_image.png" /></a></div>
										<div class="postInformation">
											<div class="left width-100">
												<h5>Hi Friend check in <a href="#">getlinc</a> for new desings cloths</h5>
												<div class="detail"><a href="javascript:void(0)">Comment</a>| 8 Minutes Ago |<a href="javascript:void(0)">Share</a></div>
												
												<div class="clear"></div>
											</div>
										</div>
										<div class="clear"></div>
									</li>
									<li class="post">
										<div class="post_image"><a href="javascript:void(0)"><img src="images/profile_image.png" /></a></div>
										<div class="postInformation">
											<div class="left width-100">
												<h5>Hi Friend check in <a href="#">getlinc</a> for new desings cloths</h5>
												<div class="detail"><a href="javascript:void(0)">Comment</a>| 8 Minutes Ago |<a href="javascript:void(0)">Share</a></div>
												<div class="subcomment">
													<div class="post_image"><a href="javascript:void(0)"><img src="images/profile_image.png" /></a></div>
													<div class="postInformation">
														<div class="left width-100">
															<h5>Hi Friend check in <a href="#">getlinc</a> for new desings cloths</h5>
															<div class="detail"><a href="javascript:void(0)">Comment</a>| 8 Minutes Ago |<a href="javascript:void(0)">Share</a></div>
															
															<div class="clear"></div>
														</div>
													</div>
													<div class="clear"></div>
												</div>
												<div class="clear"></div>
											</div>
										</div>
										<div class="clear"></div>
									</li>
									<li class="post">
										<div class="post_image"><a href="javascript:void(0)"><img src="images/profile_image.png" /></a></div>
										<div class="postInformation">
											<div class="left width-100">
												<h5>Hi Friend check in <a href="#">getlinc</a> for new desings cloths</h5>
												<div class="detail"><a href="javascript:void(0)">Comment</a>| 8 Minutes Ago |<a href="javascript:void(0)">Share</a></div>
												<div class="media">
													<img src="images/camtwo.jpg" title="image" />
													<img src="images/camtwo.jpg" title="image" />
													<img src="images/camtwo.jpg" title="image" />
													<img src="images/camtwo.jpg" title="image" />
													<div class="clear"></div>
												</div>
												<div class="subcomment img">
													<div class="post_image"><a href="javascript:void(0)"><img src="images/profile_image.png" /></a></div>
													<div class="postInformation">
														<div class="left width-100">
															<h5>Hi Friend check in <a href="#">getlinc</a> for new desings cloths</h5>
															<div class="detail"><a href="javascript:void(0)">Comment</a>| 8 Minutes Ago |<a href="javascript:void(0)">Share</a></div>
															
															<div class="clear"></div>
														</div>
													</div>
													<div class="clear"></div>
												</div>
												<div class="clear"></div>
											</div>
										</div>
										<div class="clear"></div>
									</li>
								</ul>
							</div>
						</div>
						<div class="clear"></div>
					</div>
					<div class="clear"></div>
				</div>