<?php
//Srinivas Tamada http://9lessons.info
//Loading Comments link with load_updates.php 
// $commentsarray=$Wall->Comments($msg_id,0);

if($this->comment_count>2)
{
?>  
<div class="comment_ui" id="view<?php echo $this->msg_id; ?>">
<a href="javascript:void(0)" class="view_comments" id="<?php echo $this->msg_id; ?>" msg_uid="<?php echo $this->msg_uid; ?>" vi='<?php echo $this->comment_count; ?>'>View all <?php echo $this->comment_count; ?> comments</a>
</div>
<?php

}

//print_r($this->commentsarray);
if(!empty($this->commentsarray))
{
foreach($this->commentsarray as $cdata)
 {
 $com_id=$cdata['comment_id'];
 $comment=tolink(htmlcode($cdata['wall_comment'] ));
  $time=strtotime( $cdata['createddatetime']);
$mtime=date("c", $time);
   //$username=$cdata['emailid'];
   $username=$cdata['firstname']." ".$cdata['lastname'];
  $com_uid=$cdata['userid'];
  $image_path=$cdata['image_path'];
 // User Avatar
 if($image_path=='')
 $cface=$this->baseUrl('public/uploads/user_images/No_Image_Available.jpg');
 else
 $cface=$this->baseUrl('public/uploads/user_images/crop_200_200/'.$image_path);
  // End Avatar
 ?>
<div class="stcommentbody" id="stcommentbody<?php echo $com_id; ?>">
<div class="stcommentimg">
<img src="<?php echo $cface; ?>" class='small_face' alt='<?php echo $username; ?>'/>
</div> 
<div class="stcommenttext">
<?php if($this->userid==$com_uid || $this->userid==$this->msg_uid ){ ?>
<a class="stcommentdelete" href="#" id='<?php echo $com_id; ?>' title='Delete Comment'></a>
<?php } ?>
<b><a href="<?php echo $this->baseUrl("wall/index/profile/userid/".$com_uid); ?>"><?php echo $username; ?></a></b> <?php echo clear($comment); ?>
<div class="stcommenttime" title="<?php echo $mtime; ?>"></div> 
</div>
</div>
<?php 
}
}
?>