<div class="widget">
	<div class="widget-block">
		<div class="widget-header">Friend Suggestion</div>
		<div class="widget-cont">
			<ul class="thumbnail">
				<li>
					<div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></div>
					<div class="information">
						<h6>User Four</h6>
						<span>0 mutual friends</span>
					</div>
					<div class="actions">
						<a href="javascript:void(0)" class="accept">ok</a>
						<a href="javascript:void(0)" class="regect">Cacel</a>
					</div>
					<div class="clear"></div>
				</li>
				<li>
					<div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></div>
					<div class="information">
						<h6>User Four</h6>
						<span>0 mutual friends</span>
					</div>
					<div class="actions">
						<a href="javascript:void(0)" class="accept">ok</a>
						<a href="javascript:void(0)" class="regect">Cacel</a>
					</div>
					<div class="clear"></div>
				</li>
				<li>
					<div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></div>
					<div class="information">
						<h6>User Four</h6>
						<span>0 mutual friends</span>
					</div>
					<div class="actions">
						<a href="javascript:void(0)" class="accept">ok</a>
						<a href="javascript:void(0)" class="regect">Cacel</a>
					</div>
					<div class="clear"></div>
				</li>
			</ul>
		</div>
	</div>
</div>
