<?php 
$session = new Zend_Session_Namespace('MyPortal');
//$error = new Zend_Session_Namespace('MyPortalerror');
$fc = Zend_Controller_Front::getInstance()->getRequest();
$action = $fc->getActionName();
$config=Zend_Registry::get('config');	
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<!--
		Charisma v1.0.0

		Copyright 2012 Muhammad Usman
		Licensed under the Apache License v2.0
		http://www.apache.org/licenses/LICENSE-2.0

		http://usman.it
		http://twitter.com/halalit_usman
	-->
	<meta charset="utf-8">
	<title>.: GetLinc Admin <?php echo $this->title;?> :.</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
	<meta name="description" content="Description"></meta>
	<meta name="author" content="author"></meta>
	<meta name="keywords" content="Keywords" ></meta>
	<script type="text/javascript">var baseUrl='<?php echo $config->site->baseurl;?>';</script>
	<!-- The styles -->
	<link id="bs-css" href="<?php echo $this->baseUrl('public/admin'); ?>/css/bootstrap-cerulean.css" rel="stylesheet">
	<style type="text/css">
	  body {
		padding-bottom: 40px;
	  }
	  .sidebar-nav {
		padding: 9px 0;
	  }
	</style>
	<link href="<?php echo $this->baseUrl('public/admin'); ?>/css/bootstrap-responsive.css" rel="stylesheet">
	<link href="<?php echo $this->baseUrl('public/admin'); ?>/css/charisma-app.css" rel="stylesheet">
	<link href="<?php echo $this->baseUrl('public/admin'); ?>/css/jquery-ui-1.8.21.custom.css" rel="stylesheet">
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/css/fullcalendar.css' rel='stylesheet'>
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/css/fullcalendar.print.css' rel='stylesheet'  media='print'>
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/css/chosen.css' rel='stylesheet'>
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/css/uniform.default.css' rel='stylesheet'>
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/css/colorbox.css' rel='stylesheet'>
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/css/jquery.cleditor.css' rel='stylesheet'>
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/css/jquery.noty.css' rel='stylesheet'>
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/css/noty_theme_default.css' rel='stylesheet'>
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/css/elfinder.min.css' rel='stylesheet'>
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/css/elfinder.theme.css' rel='stylesheet'>
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/css/jquery.iphone.toggle.css' rel='stylesheet'>
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/css/opa-icons.css' rel='stylesheet'>
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/css/uploadify.css' rel='stylesheet'>

	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

	<!-- The fav icon -->
	<link rel="shortcut icon" href="<?php echo $this->baseUrl('public/admin'); ?>/img/favicon.ico">
	
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery-1.7.2.min.js"></script>
		
</head>

<body>
	<!-- topbar starts -->
	<?php echo $this->render('admin/header.phtml') ?>
	<!-- topbar ends -->
		<div class="container-fluid">
		<div class="row-fluid">
				
			<!-- left menu starts -->
			<?php echo $this->render('admin/leftmenu.phtml') ?><!--/span-->
			<!-- left menu ends -->
			
			<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>
			
			<div id="content" class="span10" style="min-height:500px;">
			<!-- content starts -->
			<?php  echo $this->layout()->content ?>		
			</div><!--/.fluid-container-->
			<!-- content ends -->
		  </div>
			<!--/#content.span10-->
		</div><!--/fluid-row-->
		
		
		
		
			<hr>

			<div class="modal hide fade" id="myModal">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">×</button>
					<h3>Settings</h3>
				</div>
				<div class="modal-body">
					<p>Here settings can be configured...</p>
				</div>
				<div class="modal-footer">
					<a href="#" class="btn" data-dismiss="modal">Close</a>
					<a href="#" class="btn btn-primary">Save changes</a>
				</div>
			</div>

			<footer>
				<p class="pull-left">&copy; <?php echo date('Y')-1,"-",date('Y');?> <?php echo $config->site->footer->label;?></p>
				<p class="pull-right">Powered by: AllySoft</p>
			</footer>
			
			
	
	

	<!-- external javascript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->

	<!-- jQuery -->
	<!-- <script src="<?php //echo $this->baseUrl('public/admin'); ?>/js/jquery-1.7.2.min.js"></script>-->
	<!-- jQuery UI -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery-ui-1.8.21.custom.min.js"></script>
	<!-- transition / effect library -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/bootstrap-transition.js"></script>
	<!-- alert enhancer library -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/bootstrap-alert.js"></script>
	<!-- modal / dialog library -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/bootstrap-modal.js"></script>
	<!-- custom dropdown library -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/bootstrap-dropdown.js"></script>
	<!-- scrolspy library -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/bootstrap-scrollspy.js"></script>
	<!-- library for creating tabs -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/bootstrap-tab.js"></script>
	<!-- library for advanced tooltip -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/bootstrap-tooltip.js"></script>
	<!-- popover effect library -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/bootstrap-popover.js"></script>
	<!-- button enhancer library -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/bootstrap-button.js"></script>
	<!-- accordion library (optional, not used in demo) -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/bootstrap-collapse.js"></script>
	<!-- carousel slideshow library (optional, not used in demo) -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/bootstrap-carousel.js"></script>
	<!-- autocomplete library -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/bootstrap-typeahead.js"></script>
	<!-- tour library -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/bootstrap-tour.js"></script>
	<!-- library for cookie management -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.cookie.js"></script>
	<!-- calander plugin -->
	<script src='<?php echo $this->baseUrl('public/admin'); ?>/js/fullcalendar.min.js'></script>
	<!-- data table plugin -->
	<script src='<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.dataTables.min.js'></script>

	<!-- chart libraries start -->
	<!-- <script src="<?php echo $this->baseUrl('public/admin'); ?>/js/excanvas.js"></script> -->
	<!-- <script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.flot.min.js"></script> -->
	<!-- <script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.flot.pie.min.js"></script> -->
	<!-- <script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.flot.stack.js"></script> -->
	<!-- <script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.flot.resize.min.js"></script> -->
	<!-- chart libraries end -->

	<!-- select or dropdown enhancer -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.chosen.min.js"></script>
	<!-- checkbox, radio, and file input styler -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.uniform.min.js"></script>
	<!-- plugin for gallery image view -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.colorbox.min.js"></script>
	<!-- rich text editor library -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.cleditor.min.js"></script>
	<!-- notification plugin -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.noty.js"></script>
	<!-- file manager library -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.elfinder.min.js"></script>
	<!-- star rating plugin -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.raty.min.js"></script>
	<!-- for iOS style toggle switch -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.iphone.toggle.js"></script>
	<!-- autogrowing textarea plugin -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.autogrow-textarea.js"></script>
	<!-- multiple file upload plugin -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.uploadify-3.1.min.js"></script>
	<!-- history.js for cross-browser state change on ajax -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/jquery.history.js"></script>
	<!-- application script for Charisma demo -->
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/js/charisma.js"></script>
	
	<!-- Dev JS -->	
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/dev_js/jqueryvalidate.js"></script>
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/dev_js/common.js"></script>
	<script src="<?php echo $this->baseUrl('public/admin'); ?>/dev_js/layout.js"></script>
	<!-- Dev CSS -->
	<link href='<?php echo $this->baseUrl('public/admin'); ?>/dev_css/style.css' rel='stylesheet'>
	
		

<div style="font-sze:12px; width:1000px; margin:auto; margin-bottom:5px;">
<?php
$config=Zend_Registry::get('config');
if($config->show->filepath==1){ 
echo "path: ".dirname(__FILE__);
$fc = Zend_Controller_Front::getInstance()->getRequest();
echo "&nbsp;&nbsp;,&nbsp;&nbsp; module: ".$module = $fc->getModuleName();
echo "&nbsp;&nbsp;,&nbsp;&nbsp; controller: ".$controller = $fc->getControllerName();
echo "&nbsp;&nbsp;,&nbsp;&nbsp; action: ".$action = $fc->getActionName();
echo "&nbsp;&nbsp;,&nbsp;&nbsp; layout: layout.phtml";
}
?>
</div>
		
</body>
</html>


