<div class="span2 main-menu-span">
	<div class="well nav-collapse sidebar-nav">
		<ul class="nav nav-tabs nav-stacked main-menu">
			<li class="nav-header hidden-tablet">Users Management</li>
			<li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/usermanagement/user/list"><i class="icon-home"></i><span class="hidden-tablet">Users's</span></a></li>
			<li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/merchant/list"><i class="icon-home"></i><span class="hidden-tablet">Merchant's</span></a></li>
		</ul>
		<ul class="nav nav-tabs nav-stacked main-menu">
			<li class="nav-header hidden-tablet">Products Management</li>
			<li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/products/list"><i class="icon-home"></i><span class="hidden-tablet">Products's</span></a></li>
			<li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/category/list"><i class="icon-home"></i><span class="hidden-tablet">Categories's</span></a></li>
			<li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/attributes/list"><i class="icon-home"></i><span class="hidden-tablet">Attributes's</span></a></li>
			<li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/attributesets/list"><i class="icon-home"></i><span class="hidden-tablet">Attributes Set's</span></a></li>
			<li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/attributesgroups/list"><i class="icon-home"></i><span class="hidden-tablet">Attributes Group's</span></a></li>
		</ul>
		<ul class="nav nav-tabs nav-stacked main-menu">
			<li class="nav-header hidden-tablet">Invoice Management</li>	
			<li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/invoices/list"><i class="icon-eye-open"></i><span class="hidden-tablet">Invoice's</span></a></li>				
		</ul>
		<ul class="nav nav-tabs nav-stacked main-menu">
			<li class="nav-header hidden-tablet">Security Settings</li>	
			<li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/useractivitylog/list"><i class="icon-eye-open"></i><span class="hidden-tablet">User Activity Log</span></a></li>			
			<li><a class="ajax-link" href="<?php echo $this->baseUrl();?>/admin/index/logout"><i class="icon-eye-open"></i><span class="hidden-tablet">Logout</span></a></li>			
		</ul>		
	</div><!--/.well -->
</div>