<div class="widget">
    <div class="widget-block">
        <div class="widget-header">Top Brands</div>
        <div class="widget-cont">
		
			
			
            <ul class="thumbnail">
                <li>
                    <div class="imagebrand">
						<a href="<?php echo $this->baseUrl('brands/list');?>">
						<img src="<?php echo $this->baseUrl('public/uploads/brands_images'); ?>/Levis.jpg" height="50"/>
						</a>
					</div>
					<div class="imagebrand"><img src="<?php echo $this->baseUrl('public/uploads/brands_images'); ?>/Nike.jpg" height="50"/></div>
					<div class="imagebrand"><img src="<?php echo $this->baseUrl('public/uploads/brands_images'); ?>/Levis.jpg" height="50"/></div>
					<div class="imagebrand"><img src="<?php echo $this->baseUrl('public/uploads/brands_images'); ?>/Nike.jpg" height="50"/></div>
					<div class="imagebrand"><img src="<?php echo $this->baseUrl('public/uploads/brands_images'); ?>/Levis.jpg" height="50"/></div>
					<div class="imagebrand"><img src="<?php echo $this->baseUrl('public/uploads/brands_images'); ?>/Nike.jpg" height="50"/></div>
					<div class="imagebrand"><img src="<?php echo $this->baseUrl('public/uploads/brands_images'); ?>/Levis.jpg" height="50"/></div>
					<div class="imagebrand"><img src="<?php echo $this->baseUrl('public/uploads/brands_images'); ?>/Nike.jpg" height="50"/></div>
                   
					<div class="clear"></div>
                </li>				
				
            </ul>
        </div>
    </div>
</div>