<?php
//echo "<pre>";
//print_r($this->ProductsList);
//echo count($this->ProductsList);
?>
<div class="main_body">
<div class="left width-100">


<div class="product_list">
<h4>Digital Cameras Best Sellers</h4>
</div>
<br>

<img src="<?php echo $this->baseUrl('public/uploads/merchant_banners/levis_banner_1.jpg');?>" />
<?php /*<img src="<?php echo $this->baseUrl('public/uploads/merchant_banners/levis_banner_2.jpg');?>" />
<img src="<?php echo $this->baseUrl('public/uploads/merchant_banners/levis_banner_3.jpg');?>" />*/?>
	

</div>
<div class="clear"></div>
</div>