<?php
$session = new Zend_Session_Namespace('MyPortal');
$errorsession=new Zend_Session_Namespace("addmerchant");	
$error = $this;

$attributesets_count = $this->attributesets_count;
$attributesets_list = $this->attributesets_list;

$cn=$this->iColumnName;
$do=$this->iDisplayOrder;
if($cn==""){$cn=1;}
if($do==""){$do='DESC';}
$cn='';
?>

			<?php if($session->validateerror != '') { ?>      			
				<div class="alert alert-error" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $session->validateerror;?>
				</div>
      		<?php $session->validateerror=''; } ?>
						
			
			<?php if($session->success != '') { ?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $session->success;?>
				</div>
      		<?php $session->success = '';} ?>
			
      		<?php if($errorsession->success != '') { ?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $errorsession->success;?>
				</div>
			<?php $errorsession->success = '';} ?>
			
			<?php if($error->error != ''){ ?>      			
      			<div class="alert alert-error" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $error->error;?>
				</div>
      		<?php } ?>
		

		
			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Attribute Set's</h2>
						<a href="<?php echo $this->baseUrl('admin/attributesets/register');?>"><button class="btn btn-small" style="float:right;">Add New Attribute Set</button></a>					
					</div>
					<div class="box-content">
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>Sl No.</th>
								  <th>Attribute Set's Title</th>
								  <th>Attribute Group's Title</th>
								  <th>Status</th>								  
								  <th>Actions</th>								  
							  </tr>
						  </thead>   
						  <tbody>
							<?php
							$i=1;
							foreach($attributesets_list as $each_attributesets){
							?>
							<tr>
								<td align="center"><?php echo $i;$i++;?></td>
								<td><?php echo $each_attributesets['attributes_set_title'];?></td>
								<td><?php echo $each_attributesets['attributes_group_title'];?></td>
								<td class="center">
								
																		
									<?php if($each_attributesets['statusid']=="1") {?>
									<a href="<?php echo $this->baseUrl('admin/attributesets/lock/attributes_set_id/') . $each_attributesets['attributes_set_id'];?>" onClick="return confirm('Do you want to continue?')">
									<span class="label label-success">Active</span>
									</a>
									<?php }?>
									<?php if($each_attributesets['statusid']=="6") {?>
									<a href="<?php echo $this->baseUrl('admin/attributesets/unlock/attributes_set_id/') . $each_attributesets['attributes_set_id'];?>" onClick="return confirm('Do you want to continue?')">
									<span class="label">Inactive</span>
									</a>							   
									<?php } ?>
									
								</td>
								<td class="center">								
									
									<a class="btn btn-info" href="<?php echo $this->baseUrl('admin/attributesets/edit/attributes_set_id/') . $each_attributesets['attributes_set_id'];?>">
										<i class="icon-edit icon-white"></i>  
										Edit                                            
									</a>
									<a class="btn btn-danger" href="<?php echo $this->baseUrl('admin/attributesets/delete/attributes_set_id/') . $each_attributesets['attributes_set_id'];?>" onClick="return confirm('Do you want to continue?')">
										<i class="icon-trash icon-white"></i> 
										Delete
									</a>
									
								</td>							
							</tr>
							<?php }?>
							
						  </tbody>
					  </table>            
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
			<!--/row-->
			<!--/row-->
			<!--/row-->
    
			  
				
<script type="text/javascript">
  $(document).ready(function() {
	  $(".error").fadeOut(6000);
});
</script>

		
