<?php
$session = new Zend_Session_Namespace('MyPortal');
$errorsession=new Zend_Session_Namespace("addmerchant");
$error = $this;

$attribute_count = $this->attribute_count;
$attribute_list = $this->attribute_list;

$cn=$this->iColumnName;
$do=$this->iDisplayOrder;
if($cn==""){$cn=1;}
if($do==""){$do='DESC';}
$cn='';
?>

		<?php 
      		if($error->error != '') {?>      			
      			<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $error->error;?>
				</div>
      		<?php }else if($session->validateerror != '') {?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $session->validateerror;?>
				</div>
      		<?php $session->validateerror='';      			
      		} else if($session->success != '') {?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $session->success;?>
				</div>
      		<?php $session->success = '';
      		} else if($errorsession->success != '') {?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $errorsession->success;?>
				</div>
			<?php
      			$errorsession->success = '';
      		}
			?>
		
		

		
			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Attribute's</h2>
						<a href="<?php echo $this->baseUrl('admin/attributes/register');?>"><button class="btn btn-small" style="float:right;">Add New Attribute</button></a>					
					</div>
					<div class="box-content">
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>Sl No</th>
								  <th>Attribute Title</th>
								  <th>Attribute Field Type</th>
								  <th>Attribute Data Type</th>
								  <th>Attribute Values</th>
								  <th>Status</th>								  
								  <th>Actions</th>								  
							  </tr>
						  </thead>   
						  <tbody>
							<?php 
							$i=1;
							foreach($attribute_list as $each_attribute){
							?>
							<tr>
								<td><?php echo $i;$i++;?></td>
								<td><?php echo $each_attribute['attribute_title'];?></td>
								<td><?php echo $each_attribute['attribute_field_type'];?></td>
								<td><?php echo $each_attribute['attribute_data_type'];?></td>
								<td><?php echo str_replace(',','<br>',$each_attribute['attribute_values']);?></td>
								<td class="center">
									
									<?php if($each_attribute['statusid']=="1") {?>
									<a href="<?php echo $this->baseUrl('admin/attributes/lock/attributeId/') . $each_attribute['attribute_id'];?>" onClick="return confirm('Do you want to continue?')">
									<span class="label label-success">Active</span>
									</a>
									<?php }?>
									<?php if($each_attribute['statusid']=="6") {?>
									<a href="<?php echo $this->baseUrl('admin/attributes/unlock/attributeId/') . $each_attribute['attribute_id'];?>" onClick="return confirm('Do you want to continue?')">
									<span class="label">Inactive</span>
									</a>							   
									<?php } ?>
									
								</td>								
								<td class="center">
									
									<a class="btn btn-info" href="<?php echo $this->baseUrl('admin/attributes/edit/attributeId/') . $each_attribute['attribute_id'];?>">
										<i class="icon-edit icon-white"></i>  
										Edit                                            
									</a>
									<a class="btn btn-danger" href="<?php echo $this->baseUrl('admin/attributes/delete/attributeId/') . $each_attribute['attribute_id'];?>" onClick="return confirm('Do you want to continue?')">
										<i class="icon-trash icon-white"></i> 
										Delete
									</a>
									
								</td>
							</tr>
							<?php }?>
						  </tbody>
					  </table>            
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
			<!--/row-->
			<!--/row-->
			<!--/row-->
    
			  
				
<script type="text/javascript">
  $(document).ready(function() {
	  $(".error").fadeOut(6000);
});
</script>

		
