<?php
$session = new Zend_Session_Namespace('MyPortal');
//$error = new Zend_Session_Namespace('MyPortalerror');
$error = $this;
?>
<script type="text/javascript">	
jQuery(document).ready(function() {
	//jQuery("#loginid").focus();     /*for autofocus on first field*/
// validate signup form on keyup and submit
	validatesforgotpassword();
});
</script>





<div class="row-fluid">
	<div class="well span5 center login-box">			
			<h3>Forgot Password</h3><br>
			<?php 
			if($error->error != '') {
				echo '<div class="alert alert-error" id="error1">' . $error->error . '</div>';
				$error->error = '';
			}
			?>
			<div class="alert alert-info">			
			Please enter your Username you use to Sign In to your account.  Your temporary password will be emailed to you.
			</div>
		
		<br>
		<form id="signupform" autocomplete="off"  method="post" action="" class="registration" enctype="multipart/form-data">
			<fieldset>
				<div class="input-prepend" title="Username" data-rel="tooltip">Username
					<span class="add-on"><i class="icon-user"></i></span>
					<input class="field" tabindex="1"
	id="loginid" name="loginid" type="text" value="<?php if(is_array($error->error_forgot_values)) {echo strip_tags($error->error_forgot_values['loginid']); $error->error_forgot_values= '';}?>" maxlength="50" title=""
	size="40" />
				</div>
				<span class="error_message"><?php
				if($error->error_forgot_loginid != '') {
					echo '<label class="error">' . $error->error_forgot_loginid . '</label>';
					$error->error_forgot_loginid = '';
				}
				?></span>
				<div class="clearfix"></div>				
				<div class="clearfix"></div>

				<p class="center span5">
				<input id="signup" name="signup" type="submit" class="btn btn-primary" value="Submit" tabindex="2" align="left" title="" style="width:100px;"/>
				</p>
			</fieldset>
		</form>
		
	</div><!--/span-->
</div><!--/row-->




<script type="text/javascript">	
jQuery(document).ready(function() {
	jQuery("#loginid").focus();     /*for autofocus on first field*/
// validate signup form on keyup and submit
	//validatesforgotpassword();
});
</script>
