<?php 
	$session = new Zend_Session_Namespace('MyPortal');
	$error = new Zend_Session_Namespace('MyPortalerror');

	if($error->error != '') {
		$error->error = '';
	}
			 
 ?>
<div class="row-fluid">
	<div class="well span5 center login-box" style="width:700px;">			
			<h3>Forgot Password - Success...!</h3><br>			
			<div class="alert alert-success" id="error1"><?php echo "Hi " . urldecode($session->userTempName);?>,<br/> Your Password has been mailed to your Email Id. Click continue to proceed !!</div>
				
			<a href="<?php echo $this->baseUrl('admin/index/index');?>" style="padding-left:0px"><input id="signupsubmit" name="signup" type="submit" alt="Continue button" title="" class="btn btn-primary" value="Continue" tabindex="1" style="width:100px;"  /></a>
			
		
		<br>
		<div class="box-content">
		
		<div class="box-content">
	</div><!--/span-->
</div><!--/row-->
 