<?php
$session = new Zend_Session_Namespace('MyPortal');
//$error = new Zend_Session_Namespace('MyPortalerror');
$error = $this;
?>



<div class="row-fluid">
	<div class="well span5 center login-box" style="width:700px;">			
			<h3>Forgot Password - Challenge Question</h3><br>
			<?php 
			if($session->success != '') {
				echo '<div class="alert alert-success" id="error1">'.urldecode($session->success).'</div>';
				$session->success = '';
			} else if($error->error != '') {
				echo '<div class="alert alert-error" id="error1">'.$error->error.'</div>';
				$error->error = '';
			}
			?>
			<div class="alert alert-info">			
			Please fill in the form to complete the Account challenge question reset process.
			</div>
		
		<br>
		<div class="box-content">
		<form id="signupform" autocomplete="off"  method="post" action="" class="registration" enctype="multipart/form-data">
			<fieldset>			
				<div class="control-group">				  
				  <div class="controls">
					<div class="mid_Control-profile float-left" style="float:left;">
					<div style="width:160px; float:left; text-align:right;">Challenge Question : </div>&nbsp;
					<?php
					if(substr(trim($this->securityquestions['securityquestion']), -1) == '?') {
						echo $this->securityquestions['securityquestion']; 
					} else {
						echo $this->securityquestions['securityquestion'] . '?';	
					}
					?>
					<?php
						echo "<input type=\"hidden\" name=\"secureid\" id=\"secureid\" value=\"" . $this->securityquestions['securityquestionid'] . "\"/>"; 
						//echo $this->securityquestions['securityquestion'] . "<b style=\"color: #bf0000;\">*</b>";
					?>
					</div>				   					   
				  </div>
				</div>				
				<div class="clearfix"><br></div>
				
							   
				<div class="control-group">				  
				  <div class="controls">
					<div class="mid_Control-profile float-left" style="float:left;">					
					<div style="width:160px; float:left; text-align:right;">Secret Answer : </div>&nbsp;
					<input class="field" tabindex="1" id="answer" name="answer" type="text" value="" maxlength="30" size="40" title=""/>
					</div>
					   <div class="error_message">
					   <?php 
						if($error->error_forgot_question_answer != '') {
							echo  '<label class="error">' . $error->error_forgot_question_answer . '</label>';
							$error->error_forgot_question_answer = '';
						   }
					   ?>
					   </div>
					   					   
				  </div>
				</div>
				<div class="clearfix"></div>
				
				
				<div class="control-group">				  
				  <div class="controls">
					<div class="mid_Control-profile float-left" style="float:left;">
					<div style="width:160px; float:left; text-align:right;">Re-enter Secret Answer : </div>&nbsp;
					<input class="field" tabindex="2" id="retypeanswer" name="retypeanswer" type="text" value="" maxlength="30" size="40" title=""/>
					</div>				
					   <div class="error_message">
					   <?php 
						if($error->error_forgot_question_answer_confirm != '') {
						echo  '<label class="error">' . $error->error_forgot_question_answer_confirm . '</label>';
						$error->error_forgot_question_answer_confirm = '';
					   }
					   ?>
					   </div>
					   					   
				  </div>
				</div>
				<div class="clearfix"></div>


				
				<div class="clearfix"></div>

				<p class="center span5">				
				<input id="signupsubmit" name="signup" type="submit" class="btn btn-primary" value="Submit" tabindex="3" align="left" title="" style="width:100px; float:left;" />
				</p>
			</fieldset>
		</form>
		<div class="box-content">
	</div><!--/span-->
</div><!--/row-->


  
<script type="text/javascript"> 
  jQuery(document).ready(function() {
	  //jQuery("#answer").focus();     /*for autofocus on first field*/
	  validatesforgotsecurity();	
	  jQuery("#errordisplay").fadeOut(8000);
	});  
</script>