<?php 
$session = new Zend_Session_Namespace('MyPortal');	
$errorsession=new Zend_Session_Namespace("addmerchant");
$error = $this;

?>
<script type="text/javascript">
jQuery(document).ready(function() {
	 validateslogin();	
});
</script>

<div class="row-fluid">
	<div class="well span5 center login-box">
			
			<?php              
				if($error->error != '') {
					echo '<div class="alert alert-error" id="error1">';
					echo $error->error;
					echo '</div>';
					$error->error = '';
				}else if($session->failure!=''){
					echo '<div class="alert alert-error" id="error1">';
					echo $session->failure;
					echo '</div>';
					$session->failure = '';
				}else if($session->success != ''){
					echo '<div class="alert alert-success" id="error1">';
					echo $session->success;
					echo '</div>';
					$session->success = '';
				}else if($errorsession->success != ''){
					echo '<div class="alert alert-success" id="error1">';
					echo $errorsession->success;
					echo '</div>';
					$errorsession->success = '';
				}
			?>
		
		<br>
		<form id="signupform" autocomplete="off"  method="post" action="" class="registration" enctype="multipart/form-data">
			<fieldset>
			<h3>Login...</h3><br>
				<div class="input-prepend" title="Username" data-rel="tooltip">
					<span class="add-on"><i class="icon-user"></i></span>
					<input autofocus class="input-large field required" name="username" id="username" type="text" value="" value="<?php if(is_array($error->error_login_values)) {echo $error->error_login_values['username']; $error->error_login_values = '';}?>" maxlength="50" size="25" title="" alt="Username" tabindex="1" />
				</div>
				<span class="error_message"><?php
				if($error->error_login_empty_username != '') {
				echo $error->error_login_empty_username; 
				$error->error_login_empty_username = '';
				}
				?></span>
				<div class="clearfix"></div>
				

				<div class="input-prepend" title="Password" data-rel="tooltip">
					<span class="add-on"><i class="icon-lock"></i></span>
					<input class="input-large field required" name="password" id="password" type="password" value="" maxlength="16" size="25" title="" alt="Password" tabindex="2" />
				</div>
				<span class="error_message"><?php 
				if($error->error_login_empty_password != '') {
				echo $error->error_login_empty_password;
				$error->error_login_empty_password = '';
				}?></span>
				<div class="clearfix"></div>
				<label class="remember" for="remember"><a href="<?php echo $this->baseUrl('admin/index/forgotpassword');?>">Forgot Password?</a></label>
				
				<div class="clearfix"></div>

				<p class="center span5">				
				<input id="signup" name="signup" type="submit" class="btn btn-primary" value="Login" tabindex="3" title="" style="width:100px;" />
				</p>
			</fieldset>
		</form>
		
	</div><!--/span-->
</div><!--/row-->