
<div class="main_body">
<div class="left width-100">
	<div class="breadcrumbs">
		<span class="home-icon"></span>
		<a href="javascript:void(0)" class="home">Home</a>
		<span class="arrow"></span>
		<a href="javascript:void(0)" class="events">Photo Categories</a>
		<div class="clear"></div>
	</div>
	<div id="events_page">
		<div class="header_events">
			<h2>Photo Categories</h2>
			
			<div class="event_search" id="search_cat">
				<input type="text" placeholder="Photo Category" name="search_word" id="search_word"/>
				<input type="submit" value="go" onClick="search_category();"/>
			</div>
			<div style="float:right;">
				<a class="button-dark add right fancybox" href="javascript:void(0)" id="add_photocategory"><span><span>Add Category</span></span></a>
			</div> 
			<div class="clear"></div>
		</div>
		<div class="grid-view">
			
			
			<div class="clear"></div>
			
			
			<div class="videos_list" id="videos_list">
							<ul>
							<?php foreach($this->CategoriesList as $key =>$cat_list){ 
							//if($key)
							?>
								<li class="category_border">
									<div class="product_image" align="center">
										<a href="<?php echo $this->baseUrl('photos/list/cat_id/').$cat_list['album_id'];?>">
										<input type="hidden" name="cal_id" value="<?php echo $cat_list['album_id'];?>" />
										<?php 
										$file	=	$this->baseUrl('public/uploads/photo_category_images/'.$cat_list['album_image']);
										if($cat_list['album_image'] !=''){?>
										<img src="<?php echo $file;?>" width="135" height="135">
										<?php }else{ ?>
										<img width="135" height="135" src="<?php echo $this->baseUrl('public/uploads/photo_category_images/No_Image_Available.jpg');?>">
										<?php } ?>
										</a>
									</div>
									<div class="product_info category_title">
										<a href="javascript:void(0)"><?php echo ucwords(strtolower($cat_list['album_description']));?> </a>										
									</div>
								</li>
								<?php } ?>
							</ul>
							<div class="clear"></div>
						</div>
						
						<div style="height:10px;"></div>
								
			

		</div>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>
</div>
<div id="add_category_form" style="display:none;">
<div class="register-form containerbox">
		<p>Create you are own photo category</p>
		<div class="login-part">
			<form name="category_form" id="category_form" action="addcategory" method="POST" enctype="multipart/form-data">
			<div class="row"><label>Photo Category Name</label><input type="text" id="cat_name" name="cat_name" /></div>
			<div class="row"><label>Photo Category Image</label><input type="file" id="cat_image" name="cat_image"/></div>
			<div class="btn-container"><input type="submit" id="sbt_login" name="sbt_login" value="Add"></div>
			</form>
			<div id="login_loading" style="display:none;"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" /></div>
		</div>	
	</div>		
			
</div>