
<!-- edit video file -->
<div class="register-form containerbox">
		<p>Edit photo file</p>
		<?php //echo "<pre>";print_r($photo_data); echo "venu<br>"; print_r($editvideo);?>
		<div class="login-part">
			<form name="editv_form" id="editv_form" action="<?php echo $this->baseUrl('photos/updatephoto/file_id/'.$this->photo_data['file_id']);?>" method="POST" >
			<div class="row"><label>Photo Name</label><input type="text" id="photo_name" name="photo_name" value="<?php echo $this->photo_data['file_title'];?>" /></div>
			<div class="row"><label>Choose Photo :&nbsp;&nbsp;<img width="70" height="50" src="<?php echo 	$this->baseUrl('public/uploads/photo_images/'.$this->photo_data['file_path']);?>"></label>
			<input type="file" id="photo_file" name="photo_file" /></div>
			<div class="row"><label>Photo category</label>
			<select style="width:200px" name="photo_category">
			 <option value=""> Select Category</option>
			<?php if(isset($this->CategoriesList) && !empty($this->CategoriesList)) {
			?>
			
			<?php 	foreach($this->CategoriesList as $key =>$cat_list){
					$select	=	'';
					if($this->photo_data['album_id'] == $cat_list['album_id']){ $select	=	'selected';}
				echo "<option value='".$cat_list['album_id']."' ".$select." >".ucwords(strtolower($cat_list['album_description']))."</option>";
				} }?>
				</select></div>
			<div class="btn-container"><input type="submit" id="sbt_login" name="sbt_login" value="Update Video"></div>
			</form>
			<div id="login_loading" style="display:none;"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" /></div>
		</div>	
	</div>		

<!-- Add new video file -->