<div class="main_body">
<div class="left width-100">
	<div class="breadcrumbs">
		<span class="home-icon"></span>
		<a href="javascript:void(0)" class="home">Home</a>
		<span class="arrow"></span>
		<a href="javascript:void(0)" class="events">Video`s List</a>
		<div class="clear"></div>
	</div>
	<div id="events_page">
		<div class="header_events">
			<h2>Video`s</h2>			
			<div class="event_search">
				<input type="text" placeholder="Video Name"/>
				<input type="submit" value="go"/>
			</div>
			<div class="clear"></div>
		</div>
		<div class="grid-view">
			<div class="grid-view-heading left">
				<a href="javascript:void(0)" class="button-light icon delete"><span><span>Delete</span></span></a>					
				<a href="javascript:void(0)" class="button-light icon tags"><span><span>Tags</span></span></a>	
			</div>
			<div class="right">
			<select style="width:200px">
			 <option value=""> Select Category</option>
			<?php if(isset($this->CategoriesList) && !empty($this->CategoriesList)) {
			?>
			
			<?php 	foreach($this->CategoriesList as $key =>$cat_list){ 
				echo "<option value='".$cat_list['album_id']."'>".ucwords(strtolower($cat_list['album_description']))."</option>";
				} }?>
				</select>
			</div>
			<div class="clear"></div>
			<table cellpadding="0" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th width='30'><input type="checkbox"/></th>
						<th >Video Title</th>
						<th  width='100'>Video Category</th>
						<th  width='100'>Video</th>
						<th  width='100'>Date</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				if(isset($this->video_list) && !empty($this->video_list))
				{
				foreach($this->video_list as $videolist){
				?>
					<tr class="odd">
						<td><input type="checkbox"/></td>
						<td><?php echo ucwords(strtolower($videolist['file_title']));?></td>
						<td><?php echo $videolist['album_description'];?></td>
						<td><img src="<?php echo $this->baseUrl('public/uploads/video_category_images/'.$videolist['album_image']); ?>"/></td>
						<td><?php echo date('Y-M-d',strtotime('08/10/2013'));?></td>
					</tr>
					<?php } }else{ ?>
					<td colspan="5">Records not found !</td>
					<?php } ?>
									
				</tbody>
			</table>
			<div class="grid-view-footer">
					<a  href="javascript:void(0)" class="left button-light no-text icon refresh"><span><span>Refresh</span></span></a>
					<span class="right">View 1-10 of 20</span>
					<div class="pagention text-center">
						<a  href="javascript:void(0)" class="button-light icon First"><span><span>First</span></span></a>
						<a  href="javascript:void(0)" class="button-light icon prev"><span><span>Prev</span></span></a>
						<span class="info">Page 1 of 2</span>
						<a  href="javascript:void(0)" class="button-light icon next"><span><span>Next</span></span></a>
						<a  href="javascript:void(0)" class="button-light icon last"><span><span>last</span></span></a>
						<select>
							<option>1</option>
							<option>2</option>
						</select>
					</div>
					<div class="clear"></div>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>
</div>