
<ul>
<?php foreach($this->searchcategories as $key =>$cat_list){ 
//if($key)
?>
	<li class="category_border">
		<div class="product_image" align="center">
			<a href="<?php echo $this->baseUrl('photos/list/').$cat_list['album_id'];?>">
			<input type="hidden" name="cal_id" value="<?php echo $cat_list['album_id'];?>" />
			<?php 
			$file	=	$this->baseUrl('public/uploads/photo_category_images/'.$cat_list['album_image']);
			if($cat_list['album_image'] !=''){?>
			<img src="<?php echo $file;?>" width="135" height="135">
			<?php }else{ ?>
			<img width="135" height="135" src="<?php echo $this->baseUrl('public/uploads/photo_category_images/No_Image_Available.jpg');?>">
			<?php } ?>
			</a>
		</div>
		<div class="product_info category_title">
			<a href="javascript:void(0)"><?php echo ucwords(strtolower($cat_list['album_description']));?> </a>										
		</div>
	</li>
	<?php } ?>
</ul>
<div class="clear"></div>

								
			
