<div style="clear:both; height:2px;"></div>
<div class="widget">
    <div class="widget-block">
        <div class="widget-header">Today's Top Offers</div>
        <div class="widget-cont">
            
					<div class="imageoffer-border">
						<div class="imageoffer">
						<center><img src="<?php echo $this->baseUrl('public/default'); ?>/images/product1.jpg" /></center>
						</div>
						<div class="information-only">
							<h4>User Four</h4>
							<div style="height:5px;"></div>
							<span>Date:2012-11-01  Time:7:00</span>
							<hr style="height:5px; width:100px; color:#DDD;">
							<span style="font-size:12px; clear:both;"><s>Rs. 537</s></span>
							<span style="font-size:14px; clear:both;font-weight:bold;">50 % Off </span>
							<span style="font-size:14px; clear:both;font-weight:bold;">Rs. 537</span>
						</div>
						<div class="clear"></div>
					</div>
					
					
					<div class="imageoffer-border">
						<div class="imageoffer">
						<center><img src="<?php echo $this->baseUrl('public/default'); ?>/images/product2.jpg" /></center>
						</div>
						<div class="information-only">
							<h4>User Four</h4>
							<div style="height:5px;"></div>
							<span>Date:2012-11-01  Time:7:00</span>
							<hr style="height:5px; width:100px; color:#DDD;">
							<span style="font-size:12px; clear:both;"><s>Rs. 537</s></span>
							<span style="font-size:14px; clear:both;font-weight:bold;">50 % Off </span>
							<span style="font-size:14px; clear:both;font-weight:bold;">Rs. 537</span>
						</div>
						<div class="clear"></div>
					</div>
					
					
					<div class="imageoffer-border">
						<div class="imageoffer">
						<center><img src="<?php echo $this->baseUrl('public/default'); ?>/images/product1.jpg" /></center>
						</div>
						<div class="information-only">
							<h4>User Four</h4>
							<div style="height:5px;"></div>
							<span>Date:2012-11-01  Time:7:00</span>
							<hr style="height:5px; width:100px; color:#DDD;">
							<span style="font-size:12px; clear:both;"><s>Rs. 537</s></span>
							<span style="font-size:14px; clear:both;font-weight:bold;">50 % Off </span>
							<span style="font-size:14px; clear:both;font-weight:bold;">Rs. 537</span>
						</div>
						<div class="clear"></div>
					</div>
                
                    
            </ul>
        </div>
    </div>
</div>