<?php
$config=Zend_Registry::get('config');
$base_url = $config->site->baseurl;

$this->session = new Zend_Session_Namespace('MyClientPortal');
$isSignedIn = $this->session->isSignedIn;
$displayName = $this->session->name;
?>
<div class="header-top">
			<div class="wrapper">
				<div id="logo"><a href="<?php echo $base_url; ?>"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/Logo.png" title="GetLinc.com" alt="getLinc.com"/></a></div>
				
				
				<div id="links">
					<ul>
						<li><a href="<?php echo $this->baseUrl('getlinc/aboutus/');?>" class="subitems"/>About Us</a></li>
						<li><a href="<?php echo $this->baseUrl('getlinc/contactus/');?>" class="subitems"/>Contact Us</a></li>
						<?php if($isSignedIn==1){?>
						<li class="subitems">
							<a href="javascript:void(0)" class="subitems"/>My Account</a>
							<ul>
								<li><a href="<?php echo $this->baseUrl('profile/view/');?>" class="subitems"/>My&nbsp;Profile</a></li>
								<?php /*<li><a href="javascript:void(0)" class="subitems"/>Settings</a></li>
								<li><a href="javascript:void(0)" class="subitems"/>Privacy Options</a></li>*/?>
								<li><a href="<?php echo $this->baseUrl('signin/logout/');?>" class="subitems"/>Sign&nbsp;Out</a></li>
							</ul>
						</li>
						<?php }?>
					</ul>
				</div>
				
				
				
				
				
				
				
				
				
				
				
				
				
				
			
		
		
							<div class="header_bottom" style="margin-top:0px; width:115px; border:#ff0000 solid 0px; float:right">	
								<div class="right_cart">			
								<?php								
								if($isSignedIn!=1){
								?>
								<a alt="Your Account" class="" href="javascript:void(0)" id="signup">
								  <!--span class="top">Hello, <span class="height">Sign</span></span-->
								  <span class="label" style="padding-left:20px">Click Here For Signup</span>
								</a>								
								<?php }else{?>
								<a alt="Your Account" class="" href="javascript:void(0)" id="myaccount">
								  <span class="top">Hello, <span class="height"><?php echo $displayName;?></span></span>
								  <span class="label">Your Account</span>
								</a>
								<div id="myac-options" style="display:none;z-index:1000;">
									<ul >
										<li class="top_arrow"></li>
										<li><a href="<?php echo $this->baseUrl('profile/view/');?>">My profile</a></li>
										<li><a href="javascript:void(0)">Settings</a></li>
										<li><a href="javascript:void(0)">Privacy&nbsp;Options</a></li>
										<li><a href="<?php echo $this->baseUrl('signin/logout/');?>">Sign Out</a></li>
									</ul>
								</div>
								
								<?php }?>			
								<div class="clear"></div> 
							</div>
							<div class="clear"></div>
							</div>
		
		
		
		
		
		
		
		
		
				<?php
				if($isSignedIn!=1){
				?>
				<div id="login-header">
					<form method="post" name="login_header" id="login_header">	
					<ul>
						<li><input type="text" name="email_id" id="email_id" class="" /><span>New Customer? <a href="javascript:void(0)" id="signup">Start Here</a></span></li>
						<li><input type="password" name="password" id="password" class="" /><span><a href="javascript:void(0)" >Forgot Password ?</a></span></li>
						<li class="button"><input type="submit" value="login" /></li>
					</ul>
                    </form>
					<div class="clear"></div>
				</div>
				<?php }else{?>


			
				<div id="profile">
					<?php /*<h5 class="prifile_image_label"><?php echo $displayName;?></h5>
					<div class="cont_an"><a href="<?php echo $this->baseUrl('wall/');?>" class="button" id="show_all">Show Wall</a></div> */?>
					<div class="cont_an"><a href="javascript:void(0)" class="button arrow arw-lef" id="share"><span class="plus"></span>Share<span class="arrow"></span></a></div>
					<div class="profile_image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png" title="profil name" alt="profil_name" /></div>				
					<!--span class="small_arrow"></span-->
				
							
				
				
				
				</div>
				<!-- dialog Content -->
				<div id="share-content" style="display:none">
					<textarea></textarea>
					<input type="button" value="share"/>
				</div>
				<?php }?>
				<div class="clear"></div>
			</div>
		</div>