<div class="left-sidebar">
	<div class="category-widget">
		<div class="cat-header opened">My Profile</div>
		<div class="cat-cont">
			<ul class="profilemenu">
				<li class="new-feed"><a href="javascript:void(0)"><span></span>New Feeds</a></li>
				<li class="message"><a href="javascript:void(0)"><span></span>Messages</a></li>
				<li class="find-friends"><a href="javascript:void(0)"><span></span>Find Friends</a></li>
				<li class="events"><a href="<?php echo $this->baseUrl('events/list/');?>"><span></span>Events List</a></li>
				<li class="events"><a href="<?php echo $this->baseUrl('events/add/');?>"><span></span>Events Add</a></li>
				<li class="events"><a href="<?php echo $this->baseUrl('events/view/');?>"><span></span>Events View</a></li>
				<li class="photos"><a href="javascript:void(0)"><span></span>Photos</a></li>
				<li class="groups"><a href="javascript:void(0)"><span></span>Groups</a></li>
				<li class="videos"><a href="javascript:void(0)"><span></span>Videos</a></li>
				<li class="file-sharing"><a href="javascript:void(0)"><span></span>File Sharing</a></li>
				<li class="my-blog"><a href="javascript:void(0)"><span></span>My Blog</a></li>
				<li class="polls"><a href="javascript:void(0)"><span></span>Polls</a></li>
				<li class="jobs"><a href="javascript:void(0)"><span></span>Jobs</a></li>
				<li class="store"><a href="javascript:void(0)"><span></span>Store</a></li>
			</ul>
		</div>
	</div>
					
</div>