<div class="widget">
    <div class="widget-block">
        <div class="widget-header">Even Notifications</div>
        <div class="widget-cont">
            <ul class="thumbnail">
                <li>
                    <div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></div>
                    <div class="information-only">
                        <h6>User Four</h6>
                        <span>Date:2012-11-01  Time:7:00</span>
                    </div>
                    <div class="clear"></div>
                </li>
                <li>
                    <div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></div>
                    <div class="information-only">
                        <h6>User Four</h6>
                        <span>Date:2012-11-01  Time:7:00</span>
                    </div>
                    <div class="clear"></div>
                </li>
                <li>
                    <div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></div>
                    <div class="information-only">
                        <h6>User Four</h6>
                        <span>Date:2012-11-01  Time:7:00</span>
                    </div>
                    <div class="clear"></div>
                </li>
            </ul>
        </div>
    </div>
</div>