<div id="chat-widget" class="widget">
    <div class="widget-block">
        <div class="widget-header">
            <div class="profile-information">
                <span class="chat-status invisible"></span>
                <span class="chat-name">Profile Name</span>
                <span class="change-status"></span>
                <div class="clear"></div>
            </div>
            <div class="search-chat">
                <span></span>
                <input type="text" />
            </div>
            
        </div>
        <div class="widget-cont">
            <div class="change_current_status">
                <div>You are Invisible.</div>
                <a href="javascript:void(0)" >Go Visible</a>
            </div>
            <ul class="thumbnail">
                <li>
                    <div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></div>
                    <h3><span class="chat-status invisible"></span>User Four</h3>
                    <div class="clear"></div>
                </li>
                <li>
                    <div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></div>
                    <h3><span class="chat-status visible"></span>User Four</h3>
                    <div class="clear"></div>
                </li>
                <li>
                    <div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></div>
                    <h3><span class="chat-status busy"></span>User Four</h3>
                    <div class="clear"></div>
                </li>
                <li>
                    <div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></div>
                    <h3><span class="chat-status ideal"></span>User Four</h3>
                    <div class="clear"></div>
                </li>
                <li>
                    <div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></div>
                    <h3><span class="chat-status video"></span>User Four</h3>
                    <div class="clear"></div>
                </li>
                <li>
                    <div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></div>
                    <h3><span class="chat-status video-busy"></span>User Four</h3>
                    <div class="clear"></div>
                </li>
                <li>
                    <div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></div>
                    <h3><span class="chat-status video-ideal"></span>User Four</h3>
                    <div class="clear"></div>
                </li>
            </ul>
        </div>
    </div>
</div>