<div class="category-widget">
    <div class="cat-header opened">All Categories</div>
    <div class="cat-cont">
        <ul>
            <li>
                <a href="javascript:void(0)">Cloths<span> >> </span></a>
                <ul class="subitem">
                    <li><a href="javascript:void(0)">Jeans</a></li>
                    <li><a href="javascript:void(0)">Tea</a></li>
                    <li><a href="javascript:void(0)">Mens</a></li>
                </ul>
            </li>
            <li><a href="javascript:void(0)">Mobiles & Accessories</a></li>
            <li><a href="javascript:void(0)">Foot wear</a></li>
            <li>
                <a href="javascript:void(0)">Mobiles <span>>></span></a>
                <ul class="subitem">
                    <li><a href="javascript:void(0)">Nokia</a></li>
                    <li><a href="javascript:void(0)">Samsung</a></li>
                    <li><a href="javascript:void(0)">Micromax</a></li>
                    <li><a href="javascript:void(0)">Sony</a></li>
                </ul>
            </li>
            <li><a href="javascript:void(0)">books</a></li>
            <li><a href="javascript:void(0)">Computer</a></li>
            <li><a href="javascript:void(0)">Gaming</a></li>
            <li><a href="javascript:void(0)">Baby Care & Toys</a></li>
            <li><a href="javascript:void(0)">Cloths</a></li>
            <li><a href="javascript:void(0)">Cloths</a></li>
            
        </ul>
    </div>
</div>