<?php
	$error = $this;
?>
<div class="main_body">
	<div class="left width-100">
		<div class="breadcrumbs">
			<span class="home-icon"></span>
			<a href="javascript:void(0)" class="home">Home</a>
			<span class="arrow"></span>
			<a href="javascript:void(0)" class="events">Internal Messaging</a>
			<div class="clear"></div>
		</div>
		<div id="events_page">
			<div class="header_events">
				<h2>Compose Message</h2>
				
				
				<a id="save-event" href="javascript:void(0)" class="button-grey add right"><span><span>Cancel</span></span></a>
				<div class="btn-container add right"><input type="submit" id="reg_submit" name="reg_submit" value="Send"></div>
				<div class="clear"></div>
			</div>
			<div class="event-form">
				<form>
					<div class="heading">
						<h3>New Message</h3><span class="required">Required Information</span>
						<div class="clear"></div>
					</div>
					
					<div class="row">
						<label>From :</label>
						<input type="text"/>
						<div class="clear"></div>
					</div>
					<div class="row">
						<label>Invitees :</label>
						<input type="text" name="mail_to" id="mail_to" value="<?php if(is_array($error->error_createuser_values)) {echo $error->error_createuser_values['mailto'];} ?>" <?php if($error->error_createuser_mailto != '') { echo 'class="error"'; } ?>/>
						<span class="info">(please enter email ids)</span>
						<div class="clear"></div>
					</div>
					<div class="row">
						<label>Subject :</label>
						<input type="text"/>
						<div class="clear"></div>
					</div>
					
					<div class="row">
						<label>Message :</label>
						<textarea rows="6"></textarea>
						<div class="clear"></div>
					</div>
					<div class="clear"></div>
					
					<div class="clear"></div>
					
					<div class="heading">
						<h3>Attachments</h3>
						<div class="clear"></div>
					</div>
					<div class="row left width-50 half">
						<label>Event Logo :</label>
						<input type="file"/>
						<span class="info">(Should upload less than 2MB)</span>
						<div class="clear"></div>
					</div>
					<div class="clear">
						<a id="save-event" href="javascript:void(0)" class="button-grey add right"><span><span>Cancel</span></span></a>
						<input type="submit" id="reg_submit" name="reg_submit" value="Register">
						
					</div>
				</form>
				<div class="clear">&nbsp;</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
<div class="clear"></div>
</div>