<?php
$config=Zend_Registry::get('config');
?>
<div id="footer-links">
		<div class="wrapper">
			<div class="block" id="newsletter">
				<h5>Newsletter Signup</h5>
				<div class="container">
					<p>Sign up to receive special offers and the latest style news.</p>
					<form>
						<input type="text" value="Your e-mail address" />
						<div class="clear">
							<input type="submit" value="Subscribe" />
							<!--input type="submit" value="For Women" /-->
						</div>
					</form>					
				</div>
			</div>
			<div class="blocks">
				<div class="block">
					<h5>Service</h5>
					<ul>
						<li><a href="javascript:void(0)" class="subitems"/>About</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Contact</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Terms and Conditions</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Privacy Policy</a></li>						
					</ul>
				</div>
				<div class="block">
					<h5>Our Policies</h5>
					<ul>
						<li><a href="javascript:void(0)" class="subitems"/>Cancellations and Returns</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Shipping</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Payments</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Ordering and Tracking</a></li>
					</ul>
				</div>
				<div class="block">
					<h5>Join us on</h5>
					<ul>
						<li><a href="javascript:void(0)" class="subitems"/>Facebook</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Twitter</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Google</a></li>
					</ul>
				</div>
				<div class="block">
					<h5>Payment Methods</h5>
					<div class="payment-methods"></div>
					<?php /*<h5>Shipping Partner</h5>
					<div class="shipping-methods"></div>*/?>
				</div>
				<div class="clear"></div>
			</div>
			
		</div>
	</div>
	<div id="footer">
		<div class="wrapper">
			<a href="javacript:void(0)">Conditions of Use</a>
			<a href="javacript:void(0)">Privacy Notice</a>
			<a href="javacript:void(0)">Interest-Based Ads</a>
			<span>&copy; 1996-2013 GetLinc.com, Inc.</span>
		</div>
	</div>

<?php if($config->show->profiler==1){ ?>	
<br>	
<center><h1>Profiler</h1></center>
<?php
$db_profiler=Zend_Registry::get('db'); 
$profiler = $db_profiler->getProfiler()->setEnabled(true);
//$query123 = $profiler->getQueryProfiles();

$totalTime    = $profiler->getTotalElapsedSecs();
$queryCount   = $profiler->getTotalNumQueries();
$longestTime  = 0;
$longestQuery = null;

foreach ($profiler->getQueryProfiles() as $query) {
	if ($query->getElapsedSecs() > $longestTime) {
	$longestTime  = $query->getElapsedSecs();
	$longestQuery = $query->getQuery();	
	}
	?>
	<div style="border:#CCC solid 1px; margin:auto; width:80%; padding:10px; font-size:12px; line-height:25px;">
	<span style="color:#FF0000;"><b>Query : </b></span><?php echo $query->getQuery();?><br>
	<span style="color:#FF0000;"><b>Query Time : </b></span><?php echo $query->getElapsedSecs();?><br>
	</div>
	<br>
	<?php	
}
?>
<div style="border:#CCC solid 1px; margin:auto; width:80%; padding:10px;">
<?php
echo 'Executed ' . $queryCount . ' queries in ' . $totalTime .' seconds' . "\n<br><br>";
echo 'Average query length: ' . $totalTime / $queryCount .' seconds' . "\n<br><br>";
echo 'Queries per second: ' . $queryCount / $totalTime . "\n<br><br>";
echo 'Longest query length: ' . $longestTime . "\n<br><br>";
echo "Longest query: \n" . $longestQuery . "\n<br><br>";
?>
</div>
<br>
<?php }?>