<div id="slider">
	<img id="img1" class="show" style="width: 100%; display:block; " src="<?php echo $this->baseUrl('public/default'); ?>/images/slider.png" height="200" />
	<img id="img2" style="width: 100%; display:none; " src="<?php echo $this->baseUrl('public/default'); ?>/images/slider1.png" height="200" />
	<img id="img3" style="width: 100%; display:none; " src="<?php echo $this->baseUrl('public/default'); ?>/images/slider2.png" height="200" />
	<img id="img4" style="width: 100%; display:none; " src="<?php echo $this->baseUrl('public/default'); ?>/images/slider3.png" height="200" />
	<ul>
		<li class="list active" rel="#img1">Great Combos</li>
		<li class="list" rel="#img2">Great Combos</li>
		<li class="list" rel="#img3">Great Combos</li>
		<li class="list" rel="#img4">Great Combos</li>
	</ul>
	<div class="clear"></div>
</div>
	