<div class="main_body">
<div class="left width-100">
	<?php echo $this->action('homebanner', 'index', 'default', array('a_parameter'=>'a_value'));?>
	
	<?php //print_r($this->ProductsList);?>

	
	<?php
	$i=1; 
	$special_array   = array(" ",".",";","|","/",",","'","[","]","{","}","--",":","~","`","!","@","#","$","%","^","&","*","(",")","+","?");
	$replace = '-';
	foreach($this->ProductsList as $each_ProductsList){
	if($i%4==1){
	?>
	<div class="product_list">		
		<ul>
		<?php }?>
			<li class="product_id_class" id="product_id_<?php echo $each_ProductsList['product_id'];?>">
				<div class="product_image">
					<a href="<?php echo $this->baseUrl('products/view/id')."/".$each_ProductsList['product_id']."/".str_replace($special_array, $replace,$each_ProductsList['product_title']);?>">					
					<?php if($each_ProductsList['product_image']!=''){?>
					<img src="<?php echo $this->baseUrl('public/uploads/product_images')."/".$each_ProductsList['product_image']; ?>" width="135" height="135">
					<?php }else{?>
					<img src="<?php echo $this->baseUrl('public/uploads/product_images/No_Image_Available.JPG'); ?>" width="135" height="135">
					<?php }?>
					</a></a>
				</div>
				<div class="product_info" style="text-align:center;">
					<a href="javascript:void(0)"><?php echo $each_ProductsList['product_title'];?></a>
					<span class="rating rating-1"></span>
					<div class="price">
						<?php if($each_ProductsList['product_discount_details']!='0'){?>
						<span class="old">Rs.<?php echo $each_ProductsList['product_price'];?></span>
						<span class="new">Rs.<?php echo $each_ProductsList['product_price_details'];?></span>
						<?php }else{?>
						<span class="new">Rs.<?php echo $each_ProductsList['product_price_details'];?></span>
						<?php }?>
					</div>
				</div>
			</li>
			<?php 
			if($i%4==0){
			?>
		</ul>
		
	</div>
	
	<div class="product_list">
	<h4>&nbsp;</h4>
	</div><br>
	<h4></h4>
	<?php }$i++; }?>
	
	
	
	
	
	
	


</div>
<div class="clear" style="height:10px;"></div>
</div>