<div class="main_body">
<div class="left width-100">
	<div id="slider">
		<img id="img1" class="show" style="width: 100%; display:block; " src="<?php echo $this->baseUrl('public/default'); ?>/images/slider.png" />
		<img id="img2" style="width: 100%; display:none; " src="<?php echo $this->baseUrl('public/default'); ?>/images/slider1.png" />
		<img id="img3" style="width: 100%; display:none; " src="<?php echo $this->baseUrl('public/default'); ?>/images/slider2.png" />
		<img id="img4" style="width: 100%; display:none; " src="<?php echo $this->baseUrl('public/default'); ?>/images/slider3.png" />
		<ul>
			<li class="list active" rel="#img1">Great Combos</li>
			<li class="list" rel="#img2">Great Combos</li>
			<li class="list" rel="#img3">Great Combos</li>
			<li class="list" rel="#img4">Great Combos</li>
		</ul>
		<div class="clear"></div>
	</div>
	<div class="product_list">
		<h4>Digital Cameras Best Sellers</h4>
		<ul>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camtwo.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camone.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camtwo.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camone.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
		</ul>
		<div class="clear"></div>
	</div>
	<div class="product_list">
		<h4>Digital Cameras Best Sellers</h4>
		<ul>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camtwo.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camone.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camtwo.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camone.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
		</ul>
		<div class="clear"></div>
	</div>
</div>
<div class="clear"></div>
</div>