<?php 

	$session = new Zend_Session_Namespace('MyPortal');
	//$error = new Zend_Session_Namespace('MyPortalerror');
?>
<div class="content-wrapper"><!--BO content-wrapper -->
    <div class="form-wrapper"><!--BO form-wrapper -->
<center><img alt="ACCESS DENIED" src="<?php echo $this->baseUrl('public/images/ad.gif');?>"></center>
<br/>
<br/>
<br/>
<center>
Please contact administrator for further reference<br/>
Click here
<?php if(isset($session->loggedIn) || $session->loggedIn ==1) { ?>
<a href="<?php echo $_SERVER['HTTP_REFERER'];?>"><img alt="Home" src="<?php echo $this->baseUrl('public/images/th.jpg');?>" width="30" height="30" border="0"/>
</a>
<?php } else {?>
<a href="<?php //str_replace($_SERVER['REQUEST_URI'], '', $_SERVER['HTTP_REFERER']);?>"><img alt="Home" src="<?php echo $this->baseUrl('public/images/th.jpg');?>" width="30" height="30" border="0"/>
</a>
<?php }?>

to go to Home Page
</center>
</div>
</div>


<div style="font-sze:12px; width:700px; margin:auto; margin-bottom:50px;">
<?php
$config=Zend_Registry::get('config');
if($config->show->filepath==1){ 
echo "<br>path: ".dirname(__FILE__);
$fc = Zend_Controller_Front::getInstance()->getRequest();
echo "<br>module: ".$module = $fc->getModuleName();
echo "<br>controller: ".$controller = $fc->getControllerName();
echo "<br>action: ".$action = $fc->getActionName();
echo "<br>layout: ";
}
?>
</div>