<?php
$this->session = new Zend_Session_Namespace('MyClientPortal');
$isSignedIn = $this->session->isSignedIn;
if($isSignedIn==1){
?>
<div class="left-sidebar">
	<div class="category-widget">
		<div class="cat-header opened">My Account</div>
		
		
		<?php echo $this->action('profileimage', 'wallmenu', 'default', array('a_parameter'=>'a_value'));?>

		<div class="cat-cont">
			<ul class="profilemenu">
				<li class="new-feed"><a href="<?php echo $this->baseUrl('wall/');?>"><span></span>New Feeds</a></li>
				<li class="message"><a href="<?php echo $this->baseUrl('messaging/inbox/');?>"><span></span>Messages</a></li>
				<li class="message"><a href="<?php echo $this->baseUrl('events/calendar/');?>"><span></span>Event Calendar</a></li>
				
				
				<li class="photos"><a href="<?php echo $this->baseUrl('videos/categories');?>"><span></span>Photos</a></li>				
				<li class="videos"><a href="<?php echo $this->baseUrl('videos/categories');?>"><span></span>Videos</a></li>
				<li class="file-sharing"><a href="<?php echo $this->baseUrl('videos/categories');?>"><span></span>File Sharing</a></li>
				
				
				<li class="groups"><a href="javascript:void(0)"><span></span>Groups</a></li>
				<li class="find-friends"><a href="javascript:void(0)"><span></span>Find Friends</a></li>
				
				
				<li class="my-blog"><a href="javascript:void(0)"><span></span>My Blog</a></li>
				<li class="polls"><a href="javascript:void(0)"><span></span>Polls</a></li>
				<li class="jobs"><a href="javascript:void(0)"><span></span>Jobs</a></li>
				
				
				<li class="events"><a href="<?php echo $this->baseUrl('demo/list/');?>"><span></span>Demo List</a></li>
				<li class="events"><a href="<?php echo $this->baseUrl('demo/add/');?>"><span></span>Demo Add</a></li>
				<li class="events"><a href="<?php echo $this->baseUrl('demo/view/');?>"><span></span>Demo View</a></li>
			</ul>
		</div>
	</div>
					
</div>
<div class="clear" style="height:5px;"></div>
<?php }?>