<?php 
$session = new Zend_Session_Namespace('MyPortal');
$errorsession=new Zend_Session_Namespace("addmerchant");
$error = $this;

$products_count = $this->products_count;
$products_list = $this->products_list;

$merchantlist = $this->merchantlist;
foreach($merchantlist as $each_merchant){
	$merchant_array[$each_merchant['merchant_id']] = $each_merchant['merchant_title'];
}

$cn=$this->iColumnName;
$do=$this->iDisplayOrder;
if($cn==""){$cn=1;}
if($do==""){$do='DESC';}
$cn='';
?>

		<?php 
      		if($error->error != '') {?>      			
      			<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $error->error;?>
				</div>
      		<?php }else if($session->validateerror != '') {?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $session->validateerror;?>
				</div>
      		<?php $session->validateerror='';      			
      		} else if($session->success != '') {?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $session->success;?>
				</div>
      		<?php $session->success = '';
      		} else if($errorsession->success != '') {?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $errorsession->success;?>
				</div>
			<?php
      			$errorsession->success = '';
      		}
			?>
		
		

		
			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Product's</h2>
						<a href="<?php echo $this->baseUrl('admin/products/register');?>"><button class="btn btn-small" style="float:right;">Add New Product</button></a>					
					</div>
					<div class="box-content">
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>Slno.</th>
								  <th>GetLinc ID</th>
								  <th>SKU</th>
								  <th>Title</th>
								  <th>Merchant</th>
								  <th>Status</th>								  
								  <th>Actions</th>								  
							  </tr>
						  </thead>   
						  <tbody>
						  <?php 
							$i=1;
							foreach($products_list as $each_product){?>							
							<tr>
								<td><?php echo $i;$i++;?></td>
								<td>
								<?php 
								echo "<h3>GL".$each_product['product_id'],"</h3>";
								?>
								</td>
								<td>
								<?php 
								echo $each_product['product_sku'];
								?>
								</td>								
								<td align="center" width="350">									
									<?php  echo $each_product['product_title']; ?>
								</td>
								<td align="center" width="150">									
									<?php  if($each_product['merchant_id']!=0){echo $merchant_array[$each_product['merchant_id']];}?>
								</td>
								<td class="center" width="100">
								
									<?php if($each_product['statusid']=="1") {?>
									<a href="<?php echo $this->baseUrl('admin/products/lock/productId/') . $each_product['product_id'];?>" onClick="return confirm('Do you want to continue?')">
									<span class="label label-success">Active</span>
									</a>
									<?php }?>
									<?php if($each_product['statusid']=="6") {?>
									<a href="<?php echo $this->baseUrl('admin/products/unlock/productId/') . $each_product['product_id'];?>" onClick="return confirm('Do you want to continue?')">
									<span class="label">Inactive</span>
									</a>							   
									<?php } ?>								
									
								</td>								
								<td class="center">							
									
									
									<a class="btn btn-info" href="<?php echo $this->baseUrl('admin/products/edit/productId/') . $each_product['product_id'];?>">
										<i class="icon-edit icon-white"></i>  
										Edit                                            
									</a>
									<a class="btn btn-danger" href="<?php echo $this->baseUrl('admin/products/delete/productId/') . $each_product['product_id'];?>" onclick="javascript:return confirm('Are you sure, do you want to continue?');">
										<i class="icon-trash icon-white"></i> 
										Delete
									</a>
									
									
								</td>
							</tr>
							<?php }?>
							
							
						  </tbody>
					  </table>            
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
			<!--/row-->
			<!--/row-->
			<!--/row-->
    
			  
				
<script type="text/javascript">
  $(document).ready(function() {
	  $(".error").fadeOut(6000);
});
</script>

		
