<?php 
	$usertyperoles = $this->usertyperoles;
	$session = new Zend_Session_Namespace('MyPortal');
	//$error = new Zend_Session_Namespace('MyPortalerror');
	$error = $this;
	
?>


<?php if($error->error != '') {?>
<div class="alert alert-error">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<strong>Error! </strong> <?php echo $error->error;?>
</div>
<?php $error->error = '';}?>


<div class="row-fluid sortable">
	<div class="box span12">
		<div class="box-header well" data-original-title>
			<h2><i class="icon-edit"></i>Product's</h2>			
		</div>
		<div class="box-content">			
			<form class="form-horizontal" id="signupform" autocomplete="off" method="post" action="">			
			  <fieldset>
				<legend>Register Product</legend>				
				
				<div class="control-group">
				  <label class="control-label" for="typeahead">Product Title<span class="req">*</span></label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">
					<input class="field" tabindex="1" id="product_title" name="product_title" type="text" value="<?php if(is_array($error->error_createproduct_values)) {echo $error->error_createproduct_values['product_title'];}?>" maxlength="20" size="40" title=""/>
					</div>
					<div class="error_message">
					   <?php 
						if($error->error_create_product_title != '') {
							echo '<label class="error">' .$error->error_create_product_title . '</label>';
							$error->error_create_product_title = '';
						}
					   ?>
					   </div>
					   
				  </div>
				</div>
				
				
				
				<div class="control-group">
				  <label class="control-label" for="typeahead">Product SKU</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">
					<input class="field" tabindex="1" id="product_sku" name="product_sku" type="text" value="<?php if(is_array($error->error_createproduct_values)) {echo $error->error_createproduct_values['product_sku'];}?>" maxlength="20" size="40" title=""/>
					</div>
					<div class="error_message">
					   <?php 
						if($error->error_create_product_sku != '') {
							echo '<label class="error">' .$error->error_create_product_sku . '</label>';
							$error->error_create_product_sku = '';
						}
					   ?>
					   </div>
					   
				  </div>
				</div>
				
				
				
				
				
				<div class="control-group">
				  <label class="control-label" for="typeahead">Product Merchant</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">
					
					<select id="merchant_id" name="merchant_id">
						<option value="">-Select Merchant-</option>
						<?php foreach($this->merchantlist as $each_merchantlist){						
						if(is_array($error->error_createproduct_values) && $error->error_createproduct_values['merchant_id'] == $each_merchantlist['merchant_id']) {
						$select = ' selected="selected"';
						} else {
						$select = '';
						}
						?>
						<option value="<?php echo $each_merchantlist['merchant_id'];?>" <?php echo $select; ?> ><?php echo $each_merchantlist['merchant_title'];?></option>
						<?php }?>
					</select>
					
					</div>
					<div class="error_message">
					   <?php 
						if($error->error_create_merchant_id!= '') {
							echo '<label class="error">' .$error->error_create_merchant_id . '</label>';
							$error->error_create_merchant_id = '';
						}
					   ?>
					   </div>
					   
				  </div>
				</div>
				
				
				
				
				
				
				<div class="control-group">
				  <label class="control-label" for="typeahead">Meta Title</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">
					<input class="field" tabindex="1" id="product_meta_title" name="product_meta_title" type="text" value="<?php if(is_array($error->error_createproduct_values)) {echo $error->error_createproduct_values['product_meta_title'];}?>" maxlength="20" size="40" title=""/>
					</div>
					<div class="error_message">
					   <?php 
						if($error->error_create_product_meta_title != '') {
							echo '<label class="error">' .$error->error_create_product_meta_title . '</label>';
							$error->error_create_product_meta_title = '';
						}
					   ?>
					   </div>
					   
				  </div>
				</div>
				
				
				<div class="control-group">
				  <label class="control-label" for="typeahead">Meta Description</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">					
					<textarea class="field" id="product_meta_description" name="product_meta_description" rows="5" cols="80"><?php if(is_array($error->error_createproduct_values)) {echo $error->error_createproduct_values['product_meta_description'];}?></textarea>
					</div>
					<div class="error_message">
					   <?php 
						if($error->error_create_product_meta_description!= '') {
							echo '<label class="error">' .$error->error_create_product_meta_description . '</label>';
							$error->error_create_product_meta_description = '';
						}
					   ?>
					   </div>
					   
				  </div>
				</div>
				
				
				
				<div class="control-group">
				  <label class="control-label" for="typeahead">Product Small Description</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">					
					<textarea class="field" id="product_small_description" name="product_small_description" rows="5" cols="80"></textarea>
					</div>
					<div class="error_message">
					   <?php 
						if($error->error_create_product_small_description != '') {
							echo '<label class="error">' .$error->error_create_product_small_description . '</label>';
							$error->error_create_product_small_description = '';
						}
					   ?>
					   </div>
					   
				  </div>
				</div>
				
				
				<div class="control-group">
				  <label class="control-label" for="typeahead">Product Large Description</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">					
					<textarea class="cleditor" id="product_description" name="product_description" rows="3"></textarea>
					</div>
					<div class="error_message">
					   <?php 
						if($error->error_create_product_description != '') {
							echo '<label class="error">' .$error->error_create_product_description . '</label>';
							$error->error_create_product_description = '';
						}
					   ?>
					   </div>
					   
				  </div>
				</div>
				
				
				
				
				
				
				<div class="control-group">
				  <label class="control-label" for="typeahead">Attribute Groups</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">
					
					<select id="attributes_group_id" name="attributes_group_id">
						<option value="">-Select Attribute Groups-</option>
						<?php foreach($this->attributegroupslist as $each_attributegroup){						
						if(is_array($error->error_createproduct_values) && $error->error_createproduct_values['attributes_group_id'] == $each_attributegroup['attributes_group_id']) {
						$select = ' selected="selected"';
						} else {
						$select = '';
						}
						?>
						<option value="<?php echo $each_attributegroup['attributes_group_id'];?>" <?php echo $select; ?> ><?php echo $each_attributegroup['attributes_group_title'];?></option>
						<?php }?>
					</select>
					
					</div>
					<div class="error_message">
					   <?php 
						if($error->error_create_attributes_group_id!= '') {
							echo '<label class="error">' .$error->error_create_attributes_group_id . '</label>';
							$error->error_create_attributes_group_id = '';
						}
					   ?>
					   </div>
					   
				  </div>
				</div>
				
				<script type="text/javascript">
				function checkAttributeGroup(){
					if($("#attributes_group_id").val()==''){
						return confirm("Attribute Group not selected, Do you want to continue?");
					}else{
						var AttributeGroupTitle = $("#attributes_group_id :selected").text();
						return confirm("You are selected Attribute Group : "+AttributeGroupTitle+", Do you want to continue?");					
					}
				}				
				</script>
				
				
				
				
				<div class="form-actions">			  
				  <input id="signupsubmit" name="signup" type="submit"  class="btn btn-primary" value="Save" tabindex="7" title="" onclick="javascript:return checkAttributeGroup();" />
				</div>
			  </fieldset>
			</form>   

		</div>
	</div><!--/span-->

</div>
