<div class="main_body">
<div class="left width-100">
	<div class="breadcrumbs">
		<span class="home-icon"></span>
		<a href="javascript:void(0)" class="home">Home</a>
		<span class="arrow"></span>
		<a href="javascript:void(0)" class="events">Video Categories</a>
		<div class="clear"></div>
	</div>
	<div id="events_page">
		<div class="header_events">
			<h2>Video Categories</h2>
			
			<div class="event_search">
				<input type="text" placeholder="Video Category"/>
				<input type="submit" value="go"/>
			</div>
			<div style="float:right;">
				<a class="button-dark add right fancybox" href="javascript:void(0)" id="add_category"><span><span>Add Category</span></span></a>
			</div> 
			<div class="clear"></div>
		</div>
		<div class="grid-view">
			
			
			<div class="clear"></div>
			
			
			<div class="videos_list">
							<ul>
							<?php foreach($this->CategoriesList as $key =>$cat_list){ 
							//if($key)
							?>
								<li class="category_border">
									<div class="product_image">
										<a href="<?php echo $this->baseUrl('videos/list/').$cat_list['album_id'];?>">
										<input type="hidden" name="cal_id" value="<?php echo $cat_list['album_id'];?>" />
										<img src="<?php echo $this->baseUrl('public/default/images/album_category/').$cat_list['album_image'];?>"></a>
									</div>
									<div class="product_info category_title">
										<a href="javascript:void(0)"><?php echo $cat_list['album_description'];?> </a>										
									</div>
								</li>
								<?php } ?>
							</ul>
							<div class="clear"></div>
						</div>
						
						<div style="height:10px;"></div>
								
			

		</div>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>
</div>
<div id="add_category" style="display:none;">

				<label>Email Id<span class="error_class">*</span></label>
				<input type="text" name="email_id" id="email_id"/>				
			
</div>