<div class="main_body">
<div class="left width-100">
	<div class="breadcrumbs">
		<span class="home-icon"></span>
		<a href="javascript:void(0)" class="home">Home</a>
		<span class="arrow"></span>
		<a href="javascript:void(0)" class="events">Video Categories</a>
		<div class="clear"></div>
	</div>
	<div id="events_page">
		<div class="header_events">
			<h2>Video Categories</h2>
			
			<div class="event_search">
				<input type="text" placeholder="Video Category"/>
				<input type="submit" value="go"/>
			</div>
			<div class="clear"></div>
		</div>
		<div class="grid-view">
			
			
			<div class="clear"></div>
			
			
			<div class="videos_list">
							
							<ul>
								<li class="category_border">
									<div class="product_image">
										<a href="<?php echo $this->baseUrl('videos/list/');?>">
										<img src="<?php echo $this->baseUrl('public/default/images/camtwo.jpg');?>"></a>
									</div>
									<div class="product_info category_title">
										<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP...vvvvvvvv </a>										
									</div>
								</li>
								<li class="category_border">
									<div class="product_image">
										<a href="<?php echo $this->baseUrl('videos/list/');?>"><img src="<?php echo $this->baseUrl('public/default/images/camtwo.jpg');?>"></a></a>
									</div>
									<div class="product_info category_title">
										<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>										
									</div>
								</li>
								<li class="category_border">
									<div class="product_image">
										<a href="<?php echo $this->baseUrl('videos/list/');?>"><img src="<?php echo $this->baseUrl('public/default/images/camtwo.jpg');?>"></a></a>
									</div>
									<div class="product_info category_title">
										<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>										
									</div>
								</li>
								<li class="category_border">
									<div class="product_image">
										<a href="<?php echo $this->baseUrl('videos/list/');?>"><img src="<?php echo $this->baseUrl('public/default/images/camtwo.jpg');?>"></a></a>
									</div>
									<div class="product_info category_title">
										<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>										
									</div>
								</li>
							</ul>
							<div class="clear"></div>
						</div>
						
						<div style="height:10px;"></div>
						
						<div class="videos_list">
							
							<ul>
								<li class="category_border">
									<div class="product_image">
										<a href="<?php echo $this->baseUrl('videos/list/');?>">
										<img src="<?php echo $this->baseUrl('public/default/images/camtwo.jpg');?>"></a>
									</div>
									<div class="product_info category_title">
										<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP...vvvvvvvv </a>										
									</div>
								</li>
								<li class="category_border">
									<div class="product_image">
										<a href="<?php echo $this->baseUrl('videos/list/');?>"><img src="<?php echo $this->baseUrl('public/default/images/camtwo.jpg');?>"></a></a>
									</div>
									<div class="product_info category_title">
										<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>										
									</div>
								</li>
								<li class="category_border">
									<div class="product_image">
										<a href="<?php echo $this->baseUrl('videos/list/');?>"><img src="<?php echo $this->baseUrl('public/default/images/camtwo.jpg');?>"></a></a>
									</div>
									<div class="product_info category_title">
										<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>										
									</div>
								</li>
								<li class="category_border">
									<div class="product_image">
										<a href="<?php echo $this->baseUrl('videos/list/');?>"><img src="<?php echo $this->baseUrl('public/default/images/camtwo.jpg');?>"></a></a>
									</div>
									<div class="product_info category_title">
										<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>										
									</div>
								</li>
							</ul>
							<div class="clear"></div>
						</div>
			
			
			

		</div>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>
</div>