
<!-- edit video file -->
<div id="editvideo_form"  >
<div class="register-form containerbox">
		<p>Edit video file</p>
		<?php //echo "<pre>";print_r($video_data); echo "venu<br>"; print_r($editvideo);?>
		<div class="login-part">
			<form name="editv_form" id="editv_form" action="<?php echo $this->baseUrl('videos/updatevideo/file_id/'). $this->video_data['file_id'];?>" method="POST" >
			<div class="row"><label>Video Name</label><input type="text" id="evideo_name" name="evideo_name" value="<?php echo $this->video_data['file_title'];?>" />
			
			</div>
			<div class="row"><label>Video Path Example:- http://youtu.be/C7FYmj7fMDs</label>
			<input type="text" id="evideo_path" name="evideo_path" value="<?php echo $this->video_data['file_path'];?>"/></div>
			<div class="row"><label>Video category</label>
			<select style="width:200px" name="evideo_category">
			 <option value=""> Select Category</option>
			<?php if(isset($this->CategoriesList) && !empty($this->CategoriesList)) {
			?>
			
			<?php 	foreach($this->CategoriesList as $key =>$cat_list){
					$select	=	'';
					if($this->video_data['album_id'] == $cat_list['album_id']){ $select	=	'selected';}
				echo "<option value='".$cat_list['album_id']."' ".$select." >".ucwords(strtolower($cat_list['album_description']))."</option>";
				} }?>
				</select></div>
			<div class="btn-container"><input type="submit" id="sbt_login" name="sbt_login" value="Update Video"></div>
			</form>
			<div id="login_loading" style="display:none;"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" /></div>
		</div>	
	</div>		
			
</div>
<!-- Add new video file -->