<div class="main_body">
<div class="left width-100">
	<div class="breadcrumbs">
		<span class="home-icon"></span>
		<a href="javascript:void(0)" class="home">Home</a>
		<span class="arrow"></span>
		<a href="javascript:void(0)" class="events">Videos List</a>
		<div class="clear"></div>
	</div>
	<div id="events_page">
		<div class="header_events">
			<h2>Videos</h2>			
			<div class="event_search">
				<input type="text" placeholder="Video Name" name="searchvideo" id="searchvideo"/>
				<input type="submit" value="go" onClick="search_video();" />
			</div>
			<div style="float:right;">
				<a class="button-dark add right fancybox" href="javascript:void(0)" id="addvideo"><span><span>Add Video</span></span></a>
			</div> 
			<div class="clear"></div>
		</div>
		<div class="grid-view">
			<div class="grid-view-heading left">
				<a href="javascript:void(0)" class="button-light icon delete"><span><span>Delete</span></span></a>					
				<a href="javascript:void(0)" class="button-light icon tags"><span><span>Tags</span></span></a>	
			</div>
			<div class="right">
			<select style="width:200px" >
			 <option value=""> Select Category</option>
			<?php if(isset($this->CategoriesList) && !empty($this->CategoriesList)) {
			?>
			
			<?php 	foreach($this->CategoriesList as $key =>$cat_list){ 
				echo "<option value='".$cat_list['album_id']."' onclick='select_category(".$cat_list['album_id'].")'>".ucwords(strtolower($cat_list['album_description']))."</option>";
				} }?>
				</select>
			</div>
			<div class="clear"></div>
			<div id="videolists">
			<table cellpadding="0" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th width='30'><input type="checkbox"/></th>
						<th width='200'>Video Title</th>
						<th  width='100'>Video Category</th>
						<th  width='200'>Video</th>
						<th  width='100'>Date</th>
						<th  width='100'>Action</th>
					</tr>
				</thead>
				<tbody>
				<?php 
				if(isset($this->video_list) && !empty($this->video_list))
				{
				foreach($this->video_list as $videolist){
				?>
					<tr class="odd">
						<td width='30'><input type="checkbox"/></td>
						<td width='200'><?php echo ucwords(strtolower($videolist['file_title']));?></td>
						<td width='100'><?php echo ucwords(strtolower($videolist['album_description']));?></td>
						<td width='100' id="video<?php echo $videolist['file_id'];?>"><input type="hidden" name="videoid" value="<?php echo $videolist['file_path'];?>"><a href="javascript:void(0)" onCLick="video_preview('<?php echo $videolist['file_path'];?>', 'video_<?php echo $videolist['file_id'];?>');" ><img width="120" height="75" src="http://img.youtube.com/vi/<?php echo $videolist['file_path']; ?>/0.jpg"/></a></td>
						<!--td><?php echo $videolist['file_path']; ?></td-->
						<td width='100'><?php echo date('Y-M-d',strtotime($videolist['createddatetime']));?></td>
						<td width='100'> <a id="editvideo" class="button-edit fancy" href="javascript:void(0)"  onClick="edit_video(<?php echo $videolist['file_id']; ?>)";></a> | <a class="button-delete" href="<?php echo $this->baseUrl('videos/deletevideo/file_id/').$videolist['file_id']."/cat_id/".$videolist['album_id']; ?>";></a></td>
					
						</tr>
					<?php } }else{ ?>
					<tr class="grid-view-footer"><td colspan="5">Records not found !</td></tr>
					<?php } ?>
					
				</tbody>
			</table>
			
		<?php 
if(count($this->video_list)>=$this->limit){?>
<input type="hidden" name="cid" id="cid" value="<?php echo $this->cat_id;?>" />
<div class="more_box grid-view-footer" id="<?php echo $this->start;?>">
	<div class="view_more_loader" id="video_view_more_loading" style="display:none;"><img src="<?php echo $this->baseUrl('public/default/images')."/ajax-loader.gif" ?>" ></div>
	<div class="view_more_products" id="video_view_more">View More..</div>
</div><div class="clear"></div>
<?php }?>	
					
		
		</div>	
		</div>
	</div>
	
	<div class="clear"></div>

		
</div>
<div class="clear"></div>
</div>
<!-- video preview -->
<div id="preview_video"  style="display:none;">
<div class="register-form containerbox" >
        <center>
        <iframe  id="myframe" title="YouTube video player" width="425" height="344" src="" frameborder="0" allowfullscreen></iframe>
        </center>
		</div>
</div>
<!-- video preview -->

<!-- Add new video file -->
<div id="add_video_form" style="display:none;">
<div class="register-form containerbox">
		<p>Create new video file</p>
		<div class="login-part">
			<form name="video_form" id="video_form" action="<?php echo $this->baseUrl('videos/addnewvideo');?>" method="POST" >
			<div class="row"><label>Video Name</label><input type="text" id="video_name" name="video_name" /></div>
			<div class="row"><label>Video Path Example:- http://youtu.be/C7FYmj7fMDs</label>
			<input type="text" id="video_path" name="video_path"/></div>
			<div class="row"><label>Video category</label>
			<select style="width:200px" name="video_category">
			 <option value=""> Select Category</option>
			<?php if(isset($this->CategoriesList) && !empty($this->CategoriesList)) {
			?>
			
			<?php 	foreach($this->CategoriesList as $key =>$cat_list){ 
				echo "<option value='".$cat_list['album_id']."' >".ucwords(strtolower($cat_list['album_description']))."</option>";
				} }?>
				</select></div>
			<div class="btn-container"><input type="submit" id="sbt_login" name="sbt_login" value="Add Video"></div>
			</form>
			<div id="login_loading" style="display:none;"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" /></div>
		</div>	
	</div>		
			
</div>
<div id="myvideo_edit" style="display:none;"></div>
<!-- Add new video file -->

