<div class="main_body">
<div class="left width-100">
	<div class="breadcrumbs">
		<span class="home-icon"></span>
		<a href="javascript:void(0)" class="home">Home</a>
		<span class="arrow"></span>
		<a href="javascript:void(0)" class="events">Video`s List</a>
		<div class="clear"></div>
	</div>
	<div id="events_page">
		<div class="header_events">
			<h2>Video`s</h2>			
			<div class="event_search">
				<input type="text" placeholder="Video Name"/>
				<input type="submit" value="go"/>
			</div>
			<div class="clear"></div>
		</div>
		<div class="grid-view">
			<div class="grid-view-heading left">
				<a href="javascript:void(0)" class="button-light icon delete"><span><span>Delete</span></span></a>					
				<a href="javascript:void(0)" class="button-light icon tags"><span><span>Tags</span></span></a>	
			</div>
			<div class="right">
				<select>
					<option>Category</option>
				</select>
			</div>
			<div class="clear"></div>
			<table cellpadding="0" cellspacing="0" width="100%">
				<thead>
					<tr>
						<th width='30'><input type="checkbox"/></th>
						<th >Video Title</th>
						<th  width='100'>Video Category</th>
						<th  width='100'>Video</th>
						<th  width='100'>Date</th>
					</tr>
				</thead>
				<tbody>
					<tr class="odd">
						<td><input type="checkbox"/></td>
						<td>Birth Day</td>
						<td>Category</td>
						<td><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></td>
						<td>08/10/2013</td>
					</tr>
					<tr class="odd">
						<td><input type="checkbox"/></td>
						<td>Birth Day</td>
						<td>Category</td>
						<td><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></td>
						<td>08/10/2013</td>
					</tr>
					<tr class="odd">
						<td><input type="checkbox"/></td>
						<td>Birth Day</td>
						<td>Category</td>
						<td><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></td>
						<td>08/10/2013</td>
					</tr>
					<tr class="odd">
						<td><input type="checkbox"/></td>
						<td>Birth Day</td>
						<td>Category</td>
						<td><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></td>
						<td>08/10/2013</td>
					</tr>
					<tr class="odd">
						<td><input type="checkbox"/></td>
						<td>Birth Day</td>
						<td>Category</td>
						<td><img src="<?php echo $this->baseUrl('public/default'); ?>/images/profile_image.png"/></td>
						<td>08/10/2013</td>
					</tr>					
				</tbody>
			</table>
			<div class="grid-view-footer">
					<a  href="javascript:void(0)" class="left button-light no-text icon refresh"><span><span>Refresh</span></span></a>
					<span class="right">View 1-10 of 20</span>
					<div class="pagention text-center">
						<a  href="javascript:void(0)" class="button-light icon First"><span><span>First</span></span></a>
						<a  href="javascript:void(0)" class="button-light icon prev"><span><span>Prev</span></span></a>
						<span class="info">Page 1 of 2</span>
						<a  href="javascript:void(0)" class="button-light icon next"><span><span>Next</span></span></a>
						<a  href="javascript:void(0)" class="button-light icon last"><span><span>last</span></span></a>
						<select>
							<option>1</option>
							<option>2</option>
						</select>
					</div>
					<div class="clear"></div>
			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>
</div>