<?php 

	$session = new Zend_Session_Namespace('MyPortal');
	$errorsession=new Zend_Session_Namespace("addmerchant");
	$error = $this;
	if(!isset($error->usermanagementsearchfields) && count($error->usermanagementsearchfields) == 0) {
		$error->usermanagementsearchfields = '';
	} 

$usertyperoles = $this->usertyperoles;
$cn=$this->iColumnName;
$do=$this->iDisplayOrder;
if($cn==""){$cn=1;}
if($do==""){$do='DESC';}
$cn='';
//print_r($error->usermanagementsearchfields);
//echo array_key_exists("lastname",$error->usermanagementsearchfields)

?>

		<?php 
      		if($error->error != '') {?>      			
      			<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $error->error;?>
				</div>
      		<?php}else if($session->validateerror != '') {?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $session->validateerror;?>
				</div>
      		<?php $session->validateerror='';      			
      		} else if($session->success != '') {?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $session->success;?>
				</div>
      		<?php $session->success = '';
      		} else if($errorsession->success != '') {?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $errorsession->success;?>
				</div>
			<?php
      			$errorsession->success = '';
      		}
			?>
		
		

		
			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Product's</h2>
						<a href="<?php echo $this->baseUrl('admin/products/register');?>"><button class="btn btn-small" style="float:right;">Add New Product</button></a>					
					</div>
					<div class="box-content">
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>Product Image</th>
								  <th>Product Title</th>
								  <th>Status</th>								  
								  <th>Actions</th>								  
							  </tr>
						  </thead>   
						  <tbody>
							
							<tr>
								<td>aaaa</td>
								<td class="center">bbbb</td>
								<td class="center">
									<span class="label label-success">Active</span>
									<span class="label label-important">Banned</span>
									<span class="label label-warning">Pending</span>
									<span class="label">Inactive</span>
								</td>								
								<td class="center">
									
									<a class="btn btn-success" href="#">
										<i class="icon-zoom-in icon-white"></i>  
										View                                            
									</a>
									<a class="btn btn-info" href="#">
										<i class="icon-edit icon-white"></i>  
										Edit                                            
									</a>
									<a class="btn btn-danger" href="#">
										<i class="icon-trash icon-white"></i> 
										Delete
									</a>
									
									
								</td>
							</tr>
							
							
						  </tbody>
					  </table>            
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
			<!--/row-->
			<!--/row-->
			<!--/row-->
    
			  
				
<script type="text/javascript">
  $(document).ready(function() {
	  $(".error").fadeOut(6000);
});
</script>

		
