<div class="widget">
    <div class="widget-block">
        <div class="widget-header">Best Selling Products</div>
        <div class="widget-cont">
            <ul class="thumbnail">
			
                <div class="clear"></div>
				
				<li class="imageoffer-best-selling">
                    <div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/product2.jpg" width="35" height="35"/></div>
                    <div class="information-only" style="width:143px;">
                        <h4>User Four</h4>
						<div style="height:5px;"></div>
                        <span>Date:2012-11-01  Time:7:00</span>
						<hr style="height:5px; width:100px; color:#DDD;">
						<span style="font-size:12px; clear:both;"><s>Rs. 537</s></span>
						<span style="font-size:14px; clear:both;font-weight:bold;">Rs. 537</span>
                    </div>
                    <div class="clear"></div>
                </li>
				
				<li class="imageoffer-best-selling">
                    <div class="image"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/product1.jpg" width="35" height="35"/></div>
                    <div class="information-only" style="width:143px;">
                        <h4>User Four</h4>
						<div style="height:5px;"></div>
                        <span>Date:2012-11-01  Time:7:00</span>
						<hr style="height:5px; width:100px; color:#DDD;">
						<span style="font-size:12px; clear:both;"><s>Rs. 537</s></span>
						<span style="font-size:14px; clear:both;font-weight:bold;">Rs. 537</span>
                    </div>
                    <div class="clear"></div>
                </li>
               
            </ul>
        </div>
    </div>
</div>