<?php 
$session = new Zend_Session_Namespace('MyPortal');
$errorsession=new Zend_Session_Namespace("addmerchant");
$error = $this;

$merchant_count = $this->merchant_count;
$merchant_list = $this->merchant_list;

$cn=$this->iColumnName;
$do=$this->iDisplayOrder;
if($cn==""){$cn=1;}
if($do==""){$do='DESC';}
$cn='';
?>

		<?php 
      		if($error->error != '') {?>      			
      			<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $error->error;?>
				</div>
      		<?php }else if($session->validateerror != '') {?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $session->validateerror;?>
				</div>
      		<?php $session->validateerror='';      			
      		} else if($session->success != '') {?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $session->success;?>
				</div>
      		<?php $session->success = '';
      		} else if($errorsession->success != '') {?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $errorsession->success;?>
				</div>
			<?php
      			$errorsession->success = '';
      		}
			?>
		
		

		
			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Merchant's</h2>
						<a href="<?php echo $this->baseUrl('admin/merchant/register');?>"><button class="btn btn-small" style="float:right;">Add New Merchant</button></a>					
					</div>
					<div class="box-content">
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>Sl No</th>
								  <th>Image/Title</th>
								  <th>Contact Details</th>
								  <th>Status</th>
								  <th>Actions</th>								  
							  </tr>
						  </thead>   
						  <tbody>
							<?php 
							$i=1;
							foreach($merchant_list as $each_merchant){?>
							<tr>
								<td><?php echo $i;$i++;?></td>
								<td align="center">								
									<?php if($each_merchant['merchant_images']!=''){?>
									<img src="<?php echo $this->baseUrl('public/uploads/merchant_images');?>/<?php echo $each_merchant['merchant_images'];?>" width="50" />									
									<?php }else{?>
									<img src="<?php echo $this->baseUrl('public/uploads/merchant_images');?>/default.jpg" width="50" />
									<?php }?>
									<br><?php  echo $each_merchant['merchant_title']; ?>
								</td>
								<td class="center">
								<?php  
								if($each_merchant['merchant_email']){echo "Email : ".$each_merchant['merchant_email']."<br>";}
								if($each_merchant['merchant_email']){echo "Mobile : ".$each_merchant['merchant_mobile']."<br>";}	
								if($each_merchant['merchant_email']){echo "Phone : ".$each_merchant['merchant_phone']."<br>";}
								if($each_merchant['merchant_email']){echo "Fax : ".$each_merchant['merchant_fax'];}														
								?>
								</td>	
								<td class="center">								
					
									<?php if($each_merchant['statusid']=="1") {?>
									<a href="<?php echo $this->baseUrl('admin/merchant/lock/merchantId/') . $each_merchant['merchant_id'];?>" onClick="return confirm('Do you want to continue?')">
									<span class="label label-success">Active</span>
									</a>
									<?php }?>
									<?php if($each_merchant['statusid']=="6") {?>
									<a href="<?php echo $this->baseUrl('admin/merchant/unlock/merchantId/') . $each_merchant['merchant_id'];?>" onClick="return confirm('Do you want to continue?')">
									<span class="label">Inactive</span>
									</a>							   
									<?php } ?>
									
								</td>								
								<td class="center">
									
									<a class="btn btn-info" href="<?php echo $this->baseUrl('admin/merchant/edit/merchantId/') . $each_merchant['merchant_id'];?>">
										<i class="icon-edit icon-white"></i>  
										Edit                                            
									</a>
									&nbsp;&nbsp;
									<a class="btn btn-danger" href="<?php echo $this->baseUrl('admin/mercahnt/delete/merchantId/') . $each_merchant['merchant_id'];?>" onClick="return confirm('Do you want to continue?')">
										<i class="icon-trash icon-white"></i> 
										Delete
									</a>								
									
								</td>
							</tr>
							<?php }?>
							
						  </tbody>
					  </table>            
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
			<!--/row-->
			<!--/row-->
			<!--/row-->
    
			  
				
<script type="text/javascript">
  $(document).ready(function() {
	  $(".error").fadeOut(6000);
});
</script>

		
