<?php
$session = new Zend_Session_Namespace('MyPortal');
$errorsession=new Zend_Session_Namespace("addmerchant");
$error = $this;

$useractivitylog_list = $this->useractivitylog_list;
//echo "<pre>";
//print_r($useractivitylog_list);
$cn=$this->iColumnName;
$do=$this->iDisplayOrder;
if($cn==""){$cn=1;}
if($do==""){$do='DESC';}
$cn='';
?>
	
		

		
			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> User Activity Log's</h2>						
					</div>
					<div class="box-content">
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th width="50">Sl No</th>
								  <th width="200">User Name</th>
								  <th width="200">User Email</th>
								  <th>User Action</th>
								  <th>User Action Description</th>
								  <th width="100">Date Time</th>								  
							  </tr>
						  </thead>   
						  <tbody>
							<?php 
							$i=1;
							foreach($useractivitylog_list as $each_useractivitylog){
							?>
							<tr>
								<td><?php echo $i;$i++;?></td>
								<td>
								<?php echo "[".$each_useractivitylog['userid']."] ".$each_useractivitylog['firstname']." ".$each_useractivitylog['lastname']."<br>";?>								
								</td>
								<td>								
								<?php echo $each_useractivitylog['userloginid'];?>
								</td>
								<td><?php echo $each_useractivitylog['useraction'];?></td>
								<td><?php echo $each_useractivitylog['useractiondesc']."<br><br>".$each_useractivitylog['actiondesc'];?></td>
								<td><?php echo $each_useractivitylog['createddatetime'];?></td>
							</tr>
							<?php }?>
						  </tbody>
					  </table>            
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
			<!--/row-->
			<!--/row-->
			<!--/row-->
    
			  
				
<script type="text/javascript">
  $(document).ready(function() {
	  $(".error").fadeOut(6000);
});
</script>

		
