<?php
$this->session = new Zend_Session_Namespace('MyClientPortal');
$isSignedIn = $this->session->isSignedIn;
?>
<div class="header-bottom">
	<div class="wrapper">
		<div class="call"><h5>ORDER BY PHONE</h5><h3>0120-4455918</h3></div>
		<div class="search">
			<form>
				<select>
					<option>all</option>
					<option>Mobile</option>
				</select>
				<input type="text" />
				<input type="submit" value="Go"/>
			</form>
		</div>
		<div class="right_cart">
			
			
			
			
			<?php
			if($isSignedIn!=1){
			?>
			<a alt="Your Account" class="" href="javascript:void(0)" id="signup">
			  <span class="top">Hello, <span class="height">Sign</span></span>
			  <span class="label">Your Account</span>
			</a>
			<span class="line"></span>
			<?php }else{?>
			<a alt="Your Account" class="" href="javascript:void(0)" id="myaccount">
			  <span class="top">Hello, <span class="height">Shiva</span></span>
			  <span class="label">Your Account</span>
			</a>
			<div id="myac-options" style="display:none;z-index:1000;">
				<ul >
					<li class="top_arrow"></li>
					<li><a href="<?php echo $this->baseUrl('profile/view/');?>">My profile</a></li>
					<li><a href="javascript:void(0)">Settings</a></li>
					<li><a href="javascript:void(0)">Privacy Options</a></li>
					<li><a href="<?php echo $this->baseUrl('signin/logout/');?>">Sign Out</a></li>
				</ul>
			</div>
			<span class="line"></span>
			<?php }?>
			
			<a alt="Your Cart" class="" href="javascript:void(0)" id="cart">
			  <span class="top">0</span>
			  <span class="label">Cart</span>
			</a>
			
			
			
			
			
			
			<div class="clear"></div> 
		</div>
		<div class="clear"></div>
	</div>
</div>