<?php
$this->session = new Zend_Session_Namespace('MyClientPortal');
$isSignedIn = $this->session->isSignedIn;

$config=Zend_Registry::get('config');
?>
<div class="header-bottom">
	<div class="wrapper">
		<div class="call"><h5>ORDER BY PHONE</h5><h3><?php echo $config->site->header->phone;?></h3></div>
		<div class="search">
			<form>
				<select>
					<option>all</option>
					<option>Mobile</option>
				</select>
				<input type="text" />
				<input type="submit" value="Go"/>
			</form>
		</div>
		<div class="right_cart">
			
			
			
			
			
			
			<a alt="Your Cart" class="" href="javascript:void(0)" id="cart">
			  <span class="top">0</span>
			  <span class="label">Cart</span>
			</a>
			
			
			
			
			
			
			<div class="clear"></div> 
		</div>
		<div class="clear"></div>
	</div>
</div>