<?php
$this->session = new Zend_Session_Namespace('MyClientPortal');
$isSignedIn = $this->session->isSignedIn;

$config=Zend_Registry::get('config');
?>
<div class="header-bottom">
	<div class="wrapper">	
	
		<?php 
		if(isset($isSignedIn) && $isSignedIn==1){?>
		
			<div style="padding-right:100px; margin-right:100px;">
			<?php
			echo $this->action('topcatmenu', 'categories', 'default', array('a_parameter'=>'a_value'));
			?>
			<div style="clear:both;"></div>
			</div>			
			
		<?php }else{?>		
		<div class="call"><h5>ORDER BY PHONE</h5><h3><?php echo $config->site->header->phone;?></h3></div>
		<?php }?>
		<div class="search">
			<form>
				<select>
					<option>all</option>
					<option>Mobile</option>
				</select>
				<input type="text" />
				<input type="submit" value="Go"/>
			</form>
		</div>
		<div class="right_cart">
			
			
			
			
			
			
			<a alt="Your Cart" class="" href="<?php echo $this->baseUrl('products/viewcart');?>" id="cart">
			  <span class="top"><?php echo $this->CartCount;?></span>
			  <span class="label">Cart</span>
			</a>
			
			
			
			
			
			
			<div class="clear"></div> 
		</div>
		<div class="clear"></div>
	</div>
</div>