<?php
//echo "<pre>";
print_r($this->ProductsList);
?>
<div class="main_body">
<div class="left width-100">	
	<div class="product_list">
		<h4>Digital Cameras Best Sellers</h4>
		<ul>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camtwo.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camone.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camtwo.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camone.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
		</ul>
		<div class="clear"></div>
	</div>
	
	<br><br>
	
	<div class="product_list">		
		<ul>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camtwo.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camone.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camtwo.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
			<li>
				<div class="product_image">
					<a href="javascript:void(0)"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/camone.jpg"></a></a>
				</div>
				<div class="product_info">
					<a href="javascript:void(0)">Canon PowerShot A2300 IS 16.0 MP... </a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$120.00</span>
					</div>
				</div>
			</li>
		</ul>
		<div class="clear"></div>
	</div>
</div>
<div class="clear"></div>
</div>