<?php
//echo "<pre>";
//print_r($this->ProductsList);
$i=1; 
$special_array   = array(" ",".",";","|","/",",","'","[","]","{","}","--",":","~","`","!","@","#","$","%","^","&","*","(",")","+","?");
$replace = '-';
foreach($this->ProductsList as $each_ProductsList){
if($i%4==1){
?>
	<div class="product_list">		
		<ul>
		<?php }?>
			<li class="product_id_class" id="product_id_<?php echo $each_ProductsList['product_id'];?>">
				<div class="product_image">
					<a href="<?php echo $this->baseUrl('products/view/id')."/".$each_ProductsList['product_id']."/".str_replace($special_array, $replace,$each_ProductsList['product_title']);?>">					
					<?php if($each_ProductsList['product_image']!=''){?>
					<img src="<?php echo $this->baseUrl('public/uploads/product_images')."/".$each_ProductsList['product_image']; ?>" width="135" height="135">
					<?php }else{?>
					<img src="<?php echo $this->baseUrl('public/uploads/product_images/No_Image_Available.JPG'); ?>" width="135" height="135">
					<?php }?>
					</a></a>
				</div>
				<div class="product_info" style="text-align:center;">
					<a href="javascript:void(0)"><?php echo $each_ProductsList['product_title'];?></a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$<?php echo $each_ProductsList['product_price_details'];?></span>
					</div>
				</div>
			</li>
			<?php 
			if($i%4==0){
			?>
		</ul>
		
	</div>
	
	<div class="product_list">
	<h4>&nbsp;</h4>
	</div><br>
	<h4></h4>
<?php }$i++; }?>

<div class="clear"></div>

<?php 
if(count($this->ProductsList)==$this->limit){?>
<div class="more_box" id="<?php echo $this->start;?>">
	<div class="view_more_loader" id="product_view_more_loading"><img src="<?php echo $this->baseUrl('public/default/images')."/ajax-loader.gif" ?>" ></div>
	<div class="view_more_products" id="product_view_more">View More..</div>
</div>
<?php }else{/*?>
	<div class="no_result_found">-No Result Found-</div>
<?php */}?>