<?php
//echo "<pre>";
//print_r($this->ProductsList);
?>
<div class="main_body">
<div class="left width-100">


<div class="product_list">
<h4>Digital Cameras Best Sellers</h4>
</div>
<br>

<?php
$i=1; 
$special_array   = array(" ",".",";","|","/",",","'","[","]","{","}","--",":","~","`","!","@","#","$","%","^","&","*","(",")","+","?");
$replace = '-';
foreach($this->ProductsList as $each_ProductsList){
if($i%4==1){
?>
	<div class="product_list">		
		<ul>
		<?php }?>
			<li>
				<div class="product_image">
					<a href="<?php echo $this->baseUrl('products/view/id')."/".$each_ProductsList['product_id']."/".str_replace($special_array, $replace,$each_ProductsList['product_title']);?>">					
					<?php if($each_ProductsList['product_image']!=''){?>
					<img src="<?php echo $this->baseUrl('public/uploads/product_images')."/".$each_ProductsList['product_image']; ?>" width="175" height="175">
					<?php }else{?>
					<img src="<?php echo $this->baseUrl('public/uploads/product_images/No_Image_Available.JPG'); ?>" width="175" height="175">
					<?php }?>
					</a></a>
				</div>
				<div class="product_info" style="text-align:center;">
					<a href="javascript:void(0)"><?php echo $each_ProductsList['product_title'];?></a>
					<span class="rating rating-1"></span>
					<div class="price">
						<span class="old">$150.00</span><span class="new">$<?php echo $each_ProductsList['product_price_details'];?></span>
					</div>
				</div>
			</li>
			<?php 
			if($i%4==0){
			?>
		</ul>
		
	</div>
	
	<div class="product_list">
	<h4>&nbsp;</h4>
	</div><br>
	<h4></h4>
<?php }$i++; }?>
	

</div>
<div class="clear"></div>
</div>