<?php
$this->session = new Zend_Session_Namespace('MyClientPortal');
$this->billingaddress = new Zend_Session_Namespace('MyClientPortalBillingAddress');
$isSignedIn = $this->session->isSignedIn;
$displayName = $this->session->name;
?>
<div class="main_body">
	<div class="left width-100">
		<div id="checkoutSteps">
		
			<?php 
			if($isSignedIn==1){
				$active_tab = 2;
			}else{
				$active_tab = 1;
			}
			?>
			
			
			<ul class="trigger">
				<li <?php if($active_tab==1){?>class="active"<?php }?>>
					<a href="javascript:void(0)" rel="#login_panel"><span>1</span>Login</a>
				</li>
				<li>
					<a href="javascript:void(0)" <?php if($isSignedIn==1){?>rel="#shipping_panel"<?php }?>><span>2</span>Billing / Shipping Address</a>
				</li>
				<li <?php if($active_tab==2){?>class="active"<?php }?>>
					<a href="javascript:void(0)" <?php if($isSignedIn==1){?>rel="#order_summary"<?php }?>><span>3</span>Order Summary</a>
				</li>
				<li>
					<a href="javascript:void(0)" <?php if($isSignedIn==1){?>rel="#payment_panel"<?php }?>><span>4</span>Payment Options</a>
				</li>
			</ul>
			<div class="container">
			
			
			
				<div id="login_panel" class="cont" style="display:<?php if($active_tab==1){?>block<?php }else{?>none<?php }?>;">
					<div style="clear:both;"><br></div>
					
					<?php if($isSignedIn==1){?>
						<a href="javascript:void(0)" rel="#shipping_panel">					
						<?php echo "Hello: ".$displayName;?> Please click here to Continue
						</a>
					<?php }else{?>					
						<a id="signup" class="" href="javascript:void(0)" alt="Your Account">
						<span class="label" style="padding-left:20px">Click Here For Sign-In</span>
						</a>
					<?php }?>
					
					<div style="clear:both;"><br></div>
				</div>
				
				
				
				<div id="order_summary" class="cont" style="display:<?php if($active_tab==2){?>block<?php }else{?>none<?php }?>;" >
					<table width="700">
					<tr>
						<td>					
							<h3><b>Enter Billing address</b></h3><br>
							<div class="form">
								<div class="row">
									<label>First Name<span>*</span></label>:<?php echo $this->billingaddress->billing_first_name;?>
								</div>
								<div class="row">
									<label>Last Name<span>*</span></label>:<?php echo $this->billingaddress->billing_last_name;?>
								</div>
								<div class="row">
									<label>Email Address<span>*</span></label>:<?php echo $this->billingaddress->billing_email_address;?>
								</div>
								<div class="row">
									<label>Street Address<span>*</span></label>:<?php echo $this->billingaddress->billing_street_address;?>
								</div>
								<div class="row">
									<label>Landmark<span>*</span></label>:<?php echo $this->billingaddress->billing_landmark;?>
								</div>
								<div class="row">
									<label>Address lane 2<span></span></label>:<?php echo $this->billingaddress->billing_address_lane_2;?>
								</div>
								<div class="row">
									<label>City<span>*</span></label>:<?php echo $this->billingaddress->billing_city;?>
								</div>
								<div class="row">
									<label>State<span>*</span></label>:<?php echo $this->billingaddress->billing_state;?>
								</div>
								<div class="row">
									<label>Country<span>*</span></label><span class="value">India<span style="margin:5px; color:#666;">(Service Available India only)</span></span>
								</div>
								<div class="row">
									<label>Pincode<span>*</span></label>:<?php echo $this->billingaddress->billing_pincode;?>
								</div>
								<div class="row">
									<label>Phone<span>*</span></label>:<?php echo $this->billingaddress->billing_phone;?>
								</div>
							</div>
						</td>
						<td width="20"></td>
						<td>					
							<h3><b>Enter Shipping address</b></h3><br>
							<div class="form">
								<div class="row">
									<label>First Name<span>*</span></label>:<?php echo $this->billingaddress->shipping_first_name;?>
								</div>
								<div class="row">
									<label>Last Name<span>*</span></label>:<?php echo $this->billingaddress->shipping_last_name;?>
								</div>
								<div class="row">
									<label>Email Address<span>*</span></label>:<?php echo $this->billingaddress->shipping_email_address;?>
								</div>
								<div class="row">
									<label>Street Address<span>*</span></label>:<?php echo $this->billingaddress->shipping_street_address;?>
								</div>
								<div class="row">
									<label>Landmark<span>*</span></label>:<?php echo $this->billingaddress->shipping_landmark;?>
								</div>
								<div class="row">
									<label>Address lane 2<span></span></label>:<?php echo $this->billingaddress->shipping_address_lane_2;?>
								</div>
								<div class="row">
									<label>City<span>*</span></label>:<?php echo $this->billingaddress->shipping_city;?>
								</div>
								<div class="row">
									<label>State<span>*</span></label>:<?php echo $this->billingaddress->shipping_state;?>
								</div>
								<div class="row">
									<label>Country<span>*</span></label><span class="value">India<span style="margin:5px; color:#666;">(Service Available India only)</span></span>
								</div>
								<div class="row">
									<label>Pincode<span>*</span></label>:<?php echo $this->billingaddress->shipping_pincode;?>
								</div>
								<div class="row">
									<label>Phone<span></span></label>:<?php echo $this->billingaddress->shipping_phone;?>
								</div>
							</div>
						</td>
					</tr>
					</table>
					
					<div style="clear"><br></div>
					<div class="right">
						<a class="anchor_link_button" href="<?php echo $this->baseUrl('products/placeorder');?>">Proceed to checkout</a>
						<a class="anchor_link_button" href="<?php echo $this->baseUrl('products/placeorder');?>">Continue Checkout</a>
					</div>
					<div class="clear"></div>
				</div>

			</div>
		</div>
	</div>
	<div class="clear"></div>
</div>