<?php
//echo "<pre>";
//print_r($this->productdetails);
?>
<div class="main_body">
	<div class="mprod-section unit" itemscope="" itemtype="http://schema.org/Product">

		<form action="" method="POST" name="product_details_form" id="product_details_form" enctype='multipart/form-data'>
			<div id="topsection" class="line bpadding10">
					
					
					<div class="mprod-basic-info unit">
						<div class="multi-images-section">
						
							<?php
							//echo "<pre>";
							//print_r($this->ProductImageDetails);
							?>
							
							<link rel="stylesheet" href="<?php echo $this->baseUrl('public/default/css/multizoom.css');?>" type="text/css" />
							<script type="text/javascript" src="<?php echo $this->baseUrl('public/default/js/multizoom.js');?>"></script>
							<script type="text/javascript">
							jQuery(document).ready(function($){

								$('#image1').addimagezoom({ // single image zoom
									zoomrange: [3, 10],
									magnifiersize: [300,300],
									magnifierpos: 'right',
									cursorshade: true,
									largeimage: 'hayden.jpg' //<-- No comma after last option!
								})


								$('#image2').addimagezoom() // single image zoom with default options
								
								$('#multizoom1').addimagezoom({ // multi-zoom: options same as for previous Featured Image Zoomer's addimagezoom unless noted as '- new'
									descArea: '#description', // description selector (optional - but required if descriptions are used) - new
									speed: 1500, // duration of fade in for new zoomable images (in milliseconds, optional) - new
									descpos: true, // if set to true - description position follows image position at a set distance, defaults to false (optional) - new
									imagevertcenter: true, // zoomable image centers vertically in its container (optional) - new
									magvertcenter: true, // magnified area centers vertically in relation to the zoomable image (optional) - new
									zoomrange: [3, 10],
									magnifiersize: [250,250],
									magnifierpos: 'right',
									cursorshadecolor: '#fdffd5',
									cursorshade: true //<-- No comma after last option!
								});
								
								$('#multizoom2').addimagezoom({ // multi-zoom: options same as for previous Featured Image Zoomer's addimagezoom unless noted as '- new'
									descArea: '#description2', // description selector (optional - but required if descriptions are used) - new
									disablewheel: true // even without variable zoom, mousewheel will not shift image position while mouse is over image (optional) - new
											//^-- No comma after last option!	
								});
								
							})

							</script>
							
							<div style="float:right;width:350px;">					
								<?php 			
								foreach($this->ProductImageDetails as $each_ProductImages){			
								if(trim($each_ProductImages['product_thumbnail'])==1){?>
								<div class="targetarea diffheight">
								<img id="multizoom2" style="float:right;" src="<?php echo $this->baseUrl('public/uploads/product_images')."/".$each_ProductImages['product_image']; ?>" width="300" height="225">
								</div>
								<?php }}?>
								
								<div class="multizoom2 thumbs">
								<?php
								if(count($this->ProductImageDetails)>1){
								foreach($this->ProductImageDetails as $each_ProductImages){			
								if(trim($each_ProductImages['product_thumbnail'])==0 || $each_ProductImages['product_thumbnail']==1){?>
								<a href="<?php echo $this->baseUrl('public/uploads/product_images')."/".$each_ProductImages['product_image']; ?>" data-large="<?php echo $this->baseUrl('public/uploads/product_images')."/".$each_ProductImages['product_image']; ?>" data-title="Image" data-dims="300, 225">
								<img style="float:right;margin:2px;" src="<?php echo $this->baseUrl('public/uploads/product_images')."/".$each_ProductImages['product_image']; ?>"  width="55">
								</a>
								<?php }}}?>
								</div>
							</div>
							
							
						</div>
						
						<div class="clear"></div>
						
						<div class="mprod-social-info fksk-mprod-social-info" id="mprod-social-info-id">		
							<div class="line social-plugins">
								<div class="line social-btn-container">
								
								
								<?php /*
								<!-- AddThis Button BEGIN -->
								<div class="addthis_toolbox addthis_default_style ">
								<a class="addthis_button_preferred_1"></a>
								<a class="addthis_button_preferred_2"></a>
								<a class="addthis_button_preferred_3"></a>
								<a class="addthis_button_preferred_4"></a>
								<a class="addthis_button_compact"></a>
								<a class="addthis_counter addthis_bubble_style"></a>
								</div>
								<script type="text/javascript">var addthis_config = {"data_track_addressbar":true};</script>
								<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-51f2e8c31cff37cc"></script>
								<!-- AddThis Button END -->
								*/ ?>
								
								</div>
							</div>
					 
					 
					 
							<div class="tmargin5 line fk-text-center">
								<div class="fk-user-rating">
								<span class="message">Rate this product</span> &nbsp;
								<ul class="fk-give-star " data-rating-count="765" stars="0" data-ratings-location="Top">
								<li class="user-rating" style="width:0%"></li>
								<li><a title="Rate this 1 star out of 5" class="star-1 login-required" href="javascript:void(0)">1</a></li>
								<li><a title="Rate this 2 stars out of 5" class="stars-2 login-required" href="javascript:void(0)">2</a></li>
								<li><a title="Rate this 3 stars out of 5" class="stars-3 login-required" href="javascript:void(0)">3</a></li>
								<li><a title="Rate this 4 stars out of 5" class="stars-4 login-required" href="javascript:void(0)">4</a></li>
								<li><a title="Rate this 5 stars out of 5" class="stars-5 login-required" href="javascript:void(0)">5</a></li>
								</ul>
								</div>


								<div class="line tmargin5">
								<a class="login-required" href="javascript:void(0)">Write a review</a>
								</div>
							</div>	
						</div>	
					</div>
					







					<div class="mprod-summary lastUnit">

							<!-- Top Title Details -->    
							<div class="mprod-summary-title fksk-mprod-summary-title">
								<h1 itemprop="name" title="Sony Xperia Tipo"><?php echo $this->productdetails['product_title'];?></h1>
								<span class="line extra_text">(Tag Lane)</span>	
								<div style="height:20px;"></div>								
								<div class="mprod-warrenty">
								<?php echo $this->productdetails['product_small_description'];?>
								</div>
							</div>
							
							
							
							
							
							<div class="shop-section line bmargin10 tmargin5">
								<div class="price-section fksk-price-section unit" style="width:350px;">
									<div class="price-table">
										<div class="line">
											<div class="prices">												
												<?php 
												//echo "<pre>";
												//print_r($this->ProductPriceDetails);
												?>												
												<br>
												<div class="offer-box fk-font-small">
													<div class="offer-sticker"></div>
													<div class="line" style="line-height:23px;">
														<input type="hidden" name="product_id" value="<?php echo $this->product_id?>" />
														<?php 
														$p=0;
														foreach($this->ProductPriceDetails as $each_ProductPriceDetails){														
														?>
														<input type="radio" name="product_price_id" <?php if($p==0){?>checked="checked"<?php }?> value="<?php echo $each_ProductPriceDetails['product_price_id'];?>" />
														<?php 
														echo $each_ProductPriceDetails['product_price_description']." &nbsp; ";													
														
														if($each_ProductPriceDetails['product_discount']=='0'){
															echo "Rs.".$each_ProductPriceDetails['product_price'];
														}else{
															
															if($each_ProductPriceDetails['product_discount_type']=='Percentage'){
																echo "Rs.".$each_ProductPriceDetails['product_price']."(".$each_ProductPriceDetails['product_discount']."% Discount)";
															}
															
															if($each_ProductPriceDetails['product_discount_type']=='Amount'){
																echo "Rs.".$each_ProductPriceDetails['product_price']."(Rs.".$each_ProductPriceDetails['product_discount']." Discount)";
															}
														}
														?>
														<br>
														<?php $p++;}?>													
													</div>
												</div>											
											</div>
										</div>
									</div>
								</div>
								
								<div class="stock-section lastUnit">									
									<span class="fk-font-finalprice fk-font-big fk-bold final-price">
									Rs. 8490									
									</span>
									<br>
									<div class="label fksk-label">Inclusive of taxes</div>	
									<br>
									<div class="stock-status instock fk-font-normal fk-bold" id="fk-stock-info-id">In Stock.</div>									
								</div>								
							</div>
							





							<div class="shipping-section fksk-shipping-section" id="fk-mprod-shipping-section-id">
								<div class="block-header fksk-block-header line">
								<div class="block-headertext">FREE Home Delivery</div>
								<div class="shipping-details">Delivered in 2-3 business days.</div>
								</div>
								
								
								<div class="block-body fksk-block-body line">
								
								<div class="line">
								<div class="unit buy-btn-sec" id="mprod-buy-btn">								
								<a href="javascript:void(0)" class="fk-inline-block buy-btn fksk-buy-btn" id="add_to_cart">
								</a>
								</div>
								<div class="lastUnit">
								<div class="mprod-shipment-text fk-normalfont">with an option to pay <div class="boldtext">Cash on Delivery</div></div>
								</div>
								</div>
								

								<div class="telesale-msg">
									<img src="<?php echo $this->baseUrl('public/default/images/phone-icon-7b7b8b07.png');?>">									
									You may also call us at <span class="highlight">
									<?php 
									$config=Zend_Registry::get('config');
									echo $config->site->header->phone;
									?>
									</span> to order<span style="font-size:11px"> (toll free)</span>.
								</div>

								<?php /*
								<div class="line mprod-wlist-text tmargin10">
									<img src="<?php echo $this->baseUrl('public/default/images/my-wishlist-icon-68c3111a.png');?>">
									<a href="javascript:void(0)" class="pp-add-to-wishlist login-required">Add to My Wishlist</a>
									<span class="wlist-cmp-divider">|</span>
									<a href="javascript:void(0)" class="pp-add-to-compare fk-inline-block enabled">Add to compare</a>
								</div>
								*/?>
								</div>
							</div>
					</div>

			</div>
		</form>
			
			


			<div class="mprod-details">
			
					<div class="line bmargin20">
					<div class="unit"><div></div></div>
					<div class="lastUnit"><div></div></div>
					</div>  

			  
					<div class="item_detail_details_left mobile_prod_left" style="width:100%">
					<div id="keyFeatures"></div>
					<div class="item_left_column" id="description">
					
						<h3 class="item_desc_title"><b><?php echo $this->productdetails['product_title'];?></b></h3>
						<div class="cls"></div>
					
						<div class="item_desc_text line">
						<div style="float:left" style="padding:10px; line-height:20px;">
							<?php echo html_entity_decode($this->productdetails['product_description']);?>
							<br />
						</div>
						</div>
				
				

						<?php if(count($this->ProductAttributesDetails)>0){?>
						<div id="specifications" class="item_left_column">
							<h3 class="item_desc_title">
								<b> Specifications of <?php echo $this->productdetails['product_title'];?></b>
							</h3>
							
							<?php
							//echo "<pre>";
							//print_r($this->ProductAttributesDetails);
							foreach($this->ProductAttributesDetails as $each_ProductAttributesDetails){								
								$ProductAttributesDetails_array[$each_ProductAttributesDetails['attributes_set_id']]['attributes_set_title'] = $each_ProductAttributesDetails['attributes_set_title'];
								$ProductAttributesDetails_array[$each_ProductAttributesDetails['attributes_set_id']][$each_ProductAttributesDetails['attribute_id']]['attribute_title'] = $each_ProductAttributesDetails['attribute_title'];
								$ProductAttributesDetails_array[$each_ProductAttributesDetails['attributes_set_id']][$each_ProductAttributesDetails['attribute_id']]['attribute_value'] = $each_ProductAttributesDetails['attribute_value'];													
							}							
							//print_r($ProductAttributesDetails_array);
							//exit;
							?>

							<table cellspacing="0" class="fk-specs-type2">
							<tbody>
							<?php foreach($ProductAttributesDetails_array as $key=>$value){
							//print_r($key);
							//print_r($value);
							?>
							<tr>
								<th class="group-head" colspan="2">
								<?php 
								echo $value['attributes_set_title'];
								unset($ProductAttributesDetails_array[$key]['attributes_set_title']);
								unset($value['attributes_set_title']);
								?>
								</th>
							</tr>
							<?php
							foreach($value as $key=>$each_value){							
							?>
							<tr>
								<td class="specs-key"><?php echo $each_value['attribute_title'];?></td>
								<td class="specs-value fk-data" style="word-wrap: break-word;"><?php echo $each_value['attribute_value'];?></td>
							</tr>							
							<?php }?>
							<tr>
								<td class="specs-key" colspan="2" height="10"></td>								
							</tr>
							<?php }?>
							</tbody>
							</table>
						</div>
						<?php }?>
				
				

						<div class="fclear"></div>
						<div class="fk-gen-msg"><span class="nt">Please note:</span>All products sold on Getlinc are brand new and 100% genuine</div>
						<div class="cls"></div>			  
						<div class="fclear"></div>
					</div>
					</div>		
			</div>
			
			
			
			<div class="fk-pp-ugc recent-reviews fclear">

					<h3 class="fk-font-big bmargin10 section-title">
					<strong>Reviews of <?php echo $this->productdetails['product_title'];?></strong>
					</h3>

				
					<!-- Review Box -->
					<?php /*
					<div class="fk-pp-ugc-section1">
							<div class="unit size1of2 ratings-section">
								<div class="size1of2 unit section1">
									<div class="line">
									Average Rating
									</div>
									<div class="line">
									<div class="fk-stars" title="4.1 stars">
									<div class="rating" style="width: 82%;">
									</div>
									</div>

									<strong>4.1</strong>
									</div>
									<div class="line fk-font-small">
									(Based on 660 ratings)
									</div>
									<div class="line tmargin5">
									<a href="javascript:void(0)">
									Read 273 Reviews</a>
									</div>
								</div>
								<div class="size1of2 lastUnit section2">
									<ul class="rating-histogram">
									<li class="fk-font-small tmargin3">
									<span>5 star</span>
									<div class="rating-bars">
									<div class="progress  " style="width:60.151515151515%"></div>
									</div>
									&nbsp;<strong>397</strong>
									</li>
									<li class="fk-font-small tmargin3">
									<span>4 star</span>
									<div class="rating-bars">
									<div class="progress  " style="width:15.606060606061%"></div>
									</div>
									&nbsp;<strong>103</strong>
									</li>
									<li class="fk-font-small tmargin3">
									<span>3 star</span>
									<div class="rating-bars">
									<div class="progress  " style="width:7.8787878787879%"></div>
									</div>
									&nbsp;<strong>52</strong>
									</li>
									<li class="fk-font-small tmargin3">
									<span>2 star</span>
									<div class="rating-bars">
									<div class="progress  " style="width:4.5454545454545%"></div>
									</div>
									&nbsp;<strong>30</strong>
									</li>
									<li class="fk-font-small tmargin3">
									<span>1 star</span>
									<div class="rating-bars">
									<div class="progress  " style="width:11.818181818182%"></div>
									</div>
									&nbsp;<strong>78</strong>
									</li>
									</ul>
								</div>
							</div>
							
							<div class="lastUnit size1of3 action-section">

								<div class="fk-user-rating line bmargin10">
								<div class="message">
								<strong>Have you used this product?</strong>
								<br>
								<strong>Rate it now.</strong>
								</div>

								<ul class="fk-give-star " data-rating-count="660" stars="0">
								<li class="user-rating" style="width:0%"></li>
								<li><a title="Rate this 1 star out of 5" class="star-1 login-required" href="javascript:void(0)">1</a></li>
								<li><a title="Rate this 2 stars out of 5" class="stars-2 login-required" href="javascript:void(0)">2</a></li>
								<li><a title="Rate this 3 stars out of 5" class="stars-3 login-required" href="javascript:void(0)">3</a></li>
								<li><a title="Rate this 4 stars out of 5" class="stars-4 login-required" href="javascript:void(0)">4</a></li>
								<li><a title="Rate this 5 stars out of 5" class="stars-5 login-required" href="javascript:void(0)">5</a></li>
								</ul>
								</div>

								<div class="line">
								<a class="fk-button-blue login-required" href="javascript:void(0)"> Write a Review </a>
								</div>
							</div>
							<div class="fclear"></div>
					</div>
					*/?>






				<div class="fk-pp-ugc-section2 line">
					<div class="unit size3of4 helpful-review-container rmargin20">
							<h3 class="fk-font-big section-title fk-float-left">Most Helpful Reviews</h3>
							
					
						<div class="review-list">
						
								<div class="fclear fk-review line " review-id="RV2VNQ50D5SOSD6IM">			
								
								
										<div class="unit size1of5 section1">
											<div class="line">
											<div class="fk-stars-small" title="4 stars">
											<div class="rating" style="width: 80%;">
											</div>
											</div>
											</div>
											<div class="line">
											<a class="fk-font-bold load-user-widget" profile_name="him_ash-5521" href="javascript:void(0)">Profile Name</a>
											</div>
											<div class="date line fk-font-small"></div>
											<div class="line tmargin5 badge-certified-buyer">
											<img src="http://img6.flixcart.com/www/prod/images/certified_buyer-99274b69.png" alt="certified buyer" class="img">
											</div>
										</div>
										
																
										<div class="lastUnit size4of5 section2">
											<div class="line fk-font-big bmargin5">
											<strong>Review Title</strong>
											</div>
											<p class="line bmargin10">
											Review Description Review Description  Review Description  Review Description  Review Description  Review Description  Review Description  Review Description                              
											</p>
										
										

										
											<div class="line fk-font-small">
												<div class="unit">
												<strong>83%</strong> of <strong>92</strong> users found this review helpful.
												</div>						
											
												<div class="unitExt">
												<a href="javascript:void(0)">Permalink</a>
												&nbsp;
												<a href="javascript:void(0)" class="fk-ugc-review-reportAbuse login-required">Report Abuse</a>
												</div>
												<div class="cls"></div>
											</div>
										</div>
								</div>				
						</div>
						<div class="line">
							<a href="javascript:void(0)">Read all reviews</a>
						</div>                
					</div>                    
				</div>
				
			 <div class="fclear"></div>
			</div>

	<div class="clear"></div>
	</div>
</div>
<br><br>