<?php
$this->session = new Zend_Session_Namespace('MyClientPortal');
$isSignedIn = $this->session->isSignedIn;
if($isSignedIn==1){
?>
<!-- Change Password -->
<div id="change_pwd_cont" class="" style="display:none;">
	<div class="register-form containerbox">
		<p>GetLinc is the Leading online shopping website in india</p>
		<div class="register-part">
			<form name="change_pwd_form" id="change_pwd_form">
			<div class="row">
				<label>Old Password<span class="error_class">*</span></label>
				<input type="password" name="old_pwd" id="old_pwd"/>				
			</div>
			<div class="row">
				<label>New Password<span class="error_class">*</span></label>
				<input type="password" name="new_pwd" id="new_pwd"/>				
			</div>
			<div class="row">
				<label>Confirm Password<span class="error_class">*</span></label>
				<input type="password" name="cnf_pwd" id="cnf_pwd"/>				
			</div>
			<div class="btn-container"><input type="submit" id="change_pwd_submit" name="change_pwd_submit" value="Change"></div>
			</form>
			<div id="for_loading" style="display:none;"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" /></div>
		</div>
		<div class="clear"></div>
	</div>
</div>
<!-- end Change Password-->
<?php }?>