<div id="footer-links">
		<div class="wrapper">
			<div class="block" id="newsletter">
				<h5>Newsletter Signup</h5>
				<div class="container">
					<p>Sign up to receive special offers and the latest style news.</p>
					<form>
						<input type="text" value="Your e-mail address" />
						<div class="clear">
							<input type="submit" value="For Men" />
							<input type="submit" value="For Women" />
						</div>
					</form>
					<p>Sign up to receive special offers and the latest style news.</p>
				</div>
			</div>
			<div class="blocks">
				<div class="block">
					<h5>Service</h5>
					<ul>
						<li><a href="javascript:void(0)" class="subitems"/>About</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Contact</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Terms and Conditions</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Privacy Policy</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Affiliate Programme</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Corporate Gifting</a></li>
					</ul>
				</div>
				<div class="block">
					<h5>Our Policies</h5>
					<ul>
						<li><a href="javascript:void(0)" class="subitems"/>Cancellations and Returns</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Shipping</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Payments</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Ordering and Tracking</a></li>
					</ul>
				</div>
				<div class="block">
					<h5>Join us on</h5>
					<ul>
						<li><a href="javascript:void(0)" class="subitems"/>Facebook</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Twitter</a></li>
						<li><a href="javascript:void(0)" class="subitems"/>Google</a></li>
					</ul>
				</div>
				<div class="block">
					<h5>Payment Methods</h5>
					<div class="payment-methods"></div>
					<h5>Shipping Partner</h5>
					<div class="shipping-methods"></div>
				</div>
				<div class="clear"></div>
			</div>
			
		</div>
	</div>
	<div id="footer">
		<div class="wrapper">
			<a href="javacript:void(0)">Conditions of Use</a>
			<a href="javacript:void(0)">Privacy Notice</a>
			<a href="javacript:void(0)">Interest-Based Ads</a>
			<span>&copy; 1996-2013 GetLinc.com, Inc. or its affiliates</span>
		</div>
	</div>