<!-- Register -->
<div id="register_cont" class="" style="display:none;">
	<div class="register-form containerbox">
	
		<p>GetLinc is the Leading online shopping website in india</p>
		<div class="header">
			<a href="javascript:void(0)" id="fb_login" ></a>
			<a href="javascript:void(0)" id="google_login" ></a>
			<div class="clear"></div>
		</div>
		<div class="or"></div>
		<div class="register-part">
			<div class="row">
				<label>Email Id</label>
				<input type="text"/>
			</div>
			<div class="row">
				<div class="left width-50">
					<label>First Name</label>
					<input type="text"/>
				</div>
				<div class="right width-50">
					<label>Last Name</label>
					<input type="text"/>
				</div>
			</div>
			<div class="row">
				<label>Password</label>
				<input type="text"/>
			</div>
			<div class="row">
				<label>Mobile</label>
				<input type="text"/>
			</div>
			<div class="row radio">
				<label>Gender</label>
				<span><input type="radio"/> Male</span><span><input type="radio"/> Female</span>
			</div>
			<div class="agree">
				<input type="checkbox" />I agree to <a href="javascript:void(0)">Terms & Privacy Policy </a>of use page
			</div>
			<div class="btn-container"><input type="submit" value="Register"></div>
		</div>
		<div class="login-part">
			<div class="row"><label>Email Id</label><input type="text"/></div>
			<div class="row"><label>Email Id</label><input type="text"/></div>
			<div class="btn-container"><input type="submit" value="Login"></div>
		</div>
		
		<div class="clear"></div>
	</div>
</div>
<!-- end register-->