<!-- Register -->
<div id="register_cont" class="" style="display:none;">
	<div class="register-form containerbox">
		<p>GetLinc is the Leading online shopping website in india</p>
		<div class="header">
			<a href="javascript:void(0)" id="fb_login" ></a>
			<a href="javascript:void(0)" id="google_login" ></a>
			<div class="clear"></div>
		</div>
		<div class="or"></div>
		<div class="register-part">
			<form name="registration" id="registration">
			<div class="row">
				<label>Email Id<span>*</span></label>
				<input type="text" name="email_id" id="email_id"/>
				<label>dsdadasdsa</label>
			</div>
			<div class="row">
				<div class="left width-50">
					<label>First Name<span>*</span></label>
					<input type="text" name="first_name" id="first_name"/>
				</div>
				<div class="right width-50">
					<label>Last Name<span>*</span></label>
					<input type="text" name="last_name" id="last_name"/>
				</div>
			</div>
			<div class="row">
				<label>Password<span>*</span></label>
				<input type="password" name="password" id="password"/>
			</div>
			<div class="row">
				<label>Mobile<span>*</span></label>
				<input type="text" name="mobile" id="mobile"/>
			</div>
			<div class="row radio">
				<label>Gender</label>
				<span><input type="radio" checked="checked" name="gender" value="Male"/> Male</span><span><input type="radio" name="gender" value="Female"/> Female</span>
			</div>
			<div class="agree">
				<input style="float:left" type="checkbox" name="term_conditions" id="term_conditions"/><div style="width:97%">I agree to <a href="javascript:void(0)">Terms & Privacy Policy </a>of use page</div>
			</div>
			<div class="btn-container"><input type="submit" id="reg_submit" name="reg_submit" value="Register"></div>
			</form>
		</div>
		<div class="login-part">
			<form name="login_user" id="login_user">
			<div class="row"><label>Email Id</label><input type="text" id="email_id" name="email_id" /></div>
			<div class="row"><label>Password</label><input type="text" id="password" name="password"/></div>
			<div class="btn-container"><input type="submit" id="sbt_login" name="sbt_login" value="Login"></div>
			</form>
		</div>
		
		<div class="clear"></div>
	</div>
</div>
<!-- end register-->