<div class="main_body">
					<div class="left width-100">
						<div class="breadcrumbs">
							<span class="home-icon"></span><a href="javascript:void(0)" class="home">home</a><span class="arrow"></span><a href="javascript:void(0)" class="events">Events</a>
							<div class="clear"></div>
						</div>
						<div id="events_page">
							<div class="header_events">
								<h2>Edit Events</h2>
								<a id="save-event" href="javascript:void(0)" class="button-grey add right"><span><span>Cancel</span></span></a>
								<a id="save-event" href="javascript:void(0)" class="button-dark add right"><span><span>Save & New</span></span></a>
								<a id="save-event" href="javascript:void(0)" class="button-dark add right"><span><span>Save</span></span></a>
								<div class="clear"></div>
							</div>
							<div class="event-form">
								<form>
									<div class="heading">
										<h3>Basic Information</h3><span class="required">Required Information</span>
										<div class="clear"></div>
									</div>
									<div class="row left width-50 half">
										<label class="required">Event Name :</label>
										<input type="text"/>
										<div class="clear"></div>
									</div>
									<div class="row left width-50 half">
										<label>Event Venue :</label>
										<input type="text"/>
										<div class="clear"></div>
									</div>
									<div class="row left width-50 half">
										<label>Event Address :</label>
										<input type="text"/>
										<div class="clear"></div>
									</div>
									<div class="row left width-50 half">
										<label>Phone :</label>
										<input type="text"/>
										<div class="clear"></div>
									</div>	
									<div class="row left width-50 half date">
										<label class="required">Start Date :</label>
										<input type="text"/><select><option>12:00PM</option></select>
										<div class="clear"></div>
									</div>
									<div class="row left width-50 half date">
										<label class="required">End Date :</label>
										<input type="text"/><select><option>12:00PM</option></select>
										<div class="clear"></div>
									</div>	
									<div class="clear"></div>
									<div class="row chekbox">
										<input type="checkbox"/><label>Make Event As All Day Event</label>
										<div class="clear"></div>
									</div>
									<div class="row">
										<label>Event Link :</label>
										<input type="text"/>
										<div class="clear"></div>
									</div>
									<div class="row">
										<label>Invitees :</label>
										<input type="text"/>
										<span class="info">(please enter email ids)</span>
										<div class="clear"></div>
									</div>
									<div class="row">
										<label>Description :</label>
										<textarea rows="6"></textarea>
										<div class="clear"></div>
									</div>
									<div class="clear"></div>
									<div class="row left width-50 half">
										<label>Event Logo :</label>
										<input type="file"/>
										<div class="clear"></div>
									</div>
									<div class="row left width-50 half">
										<label>Calendar Group :</label>
										<select><option>-- Calendar Group --</option></select>
										<div class="clear"></div>
									</div>	
									<div class="clear"></div>
									<div class="heading">
										<h3>Recurrence</h3>
										<div class="clear"></div>
									</div>
									<div class="row chekbox">
										<input type="checkbox"/><label>Create Recurring Series of Events</label>
										<div class="clear"></div>
									</div>
									<div class="row">
										<label>Reminders : </label>
										<div class="fields-container">
											<div class="row"><select style="width: 12%;"><option>Email</option></select><label>Every</label><input size="2" type="text"/><select style="width: 13%;"><option>Minutes</option></select><input style="margin-top: 7px;" type="checkbox"/><label>Send this notification to everyone on this event.</label><div class="clear"></div></div>
											<div class="row"><select style="width: 12%;"><option>Pop up</option></select><label>Every</label><input size="2" type="text"/><select style="width: 13%;"><option>Minutes</option></select><input style="margin-top: 7px;" type="checkbox"/><label>Send this notification to everyone on this event.</label><div class="clear"></div></div>
										</div>
										<div class="clear"></div>
									</div>
									<div class="heading">
										<h3>Attachments</h3>
										<div class="clear"></div>
									</div>
									<div class="row left width-50 half">
										<label>Event Logo :</label>
										<input type="file"/>
										<span class="info">(Should upload less than 2MB)</span>
										<div class="clear"></div>
									</div>
									<div class="clear">
										<a id="save-event" href="javascript:void(0)" class="button-grey add right"><span><span>Cancel</span></span></a>
										<a id="save-event" href="javascript:void(0)" class="button-dark add right"><span><span>Save & New</span></span></a>
										<a id="save-event" href="javascript:void(0)" class="button-dark add right"><span><span>Save</span></span></a>
									</div>
								</form>
								<div class="clear">&nbsp;</div>
							</div>
						</div>
						<div class="clear"></div>
					</div>
<div class="clear"></div>
</div>