<div class="calendar">
<h2 class="success_message hidden"></h2>
<h2 class="error_message hidden"></h2>
<div id="calendar">

<div id="example-two">
			<div onclick="$('#example-two').hide();" class="popup_cls"></div>
	 	   
    		
    		<div class="list-wrap">
    		
                 <div class="tabusual" style="display: block;" id="Event">
          			<form name="edit_small_event_form" id="edit_small_event_form" action="" method="post" enctype="multipart/form-data">
                    <div class="task-edit-form">
                        <div class="divlabel"><label>Event Date</label><span>:</span> <label class="daylabel date_contianer"></label> <div class="clear"></div> </div>
                        <div class="divlabel" style="margin:0;"><label>Event Title</label><span>:</span> <input name="event_title" id="event_title" type="text" /> <div class="clear"></div> <span class="error_event_title hidden"></span></div>
                        <div class="divlabel"><small>e.g., 7pm Meeting with client.</small></label> <div class="clear"></div> </div>
                        <input type="hidden" name="start_date" id="start_date" value="">
						<input type="hidden" name="start_time" id="start_time" value="">
						<input type="hidden" name="end_date" id="end_date" value="">
						<input type="hidden" name="end_time" id="end_time" value="">
						<input type="hidden" name="allDay" id="allDay" value="">
						<input name="" type="button" value="Create Event" class="small_form_btn" />
                        <a href="javascript:void(0);" class="edit_event_link">Edit Event >></a>
                      <div class="clear"></div>
                      <div class="arrowdwn1"></div>  
                    </div>
          			</form>
          		 </div>
          	
                 
        		 
    		 </div> 
    		<!-- END List Wrap --></div>
</div>
</div>



<div class="event_pop appoint-popup  pop_up hidden" >
  <h3 class="apnt-popup"> <span class="event_title" ></span><a href="#" class="close_pop close_xbtn">&#120;</a></h3>
  <input type="hidden" name="event_id" value="" id="event_id"/>
  <div class="event_date_label"></div>
  <div class="clear"></div>
  <a href="javascript:void(0);" class="delete-editBtn" id="event_delete_small" onclick="deleteEvent();">Delete</a> <a href="javascript:void(0);" class="delete-editBtn editrht" onclick="editEvent();">Edit</a> </div>

<!-- popup for events / tasks starts --> 

<div id="event_form" style="display:none;">
			<div class="main_body">
					<div class="left width-100">
						<div id="events_page">
							<div class="header_events">
								<h2>Create Event </h2>
								<a id="cancel_event_one" href="javascript:void(0)" class="button-grey add right" onclick="dialoge_close();"><span><span>Cancel</span></span></a>
								<a id="save_event_one" href="javascript:void(0)" class="button-dark add right" onclick="$('#event_form_body').submit();"><span><span>Save</span></span></a>
								<div class="clear"></div>
							</div>
							<div class="event-form">
								<form name="event_form_body" id="event_form_body" action="" method="post" enctype="multipart/form-data">
								<input type="hidden" id="submit_check" name="submit_check" value="1">
								<input type="hidden" id="event_id_check" name="event_id_check">
									<div class="heading">
										<h3>Basic Information </h3><span class="required">Required Information</span>
										<div class="clear"></div>
									</div>
									<div class="row left width-50 half">
										<label class="required">Event Name :</label>
										<input type="text" name="event_name" id="event_name" class="required" value="" />
										<div class="clear"></div>
									</div>
									<div class="row left width-50 half">
										<label>Event Venue :</label>
										<input type="text" name="event_venue" id="event_venue" value="" />
										<div class="clear"></div>
									</div>
									<div class="clear"></div>
									<div class="row left width-50 half">
										<label>Event Address :</label>
										<input type="text" name="event_address" id="event_address" value="" />
										<div class="clear"></div>
									</div>
									<div class="row left width-50 half">
										<label>Type :</label>
										<select name="event_type" id="event_type"><option value="">Select</option><option value="public">Public</option><option value="private">Private</option></select>
										<div class="clear"></div>
									</div>	
									<div class="clear"></div>
									<div class="row left width-50 half date">
										<label class="required">Start Date :</label>
										<input type="text" name="event_start_date" id="event_start_date" value="" class="datepicker required"/><input id="event_start_time" name="event_start_time" type="text" class="time" />
										<div class="clear"></div>
									</div>
									<div class="row left width-50 half date">
										<label class="required">End Date :</label>
										<input type="text" name="event_end_date" id="event_end_date" value="" class="datepicker required"/><input id="event_end_time" name="event_end_time" type="text" class="time" />
										<div class="clear"></div>
									</div>	
									<div class="clear"></div>
									<div class="error_div"></div>
									<div class="clear"></div>
									<div class="row chekbox">
										<input type="checkbox" name="allday" id="allday" value="1"/><label>Make Event As All Day Event</label>
										<div class="clear"></div>
									</div>
									<!--<div class="row">
										<label>Event Link :</label>
										<input type="text"/>
										<div class="clear"></div>
									</div>
									<div class="row">
										<label>Invitees :</label>
										<input type="text"/>
										<span class="info">(please enter email ids)</span>
										<div class="clear"></div>
									</div>-->
									<div class="row">
										<label>Description :</label>
										<textarea rows="6" name="event_description" id="event_description"></textarea>
										<div class="clear"></div>
									</div>
									<div class="clear"></div>
									<!--<div class="row left width-50 half">
										<label>Event Logo :</label>
										<input type="file"/>
										<div class="clear"></div>
									</div>
									<div class="row left width-50 half">
										<label>Calendar Group :</label>
										<select><option>-- Calendar Group --</option></select>
										<div class="clear"></div>
									</div>	-->
									<div class="clear"></div>
									
									<div class="heading">
										<h3>Attachments</h3>
										<div class="clear"></div>
									</div>
									<div class="row left width-50 half">
										<label>Event Logo :</label>
										<input type="file" name="event_logo" id="event_logo"/>
										<span class="info">(Should upload less than 2MB)</span>
										<div class="clear"></div>
									</div>
									<div class="clear">
										<a id="cancel_event_two" href="javascript:void(0)" class="button-grey add right" onclick="dialoge_close();"><span><span>Cancel</span></span></a>
										<a id="save_event_two" href="javascript:void(0)" class="button-dark add right" onclick="$('#event_form_body').submit();"><span><span>Save</span></span></a>
									</div>
								</form>
								<div class="clear">&nbsp;</div>
							</div>
						</div>
						<div class="clear"></div>
					</div>
<div class="clear"></div>
</div>
</div>