<div class="main_body">
<div class="left width-100">
						<div class="breadcrumbs">
							<span class="home-icon"></span><a href="javascript:void(0)" class="home">home</a><span class="arrow"></span><a href="javascript:void(0)" class="events">Events</a>
							<div class="clear"></div>
						</div>
						<div id="events_page">
							<div class="header_events">
								<h2>Events</h2>
								<a id="add-event" href="javascript:void(0)" class="button-dark icon add"><span><span>+ New Event</span></span></a>
								<div class="event_search">
									<input type="text" placeholder="Event Name | Event Venue | Owner"/>
									<input type="submit" value="go"/>
								</div>
								<div class="clear"></div>
							</div>
							<div class="grid-view">
								<div class="grid-view-heading left">
									<a href="javascript:void(0)" class="button-light icon delete"><span><span>Delete</span></span></a>
									<a href="javascript:void(0)" class="button-light icon share"><span><span>Share</span></span></a>
									<a href="javascript:void(0)" class="button-light icon export"><span><span>Export</span></span></a>
									<a href="javascript:void(0)" class="button-light icon import"><span><span>Import</span></span></a>
									<a href="javascript:void(0)" class="button-light icon archive"><span><span>Archive</span></span></a>	
									<a href="javascript:void(0)" class="button-light icon tags"><span><span>Tags</span></span></a>	
								</div>
								<div class="right">
									<select>
										<option>Select</option>
									</select>
								</div>
								<div class="clear"></div>
								<table cellpadding="0" cellspacing="0" width="100%">
									<thead>
										<tr>
											<th width='30'><input type="checkbox"/></th>
											<th >Event Name</th>
											<th  width='100'>Start Date</th>
											<th  width='100'>End Date</th>
											<th  width='100'>Owner</th>
											<th  width='30'>Flag</th>
										</tr>
									</thead>
									<tbody>
										<tr class="odd">
											<td><input type="checkbox"/></td>
											<td>Birth Day</td>
											<td>08/10/2013</td>
											<td>08/10/2013</td>
											<td>GUNNAM CHOWD</td>
											<td><img src="<?php echo $this->baseUrl('public/default'); ?>/images/flag.png"/></td>
										</tr>
										<tr class="even">
											<td><input type="checkbox"/></td>
											<td>Birth Day</td>
											<td>08/10/2013</td>
											<td>08/10/2013</td>
											<td>GUNNAM CHOWD</td>
											<td><img src="<?php echo $this->baseUrl('public/default'); ?>/images/flag.png"/></td>
										</tr>
										<tr class="odd">
											<td><input type="checkbox"/></td>
											<td>Birth Day</td>
											<td>08/10/2013</td>
											<td>08/10/2013</td>
											<td>GUNNAM CHOWD</td>
											<td><img src="<?php echo $this->baseUrl('public/default'); ?>/images/flag.png"/></td>
										</tr>
										<tr class="even">
											<td><input type="checkbox"/></td>
											<td>Birth Day</td>
											<td>08/10/2013</td>
											<td>08/10/2013</td>
											<td>GUNNAM CHOWD</td>
											<td><img src="<?php echo $this->baseUrl('public/default'); ?>/images/flag.png"/></td>
										</tr>
										<tr class="odd">
											<td><input type="checkbox"/></td>
											<td>Birth Day</td>
											<td>08/10/2013</td>
											<td>08/10/2013</td>
											<td>GUNNAM CHOWD</td>
											<td><img src="<?php echo $this->baseUrl('public/default'); ?>/images/flag.png"/></td>
										</tr>
										<tr class="even">
											<td><input type="checkbox"/></td>
											<td>Birth Day</td>
											<td>08/10/2013</td>
											<td>08/10/2013</td>
											<td>GUNNAM CHOWD</td>
											<td><img src="<?php echo $this->baseUrl('public/default'); ?>/images/flag.png"/></td>
										</tr><tr class="odd">
											<td><input type="checkbox"/></td>
											<td>Birth Day</td>
											<td>08/10/2013</td>
											<td>08/10/2013</td>
											<td>GUNNAM CHOWD</td>
											<td><img src="<?php echo $this->baseUrl('public/default'); ?>/images/flag.png"/></td>
										</tr>
										<tr class="even">
											<td><input type="checkbox"/></td>
											<td>Birth Day</td>
											<td>08/10/2013</td>
											<td>08/10/2013</td>
											<td>GUNNAM CHOWD</td>
											<td><img src="<?php echo $this->baseUrl('public/default'); ?>/images/flag.png"/></td>
										</tr>
									</tbody>
								</table>
								<div class="grid-view-footer">
										<a  href="javascript:void(0)" class="left button-light no-text icon refresh"><span><span>Refresh</span></span></a>
										<span class="right">View 1-10 of 20</span>
										<div class="pagention text-center">
											<a  href="javascript:void(0)" class="button-light icon First"><span><span>First</span></span></a>
											<a  href="javascript:void(0)" class="button-light icon prev"><span><span>Prev</span></span></a>
											<span class="info">Page 1 of 2</span>
											<a  href="javascript:void(0)" class="button-light icon next"><span><span>Next</span></span></a>
											<a  href="javascript:void(0)" class="button-light icon last"><span><span>last</span></span></a>
											<select>
												<option>1</option>
												<option>2</option>
											</select>
										</div>
										<div class="clear"></div>
								</div>
							</div>
						</div>
						<div class="clear"></div>
					</div>
<div class="clear"></div>
</div>