<div class="main_body">
					<div class="left width-100">
						<div class="breadcrumbs">
							<span class="home-icon"></span><a href="javascript:void(0)" class="home">home</a><span class="arrow"></span><a href="javascript:void(0)" class="events">Events</a>
							<div class="clear"></div>
						</div>
						<div id="events_page">
							<div class="header_events">
								<h2>Event Details</h2>
								<a href="javascript:void(0)" class="button-grey add right"><span><span>Events List</span></span></a>
								<a  href="javascript:void(0)" class="button-dark add right"><span><span>Edit Event</span></span></a>
								<div class="clear"></div>
							</div>
							<div class="event-detail_block">
								<div class="main_event_details">
									<div class="event_image">
										<img src="<?php echo $this->baseUrl('public/default'); ?>/images/eventImae.jpg" />
									</div>
									<div class="event_detail">
										<div class="period_date">
											<label>Start Date:</label><span>08/10/2013</span>
											<label>End Date:</label><span>08/10/2013</span>
										</div>
										<h3>Birth day</h3>
									</div>
									<div class="clear"></div>
								</div>
								<div class="info">
									<div class="row">
										<div class="left width-50">
											<label>Event Address</label>
											<span>N/A</span>
										</div>
										<div class="left width-50">
											<label>Phone</label>
											<span>N/A</span>
										</div>
										<div class="clear"></div>
									</div>
									<div class="row">
										<div class="">
											<label>Invitees</label>
											<span>N/A</span>
										</div>
									</div>
									<div class="row">
										<div>
											<label>Description</label>
											<span>N/A</span>
										</div>
									</div>
									<div class="row">
										<div class="left width-50">
											<label>Recurrence</label>
											<span>N/A</span>
										</div>
										<div class="left width-50">
											<label>Reminder</label>
											<span>N/A</span>
										</div>
										<div class="clear"></div>
									</div>
									<div class="row">
										<div class="">
											<label>Tags</label>
											<span>N/A</span>
										</div>
									</div>
									<div class="row">
										<div>
											<label>Attachments</label>
											<span>N/A</span>
										</div>
									</div>
								</div>
								<div class="clear"></div>
							</div>
						</div>
						<div class="clear"></div>
					</div>
<div class="clear"></div>
</div>