<?php
	$session = new Zend_Session_Namespace('MyPortal');
	$error = $this;	
?>


<?php if($error->error != '') {?>
	<div class="alert alert-error">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<strong>Error! </strong> <?php echo $error->error;?>
	</div>		
<?php $error->error = '';
	} else if(isset($session->success) && $session->success != '') {?>
		<div class="alert alert-success">
			<button type="button" class="close" data-dismiss="alert">×</button>
			<strong>Success! </strong> <?php echo $session->success;?>
		</div>
		<?php $session->success = '';
	} 
?>



<div class="row-fluid sortable">
	<div class="box span12">
		<div class="box-header well" data-original-title>
			<h2><i class="icon-edit"></i> My Account</h2>			
		</div>
		<div class="box-content">			
			<form class="form-horizontal" id="signupform" autocomplete="off" method="post" action="">
			  <fieldset>
				<legend>Edit Personal Information</legend>
				<div class="control-group">
				  <label class="control-label" for="typeahead">Old Password</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">
					<input class="field" tabindex="1" id="old_password" name="old_password" type="password" value="" maxlength="16" size="40" title=""/>
					</div>
					   <div class="error_message">
					   <?php 
						if($error->error_changepassword_old != '') {
							echo '<label class="error">' .$error->error_changepassword_old . '</label>';
							$error->error_changepassword_old = '';
						}
					   ?>
					   </div>
					   					   
				  </div>
				</div>
				
				<div class="control-group">
				  <label class="control-label" for="typeahead">New Password</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">
					<input class="field" tabindex="2" id="new_password" name="new_password" type="password" value="" maxlength="16" size="40" title=""/>
					</div>
					<div class="error_message">
					   <?php 
						if($error->error_changepassword_new != '') {
							echo '<label class="error">' .$error->error_changepassword_new . '</label>';
							$error->error_changepassword_new = '';
						}
					   ?>
					   </div>
					   
				  </div>
				</div>
				
				<div class="control-group">
				  <label class="control-label" for="typeahead">Re-enter&nbsp;New&nbsp;Password</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">
					<input class="field" id="confirm_password" name="confirm_password" type="password" value="" maxlength="16" size="40" tabindex="3" title=""/>
					</div>
					<div class="error_message">
					   <?php 
						if($error->error_changepassword_conf != '') {
							echo '<label class="error">' .$error->error_changepassword_conf . '</label>';
							$error->error_changepassword_conf = '';
						}
					   ?>
					   </div>
					   
				  </div>
				</div>				
							
       
				<div class="form-actions">				  
				  <input name="signup" type="submit" class="btn btn-primary" value="Save" tabindex="4" title="" />
				</div>
			  </fieldset>
			</form>   

		</div>
	</div><!--/span-->

</div>




<script type="text/javascript">
jQuery(document).ready(function() {
// validate signup form on keyup and submit
	validatePassword();
});
</script>
  