<?php
$session = new Zend_Session_Namespace('MyPortal');
//$error = new Zend_Session_Namespace('MyPortalerror');
$error = $this;
?>
<div class="row-fluid">
	<div class="well span5 center login-box" style="width:700px;">	
    
<div class="top-content">
<p class="running-text">Please change your password for security reasons</p>
<p class="running-text"><span class="req">* </span>Required Fields</p>

</div>

<div class="bott-content"><!--BO bott-content -->

<div class="ForPwdForm_wrapper-forcechpwd"><!--BO ForPwdForm_wrapper -->
 <table style="margin-left:auto; margin-right:auto" align="center" width="98%"><tr> <td height="14" align="center"><div align="center">
	 <?php    
				if($error->error != '') {
					echo '<div style="color: #D82A32; font-size: 14px;"><label  id="error" style="color: #D82A32; font-size: 13px;">' . $error->error . '</label></div>';
					$error->error = '';
				} 
			?>
	</div></td> </tr></table>

  <div class="ForSecQuest-forcechpwd"><!--BO ForPwdForm-div -->
<form id="signupform" autocomplete="off" method="post" action="<?php //echo $this->baseUrl('usermanagement/index/savefirst');?>" style="width:700px;">
<div class="empty-10"></div>



			<div class="control-group">				  
				<div class="controls">   
					<div class="mid_Control-profile float-left" style="float:left;">	   
					<div style="width:200px; float:left; text-align:right;">Temporary Password : <span class="req">*</span></div>&nbsp;
					<input class="field" tabindex="1" id="oldpwd" name="oldpwd" type="password" value="" maxlength="16" size="40" title=""/>
					</div>
				
						<div class="error_message">
						<?php 
						if($error->error_firstlogin_old != '') {
						echo '<label class="error" >' .$error->error_firstlogin_old . '</label>';
						$error->error_firstlogin_old = '';
						}
						?>
						</div>
			</div>
			</div>
			<div class="clearfix"></div>
			
			
			
			<div class="control-group">				  
				<div class="controls">   
					<div class="mid_Control-profile float-left" style="float:left;">
					<div style="width:200px; float:left; text-align:right;">New password : <span class="req">*</span></div>&nbsp;
					<input class="field" tabindex="2" id="newpwd" name="newpwd" type="password" value="" maxlength="16" size="40" title=""/>
					</div>
				
						<div class="error_message">
						<?php 
						if($error->error_firstlogin_new != '') {
						echo '<label class="error" style="width:300px;line-height:1.2em;*line-height:0em">' .$error->error_firstlogin_new . '</label>';
						$error->error_firstlogin_new = '';
						}
						?>
						</div>
			</div>
			</div>
			<div class="clearfix"></div>
			
			
			
			
			<div class="control-group">				  
				<div class="controls">   
					<div class="mid_Control-profile float-left" style="float:left;">
					<div style="width:200px; float:left; text-align:right;">Re-enter New Password : <span class="req">*</span></div>&nbsp;
					<input class="field" tabindex="3" id="retypepwd" name="retypepwd" type="password" value="" maxlength="16" size="40" title=""/>
					</div>
				
						<div class="error_message">
						<?php 
						if($error->error_firstlogin_conf != '') {
						echo '<label class="error" style="width:300px;line-height:1.2em;*line-height:0em">' .$error->error_firstlogin_conf . '</label>';
						$error->error_firstlogin_conf = '';
						}
						?>
						</div>
			</div>
			</div>
			<div class="clearfix"></div>
			
			
			
			
			
			<div class="control-group">				  
				<div class="controls">   
					<div class="mid_Control-profile float-left" style="float:left;">
					<!-- Note : Security question can take max of 60 characters only -->    
					<div style="width:200px; float:left; text-align:right;">Challenge Question : <span class="req">*</span></div>&nbsp;
					<input class="field" tabindex="4" id="squestion" name="squestion" type="text" value="<?php if(is_array($error->error_firstlogin_values)) { echo $error->error_firstlogin_values['squestion'];}?>" maxlength="60" size="40" title=""/>
					</div>
				
						<div class="error_message">
						<?php 
						if($error->error_firstlogin_ques != '') {
						echo '<label class="error">' .$error->error_firstlogin_ques . '</label>';
						$error->error_firstlogin_ques = '';
						}
						?>
						</div>

			</div>
			</div>
			<div class="clearfix"></div>
     
           
			<div class="control-group">				  
				<div class="controls">   
					<div class="mid_Control-profile float-left" style="float:left;">
					<div style="width:200px; float:left; text-align:right;">Secret Answer : <span class="req">*</span></div>&nbsp;
					<input class="field" tabindex="5" id="sanswer" name="sanswer" type="text" value="" maxlength="30" size="40" title=""/>
					</div>
				
						<div class="error_message">
						<?php 
						if($error->error_firstlogin_answer != '') {
						echo '<label class="error">' .$error->error_firstlogin_answer . '</label>';
						$error->error_firstlogin_answer = '';
						}
						?>
						</div>
			</div>
			</div>
			<div class="clearfix"></div>
			
			
			
			
			<div class="control-group">				  
				<div class="controls">   
					<div class="mid_Control-profile float-left" style="float:left;">
					<div style="width:200px; float:left; text-align:right;">Re-enter Secret Answer : <span class="req">*</span></div>&nbsp;
					<input class="field" tabindex="6" id="retypesans" name="retypesans" type="text" value="" maxlength="30" size="40" title=""/>
					</div>
				
						<div class="error_message">
						<?php 
						if($error->error_firstlogin_sec != '') {
						echo '<label class="error">' .$error->error_firstlogin_sec . '</label>';
						$error->error_firstlogin_sec = '';
						}
						$error->error_firstlogin_values = '';
						?>
						</div>

			</div>
			</div>
			<div class="clearfix"></div>
	 
	     
			<div class="clearfix"></div>
			<p class="center span5">			
			<input id="signupsubmit" name="signup" type="submit" class="btn btn-primary" value="Submit" tabindex="4" align="left" title="" style="width:100px; float:left;" />
			</p>

     </form>
     <div class="clr"></div>
<div class="empty-10"></div>

      </div><!--EO  ForPwdForm-div-->

</div><!--EO  ForPwdForm_wrapper-->

</div><!--EO bott-content -->
<div class="top-content">

<p class="running-text"><b>Follow these guidelines to create a secure password:</b></p>

<p style="padding-top:2px;" class="running-text"><span class="req">&rsaquo;&rsaquo;</span> Password should be between 8 and 16 characters in length. </p>
<p style="padding-top:2px;" class="running-text"><span class="req">&rsaquo;&rsaquo;</span> Must contain minimum one number and one uppercase letter.  </p>
<p style="padding-top:2px;" class="running-text"><span class="req">&rsaquo;&rsaquo;</span> No special characters allowed.  </p>
<div class="empty-10"></div>
</div>
<div class="clr"></div><!--inportant -->

    </div></div>
  
   <script type="text/javascript">

jQuery(document).ready(function() {
/*for autofocus on first field*/
// validate signup form on keyup and submit
	validatefirstlogin();


});

</script>