<?php 
	$session = new Zend_Session_Namespace('MyPortal');
	//$error = new Zend_Session_Namespace('MyPortalerror');
	$error = $this;
?>


<?php if($session->success != '') {?>
<div class="alert alert-success">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<strong>Success! </strong> <?php echo $session->success;?>
</div>
<?php $session->success = ''; }?>


<div class="row-fluid sortable">
	<div class="box span12">
		<div class="box-header well" data-original-title>
			<h2><i class="icon-edit"></i> My Account</h2>			
		</div>
		<div class="box-content">			
			<form class="form-horizontal" id="signupform" autocomplete="off" method="post" action="">
			  <fieldset>
				<legend>Edit Personal Information</legend>
				<div class="control-group">
				  <label class="control-label" for="typeahead">First Name</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">
					<input class="input-xlarge focused" tabindex="1" id="firstname" name="firstname" type="text" value="<?php if(is_array($error->error_personalinfo_values)) { echo $error->error_personalinfo_values['firstname'];} else {echo $this->firstname;}?>" maxlength="20" size="40" title=""/>
					</div>
					   <div class="error_message">
					   <?php 
						if($error->error_personalinfo_firstname != '') {
							echo '<label class="error">' .$error->error_personalinfo_firstname . '</label>';
							$error->error_personalinfo_firstname = '';
						}
					   ?>
					   </div>
					   					   
				  </div>
				</div>
				
				<div class="control-group">
				  <label class="control-label" for="typeahead">Last Name</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">
					<input class="input-xlarge focused" tabindex="2" id="lastname" name="lastname" type="text" value="<?php if(is_array($error->error_personalinfo_values)) { echo $error->error_personalinfo_values['lastname'];} else {echo $this->lastname;}?>" maxlength="20" size="40" title=""/>
					</div>
					<div class="error_message">
					   <?php 
						if($error->error_personalinfo_lastname != '') {
							echo '<label class="error">' .$error->error_personalinfo_lastname . '</label>';
							$error->error_personalinfo_lastname = '';
						}
					   ?>
					   </div>
					   
				  </div>
				</div>
				
				<div class="control-group">
				  <label class="control-label" for="typeahead">Email Address</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">
					<input class="input-xlarge focused" tabindex="3" id="useremail" name="useremail" type="text" value="<?php if(is_array($error->error_personalinfo_values)) { echo $error->error_personalinfo_values['useremail'];} else {echo $this->username;}?>" maxlength="50" size="40" title=""/>
					</div>
					<div class="error_message">
					   <?php 
						if($error->error_personalinfo_email != '') {
							echo '<label class="error">' .$error->error_personalinfo_email . '</label>';
							$error->error_personalinfo_email = '';
						}
					   ?>
					   </div>
					   
				  </div>
				</div>
				
				<div class="control-group">
				  <label class="control-label" for="typeahead">Contact Number</label>
				  <div class="controls">
					<div class="mid_Control-profile float-left">
					<input class="input-xlarge focused" tabindex="4" id="phonenumber" name="phonenumber" type="text" value="<?php if(is_array($error->error_personalinfo_values)) { echo $error->error_personalinfo_values['phonenumber'];} else {echo $this->phonenumber;}?>" maxlength="10" size="40" title=""/>
					</div>
					<div class="error_message">
					   <?php 
						if($error->error_personalinfo_phonenumber != '') {
							echo '<label class="error">' .$error->error_personalinfo_phonenumber . '</label>';
							$error->error_personalinfo_phonenumber = '';
						}
						$error->error_personalinfo_values = '';
					   ?>
					   </div>
					   
				  </div>
				</div>
				
       
				<div class="form-actions">
				  <input id="signupsubmit" name="updatePersonalInfo" type="submit" class="btn btn-primary" value="Save" tabindex="5" title=""/>
				</div>
			  </fieldset>
			</form>   

		</div>
	</div><!--/span-->

</div>
  
<script type="text/javascript">
jQuery(document).ready(function() {
	  validatePersonal();
});
</script>