

<div style="min-height: 450px; background-color: #e5e5e5;">
<div id="alpha" class="prose" style="padding-left: 25px;">
<h2><b>Change Password</b></h2>
		    
    <div style="color:red;padding-left:150px;">
   
			<?php
				$error = new Zend_Session_Namespace('MyPortalerror');
				if($error->error != '') {
					echo $error->error;
					$error->error = '';
				}
			?>
		
    </div>
			    
			    
<form action="<?php echo $this->baseUrl('usermanagement/index/savefirst'); ?>" method="post" id="changepass" name="changepass">
<table width="736" border="0" cellpadding="3" cellspacing="3">
  <tr height="40">
    <td width="200" valign="top">    
    <div class="field">
	<label for="email">Temporary or Old Password <span style="color:#F00;">*</span></label>
	</div>    
    <input type="password" name="old_password" id="old_password" autocomplete="off" ondrop="return false" ondrag="return false" oncopy="return false" size="18" class="inputwidth" maxlength="25" />    
    <br><div id="old_password_span" style="color:red;height:2px;">&nbsp;</div><br>
    </td>
  </tr>
  <tr height="40">
    <td valign="top" class="field">
    <div class="field">
	<label for="email">New Password <span style="color:#F00;">*</span></label>
	</div>    
    <input type="password" name="new_password" id="new_password" autocomplete="off" ondrop="return false" ondrag="return false" oncopy="return false" size="18" class="inputwidth" maxlength="25"  />
    <br><div id="new_password_span" style="color:red;height:2px;">&nbsp;</div><br>
    </td>
  </tr>
  <tr height="40">
    <td valign="top">    
    <div class="field">
	<label for="email">Re-enter New Password <span style="color:#F00;">*</span></label>
	</div>
	<input type="hidden" name="useraction" value="Change Password"/>
    <input type="password" name="confirm_password" id="confirm_password" autocomplete="off" onpaste="return false" ondrop="return false" ondrag="return false" oncopy="return false" size="18" class="inputwidth" maxlength="25"  />
    <br><div id="confirm_password_span" style="color:red;height:2px;padding-bottom:5px;">&nbsp;</div><br>
    </td>
  </tr>
  <tr height="40">
    <td style="font:13px Verdana,Arial,Helvetica,sans-serif;">
    <p><b>Follow these guidelines to create a secure password:</b>
    <br>1. Password should be between 8 and 16 in length.
    <br>2. Must contain minimum one special character, one number and one uppercase letter.
    <br>3. Can't be one of your past [<?php echo $this->reusepassword;?>] passwords.
    <br>4. Password will accept only ! @ # $ * _ special characters.
    <br></p>
    </td>    
  </tr>
  <tr height="40">
    <td align="left">
    <!-- <input type="submit" name="submit" value="Create Password" onclick="return ChangeValidate(document.forms['changepass'])" />  -->    
    
    <input type="submit" name="updatepassword" value="Next >>" onclick="return ChangeValidate(document.forms['changepass'])" />
   
    </td>
  </tr>  
</table>
</form>

</div>
</div>
<script type="text/javascript">
function autofocus(){
	document.changepass.old_password.focus();
}
setTimeout("autofocus()",1000); 


 
function ChangeValidate(form){ //alert('hi');
	var Old_password = form.old_password.value;
    var New_password = form.new_password.value;
    var Confirm_password = form.confirm_password.value;
    
	
	if(Old_password == "") {
		inlineMsg1('old_password','Please enter your old password','old_password_span');
		document.changepass.old_password.focus();
	    return false;
	  }
	  
	if(Old_password.length < 2 ) {
		inlineMsg1('old_password','Invalid old password','old_password_span');
		document.changepass.old_password.focus();
	    return false;
	  }

	if(New_password == "") {
		inlineMsg1('new_password','Please enter your new password','new_password_span');
		document.changepass.new_password.focus();
	    return false;
	  }
	
	if(New_password.length < 8 ) {
		inlineMsg1('new_password','New password should be 8 - 16 characters','new_password_span');
		document.changepass.new_password.focus();
	    return false;
	  }
	  
	if(New_password.length > 16 ) {
		inlineMsg1('new_password','New password should be 8 - 16 characters','new_password_span');
		document.changepass.new_password.focus();
	    return false;
	  }
	  
	if(! New_password.match(/[A-Z]/)) {
		inlineMsg1('new_password','New password should have one uppercase character','new_password_span');
		document.changepass.new_password.focus();
	    return false;
	  }
	  
	if(! New_password.match(/[0-9]/)) {
		inlineMsg1('new_password','New password should have one number','new_password_span');
		document.changepass.new_password.focus();
	    return false;
	  }	 

	if( New_password.match(/.[",',&]/))  {
		inlineMsg1('new_password','Invalid New Password','new_password_span');
		document.changepass.new_password.focus();
	    return false;
	  }

	if(isSpclCharspassword(New_password)){
		 inlineMsg1('new_password','Invalid Password','new_password_span');
			document.changepass.new_password.focus();
		    return false;
	}
	
	 if(!isSpclCharpassword(New_password)){
		 inlineMsg1('new_password','New password should have one special character','new_password_span');
			document.changepass.new_password.focus();
		    return false;
	 }

	if(Confirm_password == "") {
		inlineMsg1('confirm_password','Please Re-type your new password','confirm_password_span');
		document.changepass.confirm_password.focus();
	    return false;
	  }	
	  
	if(New_password != Confirm_password) {
	    inlineMsg1('confirm_password','New Password & Re-type Password did not match','confirm_password_span');
	    document.changepass.confirm_password.focus();	    
	    return false;
	  }
}
</script>