<?php
$session = new Zend_Session_Namespace('MyPortal');
$error = $this;
?>




<div class="row-fluid">
	<div class="well span5 center login-box" style="width:700px;">			
			<h3>Dear User, please change your password for security reasons</h3><br>			
			<?php 
      		if($error->error != '') {
      			echo '<div class="alert alert-error" id="error1">' . $error->error . '</div>';
      			$error->error = '';
      		}
			?>			
		
		<br>
		<div class="box-content">
		<form id="signupform" name="changepass" autocomplete="off" method="post" action="<?php //echo $this->baseUrl('usermanagement/index/saveset'); ?>">
			<fieldset>							   
				<div class="control-group">				  
				  <div class="controls">
					<div class="mid_Control-profile float-left" style="float:left;">					
					<div style="width:160px; float:left; text-align:right;">Temporary Password : </div>&nbsp;
					<input class="field" tabindex="1" id="old_password" name="old_password" type="password" value="" maxlength="16" size="40" title=""/>
					</div>
					   <div class="error_message">
					   <?php 
						if($error->error_changepassword_old != '') {
							echo '<label class="error">' .$error->error_changepassword_old . '</label>';
							$error->error_changepassword_old = '';
						}
					   ?>
					   </div>
					   					   
				  </div>
				</div>
				<div class="clearfix"></div>
				
				
				<div class="control-group">				  
				  <div class="controls">
					<div class="mid_Control-profile float-left" style="float:left;">
					<div style="width:160px; float:left; text-align:right;">New password : </div>&nbsp;
					<input class="field" tabindex="2" id="new_password" name="new_password" type="password" value="" maxlength="16" size="40" title=""/>
					</div>				
					   <div class="error_message">
					   <?php 
						if($error->error_changepassword_new != '') {
							echo '<label class="error">' .$error->error_changepassword_new . '</label>';
							$error->error_changepassword_new = '';
						}
					   ?>
					   </div>
					   					   
				  </div>
				</div>
				<div class="clearfix"></div>
				
				
				<div class="control-group">				  
				  <div class="controls">
					<div class="mid_Control-profile float-left" style="float:left;">
					<div style="width:160px; float:left; text-align:right;">Re-enter New Password : </div>&nbsp;
					<input class="field" tabindex="3" id="confirm_password" name="confirm_password" type="password" value="" maxlength="16" size="40" title=""/>
					</div>				
					   <div class="error_message">
					   <?php 
						if($error->error_changepassword_conf != '') {
							echo '<label class="error">' .$error->error_changepassword_conf . '</label>';
							$error->error_changepassword_conf = '';
						}
					   ?>
					   </div>
					   					   
				  </div>
				</div>
				<div class="clearfix"></div>


				
				<div class="clearfix"></div>

				<p class="center span5">			
				<input id="signupsubmit" name="signup" type="submit" class="btn btn-primary" value="Submit" tabindex="4" align="left" title="" style="width:100px; float:left;" />
				</p>
			</fieldset>
		</form>
		
		<div class="top-content" style="text-align:left;">
		<p class="running-text"><b>Follow these guidelines to create a secure password:</b></p>
		<p style="padding-top:2px;" class="running-text"><span class="req">&rsaquo;&rsaquo;</span> Password should be between 8 and 16 characters in length. </p>
		<p style="padding-top:2px;" class="running-text"><span class="req">&rsaquo;&rsaquo;</span> Must contain minimum one number and one uppercase letter.  </p>
		<p style="padding-top:2px;" class="running-text"><span class="req">&rsaquo;&rsaquo;</span> Must not be be one of your past [<?php echo $this->reusepassword;?>] passwords.  </p>
		<p style="padding-top:2px;" class="running-text"><span class="req">&rsaquo;&rsaquo;</span> No special characters allowed.  </p>
		<div class="empty-10"></div>
		</div> 
		<div class="box-content">
	</div><!--/span-->
</div><!--/row-->


  
  
<script type="text/javascript">
jQuery(document).ready(function() {
// validate signup form on keyup and submit
	//validatePassword();
	validateTempPassword();
});
</script>