
<div class="content-wrapper"><!--BO content-wrapper -->
    <div class="form-wrapper"><!--BO form-wrapper -->
     <div class="form-layout"><!--BO form-layout -->
      
      
       <!--~~~~form-layout starts here -->
   
    <div class="login-form"><!--scipting for form -->

<div style="height: 60px;">
<?php echo $this->success;?>
</div>


</div><!--Eo scripting for form -->
    
	
    <!--Form-layout ends here -->

     </div><!--EO  form-layout-->
    <div class="empty-10"></div>
    </div><!--EO form-wrapper -->
  </div><!--EO content-wrapper -->