<?php
$session = new Zend_Session_Namespace('MyPortal');
$errorsession=new Zend_Session_Namespace("addmerchant");	
$error = $this;

$category_count = $this->category_count;
$category_list = $this->category_list;

$cn=$this->iColumnName;
$do=$this->iDisplayOrder;
if($cn==""){$cn=1;}
if($do==""){$do='DESC';}
$cn='';
?>

			<?php if($session->validateerror != '') { ?>      			
				<div class="alert alert-error" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $session->validateerror;?>
				</div>
      		<?php $session->validateerror=''; } ?>
						
			
			<?php if($session->success != '') { ?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $session->success;?>
				</div>
      		<?php $session->success = '';} ?>
			
      		<?php if($errorsession->success != '') { ?>      			
				<div class="alert alert-success" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $errorsession->success;?>
				</div>
			<?php $errorsession->success = '';} ?>
			
			<?php if($error->error != ''){ ?>      			
      			<div class="alert alert-error" id="errordisplay">
					<button type="button" class="close" data-dismiss="alert">×</button>
					<strong></strong> <?php echo $error->error;?>
				</div>
      		<?php } ?>
		

		
			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header well" data-original-title>
						<h2><i class="icon-user"></i> Categorie's</h2>
						<a href="<?php echo $this->baseUrl('admin/category/register');?>"><button class="btn btn-small" style="float:right;">Add New Category</button></a>					
					</div>
					<div class="box-content">
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th>Image</th>
								  <th>Category Title</th>
								  <th>Parent Category</th>
								  <th>Status</th>								  
								  <th>Actions</th>								  
							  </tr>
						  </thead>   
						  <tbody>
							<?php foreach($category_list as $each_category){?>
							<tr>
								<td align="center">
									<?php if($each_category['category_images']!=''){?>
									<img src="<?php echo $this->baseUrl('public/uploads/category_images');?>/<?php echo $each_category['category_images'];?>" width="50" />									
									<?php }else{?>
									<img src="<?php echo $this->baseUrl('public/uploads/category_images');?>/default.jpg" width="50" />
									<?php }?>
								</td>
								<td><?php echo $each_category['category_name'];?></td>
								<td class="center"><?php echo $each_category['parent_category_name'];?></td>
								<td class="center">
								
																		
									<?php if($each_category['statusid']=="1") {?>
									<a href="<?php echo $this->baseUrl('admin/category/lock/categoryId/') . $each_category['category_id'];?>" onClick="return confirm('Do you want to continue?')">
									<span class="label label-success">Active</span>
									</a>
									<?php }?>
									<?php if($each_category['statusid']=="6") {?>
									<a href="<?php echo $this->baseUrl('admin/category/unlock/categoryId/') . $each_category['category_id'];?>" onClick="return confirm('Do you want to continue?')">
									<span class="label">Inactive</span>
									</a>							   
									<?php } ?>
									
								</td>
								<td class="center">								
									
									<a class="btn btn-info" href="<?php echo $this->baseUrl('admin/category/edit/categoryId/') . $each_category['category_id'];?>">
										<i class="icon-edit icon-white"></i>  
										Edit                                            
									</a>
									<a class="btn btn-danger" href="<?php echo $this->baseUrl('admin/category/delete/categoryId/') . $each_category['category_id'];?>" onClick="return confirm('Do you want to continue?')">
										<i class="icon-trash icon-white"></i> 
										Delete
									</a>
									
								</td>							
							</tr>
							<?php }?>
							
						  </tbody>
					  </table>            
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
			<!--/row-->
			<!--/row-->
			<!--/row-->
    
			  
				
<script type="text/javascript">
  $(document).ready(function() {
	  $(".error").fadeOut(6000);
});
</script>

		
