<div class="main_body">
<div class="left width-100">
	<div class="breadcrumbs">
		<span class="home-icon"></span>
		<a href="javascript:void(0)" class="home">Home</a>
		<span class="arrow"></span>
		<a href="javascript:void(0)" class="events">Video`s List</a>
		<div class="clear"></div>
	</div>
	<div id="events_page">
	
	
	
	Index View
	
	
	
	

	</div>
	<div class="clear"></div>
</div>
<div class="clear"></div>
</div>