<?php
	$experiance = $this->UserDetails[0];
?>
<form class="experiance_form">
<div class="desc">
	<div class="add_experience_form form">
		<div class="left width-50">
			<div class="row">
				<label>Company Name:</label>
				<input type="text" value="<?php echo $experiance["company_name"]; ?>"/>
			</div>
			<div class="row">
				<label>Location:</label>
				<input type="text" value="<?php echo $experiance["job_location"]; ?>"/>
			</div>
			<div class="row">
				<label>Country:</label>
				<select>
					<option>Please Select Country..</option>
					<option><?php echo $experiance["country_id"]; ?></option>
				</select>
			</div>
		</div>
		<div class="right width-50">
			<div class="row">
				<label>Position:</label>
				<input type="text" value="<?php echo $experiance["job_title"]; ?>"/>
			</div>
			<div class="row">
				<label>Industry:</label>
				<select>
					<option>Select Industry..</option>
					<option><?php echo $experiance["industry_id"]; ?></option>
				</select>
			</div>
			<div class="row">
				<label>State:</label>
				<select>
					<option>Select State..</option>
					<option><?php echo $experiance["state_id"]; ?></option>
				</select>
			</div>
		</div>
		<div class="row">
			<label class="width-15">Time Period : </label>
			<div class="fields-container">
				<div class="row">
					<select><option>Month</option><option><?php echo $experiance["from_month"]; ?></option></select>
					<select><option>Year</option><option><?php echo $experiance["from_year"]; ?></option></select>
					<select><option>Month</option><option><?php echo $experiance["to_month"]; ?></option></select>
					<select><option>Year</option><option><?php echo $experiance["to_year"]; ?></option></select>
					<input type="checkbox" style="margin-top: 7px;"<?php echo ($experiance["present_working"] ? 'checked="checked"' : ""); ?>><label>Present Working Here.</label>
					<div class="clear"></div>
				</div>
			</div>
		</div>
		<div class="row">
			<label class="width-15">Description : </label>
			<textarea style="width: 80%;" rows="6"><?php echo $experiance["company_description"]; ?></textarea>
			<div class="info"  style="margin-left: 15%;"><span class="blue">2500</span> Words Remaining.</div>
			<div class="text-right">
				<a class="button-dark add" href="javascript:void(0)"><span><span>Save</span></span></a>
				<a class="button-grey add" href="javascript:void(0)"><span><span>Cancel</span></span></a>
				<div class="clear"></div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>
</form>