<?php
	$experiance = $this->UserDetails[0];
?>
<script>
$(document).ready(function(){
	$("#experiance_form_<?php echo $experiance["experience_id"]; ?>").validate({
		rules : {
			company_name : {
				required : true
			}			
		},
		messages : {
			company_name : {
				required : "Company name is required."
			}
		},
		submitHandler: function(form) {
			var str = $("#experiance_form_<?php echo $experiance["experience_id"]; ?>").serialize();
			//$("#login_user").html("Loading...");
			$.ajax({
				type : "POST",
				url : baseUrl+"/profile/addeditexperiance",
				data : "type=edit&"+str,
				beforeSend : function() {
					$("#login_loading").show();
					$("#login_user").hide();
				},
				success : function(data) {
					$("#login_loading").hide();
					$("#login_user").html(data);
					$("#login_user").show();
					return false;
				}
			});
		}
	});
});
function submit_exp_form(form) {
	$("#"+form).submit();
}
</script>
<form name="experiance_form_<?php echo $experiance["experience_id"]; ?>" id="experiance_form_<?php echo $experiance["experience_id"]; ?>">
<div class="desc">
	<div class="add_experience_form form">
		<div class="left width-50">
			<div class="row">
				<label>Company Name:</label>
				<input type="text" value="<?php echo $experiance["company_name"]; ?>" id="company_name" name="company_name"/>
			</div>
			<div class="row">
				<label>Location:</label>
				<input type="text" value="<?php echo $experiance["job_location"]; ?>" id="job_location" name="job_location"/>
			</div>
			<div class="row">
				<label>Country:</label>
				<select id="country" name="country">
					<option>Please Select Country..</option>
					<option><?php echo $experiance["country_id"]; ?></option>
				</select>
			</div>
		</div>
		<div class="right width-50">
			<div class="row">
				<label>Position:</label>
				<input type="text" value="<?php echo $experiance["job_title"]; ?>" id="job_title" name="job_title"/>
			</div>
			<div class="row">
				<label>Industry:</label>
				<select id="industry" name="industry">
					<option>Select Industry..</option>
					<option><?php echo $experiance["industry_id"]; ?></option>
				</select>
			</div>
			<div class="row">
				<label>State:</label>
				<select id="state" name="state">
					<option>Select State..</option>
					<option><?php echo $experiance["state_id"]; ?></option>
				</select>
			</div>
		</div>
		<div class="row">
			<label class="width-15">Time Period : </label>
			<div class="fields-container">
				<div class="row">
					<select id="from_month" name="from_month"><option>Month</option><option><?php echo $experiance["from_month"]; ?></option></select>
					<select id="from_year" name="from_year"><option>Year</option><option><?php echo $experiance["from_year"]; ?></option></select>
					<select id="to_month" name="to_month"><option>Month</option><option><?php echo $experiance["to_month"]; ?></option></select>
					<select id="to_year" name="to_year"><option>Year</option><option><?php echo $experiance["to_year"]; ?></option></select>
					<input type="checkbox" style="margin-top: 7px;"<?php echo ($experiance["present_working"] ? 'checked="checked"' : ""); ?> id="present_working" name="present_working"><label>Present Working Here.</label>
					<div class="clear"></div>
				</div>
			</div>
		</div>
		<div class="row">
			<label class="width-15">Description : </label>
			<textarea style="width: 80%;" rows="6" id="description" name="description"><?php echo $experiance["company_description"]; ?></textarea>
			<div class="info"  style="margin-left: 15%;"><span class="blue">2500</span> Words Remaining.</div>
			<div class="text-right">
				<a class="button-dark add" href="javascript:void(0)" onclick="submit_exp_form('experiance_form_<?php echo $experiance["experience_id"]; ?>')"><span><span>Save</span></span></a>
				<a class="button-grey add" href="javascript:void(0)"><span><span>Cancel</span></span></a>
				<div class="clear"></div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>
<input type='hidden' id="exp_id" name="exp_id" value="<?php echo $experiance["experience_id"]; ?>" />
</form>