<div class="main_body">
<div class="left width-100">
						<div class="breadcrumbs">
							<span class="home-icon"></span><a href="javascript:void(0)" class="home">home</a><span class="arrow"></span><a href="javascript:void(0)" class="events">Profile</a>
							<div class="clear"></div>
						</div>
						<div class="profile_page">
							<div class="profile_main_page">
								<div class="profile_page_image">
									<img src="<?php echo $this->baseUrl('public/default'); ?>/images/user-images.png" title="GUNNAM CHOWDARY"/>
									<a class="button-light icon cam" href="javascript:void(0)"><span><span>Edit Profile Picture</span></span></a>
									<a href="javascript:void(0)">Delete Photo</a>
									<div class="clear">&nbsp;</div>
								</div>
								<div class="profile_page_detail">
									<a href="<?php echo $this->baseUrl('profile/edit/');?>" id="done-editing" class="button-big icon edit"><span><span>Done Editing</span></span></a>
									<div class="left width-100">
										<div class="title">
											<h2 class="title_have_image">GUNNAM CHOWDARY</h2>
										</div>
										<div class="profile_main_form form">
											<label>Name:</label>
											<div class="clear row">
													<input type="text" size="30"/>
													<input type="text" size="30"/>
											</div>
											<div class="row gender">
												<label>Gender : </label><input type="radio" /><span>Male</span><input type="radio" /><span>Female</span>
											</div>
											<label>Time Zone :</label>
											<div class="row">
												<select style="width: 55%;">
													<option>Asia/Kolkata (GMT+5.30)</option>
												</select>
											</div>
											<div class="text-right">
												<a class="button-dark add" href="javascript:void(0)"><span><span>Save</span></span></a>
												<a class="button-grey add" href="javascript:void(0)"><span><span>Cancel</span></span></a>
												<div class="clear"></div>
											</div>
										</div>
									</div>
									<div class="clear">&nbsp;</div>
								</div>
								<div class="clear"></div>
								<div class="profile-information">
									<div class="left width-20">
										<strong style="position: relative; line-height: 2;">My Referral Id <img src="images/refferalicon.png" style="position: absolute; right: -2px; top: -1px;" valign="middle"/></strong>
										<br/>
										http://example.com/?refid=222
									</div>
									<div class="frnds_infor">
										<img src="images/relation_icon.png" />
										<div class="left">
											<span>14</span>
											Friends
										</div>
									</div>
									<div class="clear">&nbsp;</div>
								</div>
								<div class="profile_info_block">
									<div class="header">
										<h2 class="title_have_image about">About<span class="icon"></span></h2>
									</div>
										<div class="desc about">
											<textarea>
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</textarea>
											<div class="clear">&nbsp;</div>
											<div class="clear">
												<div class="left">
													<span class="blue">1922</span> Characters Ramaining
												</div>
												<div class="right">
													<a class="button-dark add" href="javascript:void(0)"><span><span>Save</span></span></a>
													<a class="button-grey add" href="javascript:void(0)"><span><span>Cancel</span></span></a>
												</div>
											</div>
										</div>
									
								</div>
								<div class="profile_info_block">
									<div class="header">
										<h2 class="title_have_image exprce">Experience Details</h2>
										<a href="javascript:void(0)"><span>+</span>Add a Position</a>
									</div>
										<div class="desc">
											<div class="add_experience_form form">
												<div class="left width-50">
													<div class="row">
														<label>Company Name:</label>
														<input type="text"/>
													</div>
													<div class="row">
														<label>Location:</label>
														<input type="text"/>
													</div>
													<div class="row">
														<label>Country:</label>
														<select>
															<option>Please Select Country..</option>
														</select>
													</div>
												</div>
												<div class="right width-50">
													<div class="row">
														<label>Position:</label>
														<input type="text"/>
													</div>
													<div class="row">
														<label>Industry:</label>
														<select>
															<option>Select Industry..</option>
														</select>
													</div>
													<div class="row">
														<label>State:</label>
														<select>
															<option>Select State..</option>
														</select>
													</div>
												</div>
												<div class="row">
													<label class="width-15">Time Period : </label>
													<div class="fields-container">
														<div class="row">
															<select><option>Month</option></select>
															<select><option>Year</option></select>
															<select><option>Month</option></select>
															<select><option>Year</option></select>
															<input type="checkbox" style="margin-top: 7px;"><label>Present Working Here.</label>
															<div class="clear"></div>
														</div>
													</div>
												</div>
												<div class="row">
													<label class="width-15">Description : </label>
													<textarea style="width: 80%;" rows="6"></textarea>
													<div class="info"  style="margin-left: 15%;"><span class="blue">2500</span> Words Remaining.</div>
													<div class="text-right">
														<a class="button-dark add" href="javascript:void(0)"><span><span>Save</span></span></a>
														<a class="button-grey add" href="javascript:void(0)"><span><span>Cancel</span></span></a>
														<div class="clear"></div>
													</div>
												</div>
												<div class="clear"></div>
											</div>
											<div>
											<h2 class="title_have_image exprce">Sr Software Engineer<span class="icon"></span></h2>
											<span class="caption">VIP IT Services</span>
											<span class="information">March 2013 - To Present (0 years 3 months ) | Hyderabad</span>
<p>
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
										</div>
										<div>
											<h2 class="title_have_image exprce">Sr Software Engineer<span class="icon"></span></h2>
											<span class="caption">Company Name</span>
											<span class="information">March 2013 - To Present (0 years 3 months ) | Hyderabad</span>
<p>											
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
										</div>
										</div>
									
								</div>
								<div class="profile_info_block">
									<div class="header">
										<h2 class="title_have_image edu">Education Details</h2>
										<a href="javascript:void(0)"><span>+</span>Add Education</a>
									</div>
										<div class="desc">
											<div class="add_experience_form form">
												<div class="left width-50">
													<div class="row">
														<label>School Name:</label>
														<input type="text"/>
													</div>
													<div class="row">
														<label>Time Period:</label>
														<div class="fields-container">
															<div class="row">
																<input  size="10" type="text" ><label>to</label><input  size="10" type="text" >
																<div class="clear"></div>
															</div>
														</div>
													</div>
													<div class="row">
														<label>Degree:</label>
														<input type="text"/>
													</div>
													<div class="row">
														<label>Field of Study:</label>
														<input type="text"/>
													</div>
												</div>
												<div class="row">
													<label class="width-15">Description : </label>
													<textarea style="width: 80%;" rows="6"></textarea>
													<div class="info"  style="margin-left: 15%;"><span class="blue">2500</span> Words Remaining.</div>
													<div class="text-right">
														<a class="button-dark add" href="javascript:void(0)"><span><span>Save</span></span></a>
														<a class="button-grey add" href="javascript:void(0)"><span><span>Cancel</span></span></a>
														<div class="clear"></div>
													</div>
												</div>
												<div class="clear"></div>
											</div>
											<div>
											<h2 class="title_have_image exprce">IACR Engg College<span class="icon"></span></h2>
											<span class="caption">B Tech,ECE</span>
											<span class="information">2002-2006</span>
<p>
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
										</div>
										<div>
											<h2 class="title_have_image exprce">School Name<span class="icon"></span></h2>
											<span class="caption">Inter, MPC</span>
											<span class="information">2001-2002</span>
<p>											
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
										</div>
										</div>
									
								</div>
								<div class="profile_info_block">
									<div class="header">
										<h2 class="title_have_image prsnlinformtn">Personal Information</h2>
										<a href="javascript:void(0)"><span>+</span>Add/Change</a>
									</div>
										<div class="desc">
											<div class="add_experience_form form">
												<div class="row">
													<label class="width-15">Birthday : </label>
													<div class="fields-container">
															<select><option>December</option></select>
															<select><option>20</option></select>
															<select><option>1983</option></select>
															<input type="checkbox" style="margin-top: 7px;"><label>Show only month & day to your friends.</label>
															<div class="clear"></div>
													</div>
												</div>
												<div class="left width-50">
													<div class="row">
														<label>Marital Status :</label>
														<select><option>Single</option></select>
													</div>
												</div>
												<div class="row">
													<label class="width-15">Interests : </label>
													<textarea style="width: 80%;" rows="6"></textarea>
													<div class="info"  style="margin-left: 16%;">Examples: Management training. new technologies, investing</div>
												</div>
												<div class="row">
													<label class="width-15">Honors & Awards : </label>
													<textarea style="width: 80%;" rows="6"></textarea>
												</div>
												<div class="row">
													<label class="width-15">Contact For : </label>
													<textarea style="width: 80%;" rows="6"></textarea>
													<div class="info"  style="margin-left: 16%;">Tip: Advice for Contacting You</div>
												</div>
												<div class="text-right">
														<a class="button-dark add" href="javascript:void(0)"><span><span>Save</span></span></a>
														<a class="button-grey add" href="javascript:void(0)"><span><span>Cancel</span></span></a>
														<div class="clear"></div>
												</div>
												<div class="clear"></div>
											</div>
										</div>
									
								</div>
								<div class="profile_info_block">
									<div class="header">
										<h2 class="title_have_image address">Address</h2>
										<a href="javascript:void(0)"><span>+</span>Add/Change</a>
									</div>
										<div class="desc">
											<div class="add_experience_form form">
												<div class="left width-50">
													<h2 class="black">Home</h2>
													<div class="row">
														<label>Street :</label>
														<textarea></textarea>
													</div>
													<div class="row">
														<label>City :</label>
														<input type="text"/>
													</div>
													<div class="row">
														<label>Country :</label>
														<select><option>India</option></select>
													</div>
													<div class="row">
														<label>State :</label>
														<select><option>Andra Pradesh</option></select>
													</div>
													<div class="row">
														<label>Zip Code :</label>
														<input type="text"/>
													</div>
												</div>
												<div class="left width-50">
													<h2 class="black">Office</h2>
													<div class="row">
														<label>Street :</label>
														<textarea></textarea>
													</div>
													<div class="row">
														<label>City :</label>
														<input type="text"/>
													</div>
													<div class="row">
														<label>Country :</label>
														<select><option>India</option></select>
													</div>
													<div class="row">
														<label>State :</label>
														<select><option>Andra Pradesh</option></select>
													</div>
													<div class="row">
														<label>Zip Code :</label>
														<input type="text"/>
													</div>
												</div>
												<div class="clear"></div>
												<div class="text-right">
														<a class="button-dark add" href="javascript:void(0)"><span><span>Save</span></span></a>
														<a class="button-grey add" href="javascript:void(0)"><span><span>Cancel</span></span></a>
														<div class="clear"></div>
												</div>
											</div>
											<div class="clear"></div>
										</div>
								</div>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
					</div>
<div class="clear"></div>
</div>