<?php
$education = $this->UserDetails["education"];
?>
<div class="header">
	<h2 class="title_have_image edu">Education Details</h2>
	<a href="javascript:void(0);" class="edit_education edit_education_new" id="edit_education_new"><span>+</span>Add Education</a>
</div>
<div class="desc education_views">
	<div class="education_view" id="education_view_new" style="display:none;"></div>
	<div class="education_edit" id="education_edit_new" style="display:none;"></div>
	<?php foreach($education as $key => $value) { ?>
	<div class="education_view" id="education_view_<?php echo $value["education_id"]; ?>">
		<h2 class="title_have_image educat"><?php echo $value["school_name"]; ?><span class="edit_education edit_education_<?php echo $value["education_id"]; ?> icon" id="edit_education_<?php echo $value["education_id"]; ?>"></span><div id="education_edit_loading_<?php echo $value["education_id"]; ?>" style="display:none;"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" /></div></h2>
		<span class="caption"><?php echo $value["school_name"].($value["specialization"] ? ", ".$value["specialization"] : ""); ?></span>
		<span class="information"><?php echo ($value["from_month"]) ? date("F", mktime(0, 0, 0, $value["from_month"], 10)) : 0; ?> <?php echo $value["from_year"]; ?> - To <?php echo ($value["present_working"]) ? "Present" : (($value["to_month"]) ? date("F", mktime(0, 0, 0, $value["to_month"], 10)) : 0)." ".$value["to_year"]; ?></span>
		<p><?php echo $value["education_notes"]; ?></p>
	</div>
	<div class="education_edit" id="education_edit_<?php echo $value["education_id"]; ?>" style="display:none;"></div>
	<?php } ?>
</div>