<?php
	$education = $this->UserDetails;
	$error = (isset($education["error"])) ? 1 : 0;
	if($error) {
		$edu_id = (isset($education["edu_id"])) ? $education["edu_id"] : 0;
		echo $this->action('addediteducation', 'profile', 'default', array('input_type'=>'error', 'education_idd'=>$edu_id));
	}
	else {
		$dis_type = (isset($education["dis_type"])) ? 1 : 0;
		if($dis_type) {
?>
<div class="education_view" id="education_view_<?php echo $education["education_id"]; ?>">
	<?php } ?>
	<h2 class="title_have_image exprce"><?php echo $education["job_title"]; ?>
		<span class="edit_education edit_education_<?php echo $education["education_id"]; ?> icon" id="edit_education_<?php echo $education["education_id"]; ?>"></span>
		<div id="education_edit_loading_<?php echo $education["education_id"]; ?>" style="display:none;">
			<img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" />
		</div>
	</h2>
	<span class="caption"><?php echo $education["school_name"]; ?></span>
	<span class="information"><?php echo ($education["from_month"]) ? date("F", mktime(0, 0, 0, $education["from_month"], 10)) : ""; ?> <?php echo $education["from_year"]; ?> - To <?php echo (($education["to_month"]) ? date("F", mktime(0, 0, 0, $education["to_month"], 10)) : "")." ".$education["to_year"]; ?></span>
	<p><?php echo $education["education_notes"]; ?></p>
<?php if($dis_type) { ?>
</div>
<div class="education_edit" id="education_edit_<?php echo $education["education_id"]; ?>" style="display:none;"></div>
<?php } } ?>