<?php 

$profile = $this->UserDetails["profile"][0];
$address = $this->UserDetails["address"];
$experiance = $this->UserDetails["experiance"];
$education = $this->UserDetails["education"];
$timezones = $this->UserDetails["timezones"];
$present_cmp = ($profile["company_name"]) ? $profile["company_name"].($profile["country_name"] ? " - ".$profile["country_name"] : "") : "";
//$previous_cmp = "";
$current_status = ($profile["job_title"] && $profile["company_name"]) ? $profile["job_title"].(($profile["company_name"]) ? " at ".$profile["company_name"] : "") : "";
$recent_education = ($profile["degree"]) ? $profile["degree"]." at ".$profile["school_name"] : "";

?>
<div class="main_body" style="float:left;width:100%;">
<div class="left width-100">
						<div class="breadcrumbs">
							<span class="home-icon"></span><a href="javascript:void(0)" class="home">home</a><span class="arrow"></span><a href="javascript:void(0)" class="events">Profile</a>
							<div class="clear"></div>
						</div>
						<div class="profile_page">
							<div class="profile_main_page">
								<div class="profile_page_image">
									<div align="center">
									<?php
										$path = $this->baseUrl('public/uploads')."/user_images/";
										//$image_name = "No_Image_Available.jpg";
										$image_name = "profile.png";										
										$image_status = 0;
										if($profile["image_path"] && file_exists( $_SERVER['DOCUMENT_ROOT'].$path."crop_200_200/".$profile["image_path"] )) {
											$path = $path."crop_200_200/";
											$image_name = $profile["image_path"];
											$image_status = 1;
										}
									?>
									<img src="<?php echo $path.$image_name; ?>" title="GUNNAM CHOWDARY" width="200" height="200"/>
									<?php ?>
									</div>
									<!--a class="button-light icon cam" href="javascript:void(0)" id="image_upload"><span>Edit Profile Picture</span></a-->
									<?php if($image_status) { ?>
									<form id="upload_image" name="upload_image" action="<?php echo $this->baseUrl('profile/upload/');?>" method="post" style="text-align:center;">
										<div align="center" class="profile_image_change profile_image_edit">Edit Profile Picture</div>
										<input id="avatar" type="file" name="avatar" class="profile_image_file_button" style="position: absolute; filter: alpha(opacity=0); font-family: Arial; font-size: 118px; top: 0px; cursor: pointer; right: 0px; opacity: 0;"/>
									</form>
									<a href="javascript:void(0);" id="delete_image">Delete Photo</a>
									<?php } else { ?>
									<form id="upload_image" name="upload_image" action="<?php echo $this->baseUrl('profile/upload/');?>" method="post" style="text-align:center;">
										<div align="center" class="profile_image_change profile_image_upload">Upload Profile Picture</div>
										<input id="avatar" type="file" name="avatar" class="profile_image_file_button" style="position: absolute; filter: alpha(opacity=0); font-family: Arial; font-size: 118px; top: 0px; cursor: pointer; right: 0px; opacity: 0;"/>
									</form>
									<?php } ?>
									<div class="clear">&nbsp;</div>
								</div>
								<div class="profile_page_detail">
									<!--a href="<?php echo $this->baseUrl('profile/edit/');?>" id="done-editing" class="button-big icon edit"><span><span>Done Editing</span></span></a-->
									<div class="left width-100" id="member_profile_title">
										<div class="title">
											<h2 class="title_have_image"><label id="h2_name"><?php echo $profile["firstname"]." ".$profile["lastname"]; ?></label><span class="icon" id="member_profile_title_icon"></span></h2>
											<span class="caption"><?php echo $current_status; ?></span>
										</div>
										<?php if($profile["timezone_id"]) { ?>
										<div class="timezone" id="timezone_dis"><?php foreach($timezones as $value) { echo ($value["timezone_id"] == $profile["timezone_id"]) ? $value["timezone_location"]." ".$value["gmt"] : ""; } ?></div>
										<?php } ?>
										<div class="details">
											<?php if($present_cmp) { ?>
											<label style="width:10%">Current:</label><span class="blue"><?php echo $present_cmp; ?></span>
											<?php } ?>
											<!--label>Previous:</label><span class="blue"><?php echo $previous_cmp; ?></span-->
											<div class="clear">&nbsp;</div>
											<?php if($recent_education) { ?>
											<label style="width:13%">Education:</label><span class="blue"><?php echo $recent_education; ?></span>
											<?php } ?>
										</div>
										<div class="clear">&nbsp;</div>
										<div class="clear">
											<a href="javascript:void(0)" class="button-light blue icon mail"><span><span><?php echo $profile["emailid"]; ?></span></span></a>
											<!--a href="javascript:void(0)" class="button-light blue icon skype"><span><span>vip.veera</span></span></a-->
											<a href="javascript:void(0)" class="button-light blue icon phone"><span><span><?php echo $profile["phonenumber"]; ?></span></span></a>
										</div>
									</div>
									<div class="left width-100" id="member_profile_title_edit" style="display:none">
										<form class="member_profile_title_edit">
										<div class="profile_main_form form">
											<label>Name:</label>
											<div class="clear row">
													<input type="text" size="30" name="fname" id="fname" value="<?php echo $profile["firstname"]; ?>"/>
													<input type="text" size="30" name="lname" id="lname" value="<?php echo $profile["lastname"]; ?>"/>
											</div>
											<div class="row gender">
												<label>Gender : </label><input type="radio" name="gender" id="gender" value="Male" <?php echo ($profile["gender"] == "Male" || $profile["gender"] == "") ? "checked" : ""; ?>/><span>Male</span><input type="radio" name="gender" id="gender" value="Female" <?php echo ($profile["gender"] == "Female") ? "checked" : ""; ?>/><span>Female</span>
											</div>
											<label>Time Zone :</label>
											<div class="row">
												<select style="width: 55%;" name="timezone" id="timezone">
													<?php foreach($timezones as $value) { ?>
													<option value="<?php echo $value["timezone_id"]; ?>" <?php echo ($value["timezone_id"] == $profile["timezone_id"]) ? "selected" : ""; ?>><?php echo $value["timezone_location"]." ".$value["gmt"]; ?></option>
													<?php } ?>
												</select>
											</div>
											<div class="text-right">
												<a class="button-dark add" href="javascript:void(0);" id="save_member_profile_title"><span><span>Save</span></span></a>
												<a class="button-grey add common_cancel_btn" href="javascript:void(0);" id="cancel_member_profile_title"><span><span>Cancel</span></span></a>
												<div class="clear"></div>
											</div>
										</div>
										</form>
									</div>
									<div class="clear">&nbsp;</div>
								</div>
								<div class="clear"></div>
								<div class="profile-information">
									<div class="left width-20">
										<strong style="position: relative; line-height: 2; font-size:14px;">
										Edit Your Profile</strong>										
									</div>
									<div class="frnds_infor">
										<img src="images/relation_icon.png" />
										<div class="left">
											<span>14</span>
											Friends
										</div>
									</div>
									<div class="clear">&nbsp;</div>
								</div>
								<div class="profile_info_block">
									<div class="header">
										<h2 class="title_have_image about">About<span class="edit_aboutus icon"></span></h2>
									</div>
										<div class="desc" id="view_about_us">
											<?php if($profile["about_us"]) echo $profile["about_us"]; else { ?>
											<div class="add_about edit_aboutus" id="mem_abt_edit" > <a href="javascript:void(0)"></a>Add About</div>
											<?php } ?>
										</div>
										<div class="desc about" style="display:none;" id="edit_about_us">
											<form name="form_about_us" id="form_about_us" method="POST" action="#">
												<textarea name="about_us" id="about_us" class="auto_count"><?php echo $profile["about_us"]; ?></textarea>
												<div class="info">
													<span class="blue"><?php echo 500 - strlen($profile["about_us"]); ?></span> Characters Remaining
												</div>
												<div class="clear">&nbsp;</div>
												<div class="clear">
													<div class="right">
														<a class="button-dark add" href="javascript:void(0);" onclick="submit_form()"><span><span>Save</span></span></a>
														<a class="button-grey add common_cancel_btn" href="javascript:void(0)" onclick="cancel_form()"><span><span>Cancel</span></span></a>
													</div>
												</div>
											</form>
											<div id="loading_about_us" style="display:none;"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" /></div>
										</div>
										<div id="login_loading" style="display:none;"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" /></div>
								</div>
								<div class="profile_info_block all_experiances_view">
									<div class="header">
										<h2 class="title_have_image exprce">Experience Details</h2>
										<a class="edit_experiance edit_experiance_new" id="edit_experiance_new" href="javascript:void(0)"><span>+</span>Add a Position</a>
									</div>
										<div class="desc experiance_views">
										<div class="experiance_view" id="experiance_view_new" style="display:none;"></div>
										<div class="experiance_edit" id="experiance_edit_new" style="display:none;"></div>
										<?php if(count($experiance) > 0 ) { ?>
										<?php foreach($experiance as $key => $value) { ?>
										<div class="experiance_view" id="experiance_view_<?php echo $value["experience_id"]; ?>">
											<h2 class="title_have_image exprce"><?php echo $value["job_title"]; ?><span class="edit_experiance edit_experiance_<?php echo $value["experience_id"]; ?> icon" id="edit_experiance_<?php echo $value["experience_id"]; ?>"></span><div id="experiance_edit_loading_<?php echo $value["experience_id"]; ?>" style="display:none;"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" /></div></h2>
											<span class="caption"><?php echo $value["company_name"].($value["job_location"] ? ", ".$value["job_location"] : ""); ?></span>
											<?php
												$date1 = $value["from_year"]."-".$value["from_month"]."-1";
												$date2 = $value["to_year"]."-".$value["to_month"]."-1";
												$diff = abs(strtotime($date2) - strtotime($date1));
												$years = floor($diff / (365*60*60*24));
												$months = floor(($diff - $years * 365*60*60*24) / (30*60*60*24));
												$days = floor(($diff - $years * 365*60*60*24 - $months*30*60*60*24)/ (60*60*24));
												$duration = "(".$years." years ".$months." months)";
											?>
											<span class="information"><?php echo ($value["from_month"]) ? date("F", mktime(0, 0, 0, $value["from_month"], 10)) : 0; ?> <?php echo $value["from_year"]; ?> - To <?php echo ($value["present_working"]) ? "Present" : (($value["to_month"]) ? date("F", mktime(0, 0, 0, $value["to_month"], 10)) : 0)." ".$value["to_year"]; ?> <?php echo $duration; ?></span>
											<p><?php echo $value["company_description"]; ?></p>
										</div>
										<div class="experiance_edit" id="experiance_edit_<?php echo $value["experience_id"]; ?>" style="display:none;"></div>
										<?php } } else { ?>
										<div class="add_about edit_experiance edit_experiance_new edit_experiance_bar" id="edit_experiance_new"> <a href="javascript:void(0)"></a>Add Experience</div>
										<?php } ?>
										</div>
									
								</div>
								<div class="profile_info_block all_education_view">
									<div class="header">
										<h2 class="title_have_image edu">Education Details</h2>
										<a href="javascript:void(0);" class="edit_education edit_education_new" id="edit_education_new"><span>+</span>Add Education</a>
									</div>
										<div class="desc education_views">
										<div class="education_view" id="education_view_new" style="display:none;"></div>
										<div class="education_edit" id="education_edit_new" style="display:none;"></div>
										<?php if(count($education) > 0 ) { ?>
											<?php foreach($education as $key => $value) { ?>
											<div class="education_view" id="education_view_<?php echo $value["education_id"]; ?>">
												<h2 class="title_have_image educat"><?php echo $value["school_name"]; ?><span class="edit_education edit_education_<?php echo $value["education_id"]; ?> icon" id="edit_education_<?php echo $value["education_id"]; ?>"></span><div id="education_edit_loading_<?php echo $value["education_id"]; ?>" style="display:none;"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" /></div></h2>
												<span class="caption"><?php echo $value["degree"].($value["specialization"] ? ", ".$value["specialization"] : ""); ?></span>
												<span class="information"><?php echo ($value["from_month"]) ? date("F", mktime(0, 0, 0, $value["from_month"], 10)) : 0; ?> <?php echo $value["from_year"]; ?> - To <?php echo ($value["present_working"]) ? "Present" : (($value["to_month"]) ? date("F", mktime(0, 0, 0, $value["to_month"], 10)) : 0)." ".$value["to_year"]; ?></span>
												<p><?php echo $value["education_notes"]; ?></p>
											</div>
											<div class="education_edit" id="education_edit_<?php echo $value["education_id"]; ?>" style="display:none;"></div>
											<?php } } else { ?>
										<div class="add_about edit_education edit_education_new edit_education_bar" id="edit_education_new"> <a href="javascript:void(0)"></a>Add Education</div>
										<?php } ?>
										</div>
									
								</div>
								<div class="profile_info_block">
									<div class="header">
										<h2 class="title_have_image prsnlinformtn">Personal Information</h2>
										<a href="javascript:void(0);" class="edit_personal" id="edit_personal"><span>+</span>Add/Change</a>
									</div>
									<div class="desc personal_view" id="personal_view">
										<?php if($profile["date_of_birth"] != "0000-00-00" || $profile["marital_status"] || $profile["interests"] || $profile["phonenumber"]) { ?>
										<ul>
											<?php if($profile["date_of_birth"] != "0000-00-00"){ ?>
											<li><label>Birthday : </label><span class="blue"><?php echo $profile["date_of_birth"]; ?></span></li>
											<?php } 
											if($profile["marital_status"]) {
											?>
											<li><label>Marital Status : </label><span class="blue"><?php echo $profile["marital_status"]; ?></span></li>
											<?php } 
											if($profile["interests"]) {
											?>
											<li><label>Interests : </label><span class="blue"><?php echo $profile["interests"]; ?></span></li>
											<?php }
											if($profile["phonenumber"]) {
											?>
											<li><label>Phone : </label><span class="blue"><?php echo $profile["phonenumber"]; ?></span></li>
											<?php } ?>
										</ul>
										<?php } else { ?>
										<div class="add_about edit_personal" id="mem_contact"> <a href="javascript:void(0)"></a>Add Personal Information</div>
										<?php } ?>
									</div>
								</div>
								<div class="profile_info_block">
									<div class="header">
										<h2 class="title_have_image address">Address</h2>
										<a href="javascript:void(0)" class="edit_address" id="edit_address"><span>+</span>Add/Change</a>
									</div>
										<div class="desc address_view" id="address_view">
											<?php $addr_flag = 0; if(count($address) > 0) { foreach($address as $key => $value) { ?>
											<?php if($value["address1"] || $value["address2"] || $value["street"] || $value["city"] || $value["name"] || $value["country"] || $value["postal_code"]) { $addr_flag = 1; ?>
												<div class="left width-50">
													<h3><?php echo $value["address_type"]; ?></h3>
													<?php echo $value["address1"].($value["address2"] ? ", ".$value["address2"] : ""); echo ($value["street"]) ? "," : ""; ?><br/>
													<?php echo $value["street"]; echo ($value["city"]) ? "," : ""; ?><br/>
													<?php echo $value["city"]; echo ($value["name"]) ? "," : ""; ?><br/>
													<?php echo $value["name"]; echo ($value["country"]) ? "," : ""; ?><br/>
													<?php echo $value["country"]; echo ($value["postal_code"]) ? "," : ""; ?><br/>
													<?php echo $value["postal_code"]; ?>.
												</div>
											<?php } } } else { $addr_flag = 1; ?>
											<div class="add_about edit_address" id="mem_contact"> <a href="javascript:void(0)"></a>Add Address</div>
											<?php } if(!$addr_flag) { ?>
											<div class="add_about edit_address" id="mem_contact"> <a href="javascript:void(0)"></a>Add Address</div>
											<?php } ?>
											<div class="clear"></div>
										</div>
								</div>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
					</div>
<div class="clear"></div>
</div>
<div id="popup_content" name="popup_content" class="" style="display:none;width:auto;height:auto;">
	
</div>
<div class="modal"><!-- Place at bottom of page --></div>
<div id="member_success_msg" class="member_success_msg" style="display: none;"></div>