<?php 

$profile = $this->UserDetails["profile"][0];
$address = $this->UserDetails["address"];
$experiance = $this->UserDetails["experiance"];
$education = $this->UserDetails["education"];
$present_cmp = $profile["company_name"]." - "."country_name";
$previous_cmp = "";
$current_status = $profile["job_title"]." at ".$profile["company_name"];
$recent_education = $profile["degree"]." at ".$profile["school_name"];

?>
<div class="main_body" style="float:left;">
<div class="left width-100">
						<div class="breadcrumbs">
							<span class="home-icon"></span><a href="javascript:void(0)" class="home">home</a><span class="arrow"></span><a href="javascript:void(0)" class="events">Profile</a>
							<div class="clear"></div>
						</div>
						<div class="profile_page">
							<div class="profile_main_page">
								<div class="profile_page_image">
									<img src="<?php echo $this->baseUrl('public/default').$profile["image_path"]; ?>" title="GUNNAM CHOWDARY"/>
									<a class="button-light icon cam" href="javascript:void(0)"><span><span>Edit Profile Picture</span></span></a>
									<a href="javascript:void(0)">Delete Photo</a>
									<div class="clear">&nbsp;</div>
								</div>
								<div class="profile_page_detail">
									<a href="<?php echo $this->baseUrl('profile/edit/');?>" id="done-editing" class="button-big icon edit"><span><span>Done Editing</span></span></a>
									<div class="left width-100">
									<div class="title">
										<h2 class="title_have_image"><?php echo $profile["firstname"]." ".$profile["lastname"]; ?><span class="icon"></span></h2>
										<span class="caption"><?php echo $current_status; ?></span>
									</div>
										<div class="timezone"><?php echo $profile["timezone_id"]; ?></div>
										<div class="details">
											<label>Current:</label><span class="blue"><?php echo $present_cmp; ?></span>
											<!--label>Previous:</label><span class="blue"><?php echo $previous_cmp; ?></span-->
											<div class="clear">&nbsp;</div>
											<label>Education:</label><span class="blue"><?php echo $recent_education; ?></span>
										</div>
										<div class="clear">&nbsp;</div>
										<div class="clear">
											<a href="javascript:void(0)" class="button-light blue icon mail"><span><span><?php echo $profile["emailid"]; ?></span></span></a>
											<a href="javascript:void(0)" class="button-light blue icon skype"><span><span>vip.veera</span></span></a>
											<a href="javascript:void(0)" class="button-light blue icon phone"><span><span><?php echo $profile["phonenumber"]; ?></span></span></a>
										</div>
									</div>
									<div class="clear">&nbsp;</div>
								</div>
								<div class="clear"></div>
								<div class="profile-information">
									<div class="left width-20">
										<strong style="position: relative; line-height: 2;">My Referral Id <img src="images/refferalicon.png" style="position: absolute; right: -2px; top: -1px;" valign="middle"/></strong>
										<br/>
										http://example.com/?refid=<?php echo $profile["userid"]; ?>
									</div>
									<div class="frnds_infor">
										<img src="images/relation_icon.png" />
										<div class="left">
											<span>14</span>
											Friends
										</div>
									</div>
									<div class="clear">&nbsp;</div>
								</div>
								<div class="profile_info_block">
									<div class="header">
										<h2 class="title_have_image about">About<span class="edit_aboutus icon"></span></h2>
									</div>
										<div class="desc" id="view_about_us">
											<?php echo $profile["about_us"]; ?>
										</div>
										<div class="desc about" style="display:none;" id="edit_about_us">
											<form name="form_about_us" id="form_about_us" method="POST" action="#">
												<textarea name="about_us" id="about_us"><?php echo $profile["about_us"]; ?></textarea>
												<div class="clear">&nbsp;</div>
												<div class="clear">
													<div class="left">
														<span class="blue">1922</span> Characters Remaining
													</div>
													<div class="right">
														<a class="button-dark add" href="javascript:void(0);" onclick="submit_form()"><span><span>Save</span></span></a>
														<a class="button-grey add" href="javascript:void(0)"><span><span>Cancel</span></span></a>
													</div>
												</div>
											</form>
											<div id="loading_about_us" style="display:none;"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" /></div>
										</div>
										<div id="login_loading" style="display:none;"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" /></div>
								</div>
								<div class="profile_info_block">
									<div class="header">
										<h2 class="title_have_image exprce">Experience Details</h2>
										<a href="javascript:void(0)"><span>+</span>Add a Position</a>
									</div>
										<div class="desc">
										<?php foreach($experiance as $key => $value) { ?>
										<div class="experiance_view" id="experiance_view_<?php echo $key+1; ?>">
											<h2 class="title_have_image exprce"><?php echo $value["job_title"]; ?><span class="icon"></span></h2>
											<span class="caption"><?php echo $value["company_name"]; ?></span>
											<span class="information"><?php echo $value["from_month"]; ?> <?php echo $value["from_year"]; ?> - To <?php echo ($value["present_working"]) ? "Present" : $value["to_month"]." ".$value["to_year"]; ?> (0 years 3 months ) | <?php echo $value["job_location"]; ?></span>
											<p><?php echo $value["company_description"]; ?></p>
										</div>
										<div class="experiance_edit" id="experiance_edit_<?php echo $key+1; ?>">
											<form class="experiance_form" >
												
											</form>
										</div>
										<?php } ?>									
										</div>
									
								</div>
								<div class="profile_info_block">
									<div class="header">
										<h2 class="title_have_image edu">Education Details</h2>
										<a href="javascript:void(0)"><span>+</span>Add Education</a>
									</div>
										<div class="desc">
										<?php foreach($education as $key => $value) { ?>
										<div class="education" id="">
											<h2 class="title_have_image exprce"><?php echo $value["school_name"]; ?><span class="icon"></span></h2>
											<span class="caption"><?php echo $value["school_name"].", ".$value["specialization"]; ?></span>
											<span class="information"><?php echo $value["from_year"]; ?>-<?php echo $value["to_year"]; ?></span>
											<p><?php echo $value["education_notes"]; ?></p>
										</div>
										<?php } ?>
										</div>
									
								</div>
								<div class="profile_info_block">
									<div class="header">
										<h2 class="title_have_image prsnlinformtn">Personal Information</h2>
										<a href="javascript:void(0)"><span>+</span>Add/Change</a>
									</div>
										<div class="desc">
											<ul>
												<li><label>Birthday : </label><span class="blue"><?php echo $profile["date_of_birth"]; ?></span></li>
												<li><label>Marital Status : </label><span class="blue"><?php echo $profile["marital_status"]; ?></span></li>
												<li><label>Interests : </label><span class="blue"><?php echo $profile["interests"]; ?></span></li>
												<li><label>Honors & Awards : </label><span class="blue">Honors & Awards Honors & Awards Honors & Awards</span></li>
												<li><label>Contact For : </label><span class="blue">Contact For Contact For Contact For</span></li>
												<li><label>Personal : </label><span class="blue"><?php echo $profile["phonenumber"]; ?></span></li>
												<li><label>Website : </label><span class="blue">http://www.telugump3lyrics.com</span></li>
												<li><label>Skype : </label><span class="blue">vip.veera</span></li>	
											</ul>
										</div>
									
								</div>
								<div class="profile_info_block">
									<div class="header">
										<h2 class="title_have_image address">Address</h2>
										<a href="javascript:void(0)"><span>+</span>Add/Change</a>
									</div>
										<div class="desc">
											<?php foreach($address as $key => $value) { ?>
												<div class="left width-50">
													<h3><?php echo $value["address_type"]; ?></h3>
													<?php echo $value["address1"].", ".$value["address2"]; ?>,<br/>
													<?php echo $value["street"]; ?>,<br/>
													<?php echo $value["city"]; ?>,<br/>
													<?php echo $value["state_id"]; ?>,<br/>
													<?php echo $value["country_id"]; ?>,<br/>
													<?php echo $value["postal_code"]; ?>.
												</div>
											<?php } ?>
											<div class="clear"></div>
										</div>
								</div>
							</div>
							<div class="clear"></div>
						</div>
						<div class="clear"></div>
					</div>
<div class="clear"></div>
</div>