<?php
	$experiance = $this->UserDetails[0];
?>
<h2 class="title_have_image exprce"><?php echo $experiance["job_title"]; ?><span class="edit_experiance edit_experiance_<?php echo $experiance["experience_id"]; ?> icon"></span><div id="experiance_edit_loading_<?php echo $experiance["experience_id"]; ?>" style="display:none;"><img src="<?php echo $this->baseUrl('public/default'); ?>/images/ajax-loader.gif" /></div></h2>
<span class="caption"><?php echo $experiance["company_name"]; ?></span>
<span class="information"><?php echo $experiance["from_month"]; ?> <?php echo $experiance["from_year"]; ?> - To <?php echo ($experiance["present_working"]) ? "Present" : $experiance["to_month"]." ".$experiance["to_year"]; ?> (0 years 3 months ) | <?php echo $experiance["job_location"]; ?></span>
<p><?php echo $experiance["company_description"]; ?></p>